### PR TITLE
I1281 implement reduced time step option for thermal network matrix

### PR DESCRIPTION
**Pull request by roglen**
This PR adds an option to the config file to run the thermal network matrix with a reduced number of time steps, specifically one week per month. This feature is relevant for thermal-network optimization only. 

To assure that optimization and plots run, for the csv outputs values are extrapolated to 8760 values. This is done in the following way:
One week per month = 2016 hours
This data is repeated four times = 8064
For the remaining timesteps, it is important that the average value of the data is not changed. To assure this. The remaining timesteps are filled with the average values of that specific dataframe. 

NOTE: Plots will run in this option but are not recommended as they are in no way realistic. The purpose of the data here is to assure that pressure losses and heat losses (.csv files) can be read in from the optimization, which expects 8760 timesteps. So only minimum, maximum and sum of values needs to be retained. 

The outputs were tested for several networks in DC and DH modes, results have been added to the cea-validation repository. 

To review PR:
- [x]  set 'use-representative-week-per-month' to 'true' in the new config file, and run the thermal-network-matrix script in DH and DC mode
- [x] verify that created output files all have 8760 timesteps 
- [x]  set 'use-representative-week-per-month' to 'false' (default) in the new config file, and run the thermal-network-matrix script in DC mode (DH already tested)
- [x] verify that outputs have not changed in comparison to master, and that the cea-optimization runs successfully. Results will not be exactly identical if the minimum-mass-flows code part is activated, since this allows for deviations in mass flows, e.g. running the same network several times will give slightly different results. Still, the results should be similar. If no minimum mass flows are present, results should be identical.

### CODE REVIEW

**Comment by roglen** [comment]
@JIMENOFONSECA This branch is ready to merge

**Comment by JIMENOFONSECA** [comment]
@shanshanhsieh does optimisation and the plots run too?

**Comment by shanshanhsieh** [comment]
@daren-thomas could you please let us know which part of the check failed?
`cea test` ran through on my laptop

**Comment by daren-thomas** [comment]
@shanshanhsieh according to the jenkins, this is where it went wrong:

```

C:\Program Files (x86)\Jenkins\workspace\run cea test for pull requests>cea test 
Running `cea test` with the following parameters:
- test:reference-cases = ['all']
- test:tasks = ['all']
- test:verbosity = 1
Configuring task download_radiation
Configuring task run_embodied_energy
Configuring task run_heatmaps
Configuring task run_thermal_network_matrix
Configuring task run_emissions_mobility
Configuring task download_reference_cases
Configuring task run_calibration
Configuring task run_emissions_operation
Configuring task run_scenario_plots
Configuring task run_sensitivity
Configuring task run_unit_tests
Configuring task run_data_helper
Configuring task run_demand
.  download_reference_cases
########################################
TaskError - taskid:download_reference_cases
PythonAction Error
Traceback (most recent call last):
  File "C:\Users\darthoma\AppData\Local\conda\conda\envs\ceatest\lib\site-packages\doit\action.py", line 383, in execute
    returned_value = self.py_callable(*self.args, **kwargs)
  File "C:\Users\darthoma\AppData\Local\conda\conda\envs\ceatest\lib\site-packages\cea\tests\dodo.py", line 130, in download_reference_cases
    archive.extractall(REFERENCE_CASE_PATH)
  File "C:\Users\darthoma\AppData\Local\conda\conda\envs\ceatest\lib\zipfile.py", line 1043, in extractall
    self.extract(zipinfo, path, pwd)
  File "C:\Users\darthoma\AppData\Local\conda\conda\envs\ceatest\lib\zipfile.py", line 1031, in extract
    return self._extract_member(member, path, pwd)
  File "C:\Users\darthoma\AppData\Local\conda\conda\envs\ceatest\lib\zipfile.py", line 1086, in _extract_member
    file(targetpath, "wb") as target:
IOError: [Errno 2] No such file or directory: 'c:\\users\\darthoma\\appdata\\local\\temp\\run cea test for pull requests\\cea-reference-case\\cea-reference-case-master\\reference-case-zug\\baseline\\outputs\\data\\optimization\\slave\\00000010.0810.5510.360010.900010.090.26001011110010111100000111_InvestmentCostDetailed.csv'

```

**Comment by shanshanhsieh** [comment]
@daren-thomas , it seems like it is failing at the step when extracting the reference case.
but i don't understand why is it searching for this file that is not used anywhere else in the test.

is it trying to compare the **current** and **standard** reference cases, and this file `00000010.0810.5510.360010.900010.090.26001011110010111100000111_InvestmentCostDetailed.csv` was accidentally added to the **standard** reference case?

**Comment by daren-thomas** [comment]
I don't understand either... wait. i'm checking right now.

**Comment by daren-thomas** [comment]
OK, @shanshanhsieh now I get this error:

```
TaskError - taskid:run_emissions_mobility:zurich/masterplan
PythonAction Error
Traceback (most recent call last):
  File "C:\Users\darthoma\Miniconda2\envs\2018.04.20\lib\site-packages\doit\action.py", line 383, in execute
    returned_value = self.py_callable(*self.args, **kwargs)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\analysis\lca\mobility.py", line 88, in main
    lca_mobility(locator=locator, config=config)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\analysis\lca\mobility.py", line 75, in lca_mobility
    mobility[fields_to_plot[3]] += mobility[occupancy] * non_renewable_energy[occupancy]
  File "C:\Users\darthoma\Miniconda2\envs\2018.04.20\lib\site-packages\pandas\core\series.py", line 601, in __getitem__
    result = self.index.get_value(self, key)
  File "C:\Users\darthoma\Miniconda2\envs\2018.04.20\lib\site-packages\pandas\core\indexes\base.py", line 2491, in get_value
    raise e1
KeyError: u'LAB' 
```

**Comment by martin-mosteiro** [comment]
@daren-thomas I think I know what's wrong. It's interesting, because it's an old error that somehow flew under the radar until now. I'm creating an issue and fixing it now.

**Comment by roglen** [comment]
@JIMENOFONSECA  Please merge once you get a chance

**Pull request merged**
