### PR TITLE
437 remove multiprocessing from gv

### PR DESCRIPTION
**Pull request by daren-thomas**
implements #437 (remove multiprocessing option from GlobalVariables)

### CODE REVIEW

**Comment by JIMENOFONSECA** [comment]
@BhargavaKrishnaSreepathi please kindly give us a hand checking this PR

**Comment by JIMENOFONSECA** [comment]
@daren it does not pass the tests. the rest is ok

**Comment by daren-thomas** [comment]
@JIMENOFONSECA after fixing some merge mistakes - the tests run now.

**Comment by daren-thomas** [comment]
@JIMENOFONSECA this actually passes `cea test` - it's just that the checks themselves are broken currently and once they work, we'll need to merge them to master first. see PR #831

**Pull request merged**
