### PR TITLE
I1100 longitude problem

### PR DESCRIPTION
**Pull request by JIMENOFONSECA**
this solves #1100 @daren-thomas would you mind taking a look at this PR? thanks!

### CODE REVIEW

**Comment by BhargavaKrishnaSreepathi** [comment]
before running need to do `pip install utm`. Even i faced the mentioned error, so used the piece of code in this PR and it solved the error

**Comment by BhargavaKrishnaSreepathi** [comment]
@JIMENOFONSECA: Similar error will arise when we run `cea\technologies\solar\photovoltaic_thermal.py` and `solar_collector.py`. I used the same changes done in `photovoltaic.py` and the error is solved. I suggest that you implement the changes in these files too in this PR

**Comment by JIMENOFONSECA** [comment]
oh,oh that seems to be a problem let me check. Probably Because I changed the digital elevation model granularity, unbelievable how sensitive this can be.

**Comment by JIMENOFONSECA** [comment]
@daren-thomas this is ready to test again

**Pull request merged**
