### PR TITLE
I1364 change final to sys

### PR DESCRIPTION
**Pull request by JIMENOFONSECA**
@gabriel-happle @shanshanhsieh @martin-mosteiro @roglen @BhargavaKrishnaSreepathi 
please kindly help me to make sure that the outputs of the demand calculation plug in in to all your scripts.

Martin: Lifecycle
Gabriel: demand
Bhargava: optimization
Lenny: Network.

the value that pointed to Qwwf was changed to Qww_sys
the value that pointed to Qhsf was changed to Qhs_sys
the value that pointed to Qcsf was changed to Qcs_sys
the value that pointed to Ef was changed to E_sys and the energy produced inside the buildings were renamed to E_ww, E_hs, E_cs

This should solve #1364

### CODE REVIEW

**Comment by roglen** [comment]
@JIMENOFONSECA  I get the following two errors in the `network layout` script:
for DH:
```
C:\Users\LennyRo\Anaconda2\envs\cea\python.exe C:/Users/LennyRo/Documents/CityEnergyAnalyst/cea/technologies/thermal_network/network_layout/main.py
Traceback (most recent call last):
  File "C:/Users/LennyRo/Documents/CityEnergyAnalyst/cea/technologies/thermal_network/network_layout/main.py", line 57, in <module>
    main(cea.config.Configuration())
  File "C:/Users/LennyRo/Documents/CityEnergyAnalyst/cea/technologies/thermal_network/network_layout/main.py", line 54, in main
    network_layout(config, locator)
  File "C:/Users/LennyRo/Documents/CityEnergyAnalyst/cea/technologies/thermal_network/network_layout/main.py", line 49, in network_layout
    total_demand_location, create_plant, config.network_layout.allow_looped_networks)
  File "C:\Users\LennyRo\Documents\CityEnergyAnalyst\cea\technologies\thermal_network\network_layout\steiner_spanning_tree.py", line 79, in calc_steiner_spanning_tree
    building_anchor = calc_coord_anchor(total_demand_location, new_mst_nodes, type_network)
  File "C:\Users\LennyRo\Documents\CityEnergyAnalyst\cea\technologies\thermal_network\network_layout\steiner_spanning_tree.py", line 130, in calc_coord_anchor
    max_value = nodes_names_demand[field].max()
  File "C:\Users\LennyRo\Anaconda2\envs\cea\lib\site-packages\geopandas\geodataframe.py", line 398, in __getitem__
    result = super(GeoDataFrame, self).__getitem__(key)
  File "C:\Users\LennyRo\Anaconda2\envs\cea\lib\site-packages\pandas\core\frame.py", line 1964, in __getitem__
    return self._getitem_column(key)
  File "C:\Users\LennyRo\Anaconda2\envs\cea\lib\site-packages\pandas\core\frame.py", line 1971, in _getitem_column
    return self._get_item_cache(key)
  File "C:\Users\LennyRo\Anaconda2\envs\cea\lib\site-packages\pandas\core\generic.py", line 1645, in _get_item_cache
    values = self._data.get(item)
  File "C:\Users\LennyRo\Anaconda2\envs\cea\lib\site-packages\pandas\core\internals.py", line 3590, in get
    loc = self.items.get_loc(item)
  File "C:\Users\LennyRo\Anaconda2\envs\cea\lib\site-packages\pandas\core\indexes\base.py", line 2444, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas\_libs\index.pyx", line 132, in pandas._libs.index.IndexEngine.get_loc (pandas\_libs\index.c:5280)
  File "pandas\_libs\index.pyx", line 154, in pandas._libs.index.IndexEngine.get_loc (pandas\_libs\index.c:5126)
  File "pandas\_libs\hashtable_class_helper.pxi", line 1210, in pandas._libs.hashtable.PyObjectHashTable.get_item (pandas\_libs\hashtable.c:20523)
  File "pandas\_libs\hashtable_class_helper.pxi", line 1218, in pandas._libs.hashtable.PyObjectHashTable.get_item (pandas\_libs\hashtable.c:20477)
KeyError: 'QHf_MWhyr'

Process finished with exit code 1
```


and for DC:
```
C:\Users\LennyRo\Anaconda2\envs\cea\python.exe C:/Users/LennyRo/Documents/CityEnergyAnalyst/cea/technologies/thermal_network/network_layout/main.py
Traceback (most recent call last):
  File "C:/Users/LennyRo/Documents/CityEnergyAnalyst/cea/technologies/thermal_network/network_layout/main.py", line 57, in <module>
    main(cea.config.Configuration())
  File "C:/Users/LennyRo/Documents/CityEnergyAnalyst/cea/technologies/thermal_network/network_layout/main.py", line 54, in main
    network_layout(config, locator)
  File "C:/Users/LennyRo/Documents/CityEnergyAnalyst/cea/technologies/thermal_network/network_layout/main.py", line 49, in network_layout
    total_demand_location, create_plant, config.network_layout.allow_looped_networks)
  File "C:\Users\LennyRo\Documents\CityEnergyAnalyst\cea\technologies\thermal_network\network_layout\steiner_spanning_tree.py", line 79, in calc_steiner_spanning_tree
    building_anchor = calc_coord_anchor(total_demand_location, new_mst_nodes, type_network)
  File "C:\Users\LennyRo\Documents\CityEnergyAnalyst\cea\technologies\thermal_network\network_layout\steiner_spanning_tree.py", line 130, in calc_coord_anchor
    max_value = nodes_names_demand[field].max()
  File "C:\Users\LennyRo\Anaconda2\envs\cea\lib\site-packages\geopandas\geodataframe.py", line 398, in __getitem__
    result = super(GeoDataFrame, self).__getitem__(key)
  File "C:\Users\LennyRo\Anaconda2\envs\cea\lib\site-packages\pandas\core\frame.py", line 1964, in __getitem__
    return self._getitem_column(key)
  File "C:\Users\LennyRo\Anaconda2\envs\cea\lib\site-packages\pandas\core\frame.py", line 1971, in _getitem_column
    return self._get_item_cache(key)
  File "C:\Users\LennyRo\Anaconda2\envs\cea\lib\site-packages\pandas\core\generic.py", line 1645, in _get_item_cache
    values = self._data.get(item)
  File "C:\Users\LennyRo\Anaconda2\envs\cea\lib\site-packages\pandas\core\internals.py", line 3590, in get
    loc = self.items.get_loc(item)
  File "C:\Users\LennyRo\Anaconda2\envs\cea\lib\site-packages\pandas\core\indexes\base.py", line 2444, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas\_libs\index.pyx", line 132, in pandas._libs.index.IndexEngine.get_loc (pandas\_libs\index.c:5280)
  File "pandas\_libs\index.pyx", line 154, in pandas._libs.index.IndexEngine.get_loc (pandas\_libs\index.c:5126)
  File "pandas\_libs\hashtable_class_helper.pxi", line 1210, in pandas._libs.hashtable.PyObjectHashTable.get_item (pandas\_libs\hashtable.c:20523)
  File "pandas\_libs\hashtable_class_helper.pxi", line 1218, in pandas._libs.hashtable.PyObjectHashTable.get_item (pandas\_libs\hashtable.c:20477)
KeyError: 'QCf_MWhyr'

Process finished with exit code 1
```

**Comment by roglen** [comment]
@JIMENOFONSECA  thank you for the fix, the network layout script works now. 

I am missing all collumns related to 'data' and 'ref' cooling in my demand files. Do these not exist anymore?

**Comment by JIMENOFONSECA** [comment]
mm I think Shanshan did that fix to that somewhere (erased those columns), but not in this PR.

**Comment by roglen** [comment]
I still have the columns in master, so i think something went wrong here. If they no longer exist I will have to make some changes to the thermal netork matrix since it currntly doesn't run. 
@shanshanhsieh @JIMENOFONSECA Please advise.

**Comment by JIMENOFONSECA** [comment]
@shanshanhsieh @roglen my bad, I will puit back Qdata and Qref but i will create then Qdata_sys and Qref_sys to keep things consistent for buildings with heatpumps.

**Pull request closed without merging**
