### PR TITLE
1239 known issues table ref

### PR DESCRIPTION
**Pull request by Jack-Hawthorne**
Hallo Jimeno,
is this something along the lines of what you were thinking?
My programming skills are not strong enough to interface with Github and pull the information from the open issues into an rst table.
I'm only really using the table for the existing issues for which I could only find one link. 
Welcome to feedback as always

### CODE REVIEW

**Comment by daren-thomas** [comment]
Can one of the admins verify this patch?

**Comment by JIMENOFONSECA** [comment]
Hi jack,

I recommend you create a page like this in the documentation of CEA to address our known issues:

https://www.tensorflow.org/install/errors

Just make a table with links to our issues in GitHub that had/ are currently reference the problem.

That is all, no need to automate it.

I hope this helps,

Best, Jimeno
On 16 Nov 2018, 21:52 +0800, Daren Thomas <notifications@github.com>, wrote:

Can one of the admins verify this patch?

**Comment by JIMENOFONSECA** [comment]
@Jack-Hawthorne @daren-thomas status?

**Comment by Jack-Hawthorne** [comment]
@JIMENOFONSECA 
it's a table with the existing known issues documentation in it. some of the issues i couldn't find a suitable github link so i just wrote "update" instead.
that's what you wanted right?

**Comment by JIMENOFONSECA** [comment]
Hi Jack, thanks for this.

Did you checked closed issues too?

If so, you can create an issue in github, describe it with a problem, describe the solution in there, get the link, and close the issue.

That will keep all in github and help other users to access this info from google too.

Best, Jimeno
On 25 Nov 2018, 20:41 +0800, Jack-Hawthorne <notifications@github.com>, wrote:

@JIMENOFONSECA<https://github.com/JIMENOFONSECA>
it's a table with the existing known issues documentation in it. some of the issues i couldn't find a suitable github link so i just wrote "update" instead.
that's what you wanted right?

**Comment by JIMENOFONSECA** [comment]
@Jack-Hawthorne

**Comment by JIMENOFONSECA** [comment]
@Jack-Hawthorne I committed an example of opening an issue to store the bug and the solution. Please also check the errors while compiling the documentation. It seems it is broken.

**Comment by Jack-Hawthorne** [comment]
@JIMENOFONSECA ok, I have added the links, not sure why the table wouldn't render properly. On the local, it works fine. 

Since cleaning up the last documentation build and hiding module paths, any modifications to the existing modules which have badly written documentation will created new build errors. After working on the input locator tracer with Daren, I will have a look at the documentation batch files and try to make an easier UI for people writing and checking documentation. 

 Let me know if there are any other problems. 
Cheers,
Jack

**Pull request merged**
