### PR TITLE
I985 activation curve

### PR DESCRIPTION
**Pull request by JIMENOFONSECA**
@BhargavaKrishnaSreepathi I solved the merging issues, Now I think I just need the naming of the new variables. would you mind listing it for me?, thanks!

Demand
- Heating
- cooling
- electricity

Supply
- Heating
- cooling
- electricity

### CODE REVIEW

**Comment by JIMENOFONSECA** [comment]
@BhargavaKrishnaSreepathi While running the optimization_main for the reference case (3 generations, 3 individuals).  I am having the next error.

image

The error might be difficult to replicate, but it would be good to go to that line of code and write what to do when this happens.

**Comment by BhargavaKrishnaSreepathi** [comment]
The above error comes, when the variable is not initiated, I just fixed it. I will enlist the variables corresponding to Heating, Cooling and Electricity

**Comment by BhargavaKrishnaSreepathi** [comment]
**Demand:**

**Heating:**

1. Buildings demand from demand files

**Electricity:**

1. Buildings Electricity demand from demand files
2. "E_HPSew_req_W" (From PPactivation_pattern, Equipment electricity requirement)
3. "E_HPLake_req_W" (From PPactivation_pattern, Equipment electricity requirement)
4. "E_GHP_req_W" (From PPactivation_pattern, Equipment electricity requirement)
5. "E_BaseBoiler_req_W" (From PPactivation_pattern, Equipment electricity requirement)
6. "E_PeakBoiler_req_W" (From PPactivation_pattern, Equipment electricity requirement)

**Cooling**

1. Buildings Cooling demand from demand files


**Supply:**

**Heating:** In PPactivation_pattern.csv

1. "Q_HPSew_W"
2. "Q_HPLake_W"
3. "Q_GHP_W"
4. "Q_CHP_W"
5. "Q_Furnace_W"
6. "Q_BaseBoiler_W"
7. "Q_PeakBoiler_W"
8. "Q_AddBoiler_W"
9. "Q_from_storage_used_W" (from _StorageOperationData.csv)

**Electricity:** In PPactivation_pattern.csv

1. "E_CHP_gen_W"
2. "E_Furnace_gen_W"
3. "E_PV_gen_W"
4. "E_PVT_gen_W"
5. Balance is from Grid

**Cooling:** In PPactivation_pattern.csv

1. "Qcold_HPLake_W"
2. Rest is covered by VCC and CT, these details are not currently saved. Will do in future commits

**Comment by JIMENOFONSECA** [comment]
@BhargavaKrishnaSreepathi 

Thanks for the list:

I am missing nonetheless:

1. solar collectors,
2. PVT, electrical and thermal
3. PV electrical
4. requirements from additional boiler
5. requirements from seasonal storage (heatpump charge and heatpump discharge).

On another note, doing the balance of the electricity consumption to get the fraction of the grid assumes that all production units attend the load directly and that there are not exports.

However, we need to know how much is exported from each unit. This affects the emissions of the site. 
Once electricity is exported the emissions factor changes.

**Comment by JIMENOFONSECA** [comment]
something that could help is to know PVT to storage, PVT to direct load etc..
the same for all resources that produce electricity
E_CHP to direct load, Q_CHP to direct load, E_CHP to grid, Q_CHP to storage

**Comment by BhargavaKrishnaSreepathi** [comment]
@JIMENOFONSECA: Fixed the seggregation of the electricity from PVT to directload and PVT to grid. Here are the variables. (in PPactivation_pattern.csv)
1. "E_PV_directload_W"
2. "E_PVT_directload_W"
3. "E_CHP_directload_W"
4. "E_Furnace_directload_W"
5.  "E_PV_to_grid_W"
6. "E_PVT_to_grid_W"
7. "E_CHP_to_grid_W"
8. "E_Furnace_to_grid_W":

Solar collectors and PVT share are present in _StorageOperationData.csv

I think with this all the variables are present

**Comment by JIMENOFONSECA** [comment]
@BhargavaKrishnaSreepathi thanks for the great update, I am incorporating this now. So what about the cooling loads of VCC and CT?

**Comment by JIMENOFONSECA** [comment]
@BhargavaKrishnaSreepathi I think most is done, just the cooling loads need to be present. We could approve this PR, in any case I created three issues that can be tackled separately. It regards the coherence of the outputs of the optimization. But I believe we should keep it separate from this first round of graphs

**Comment by JIMENOFONSECA** [comment]
@BhargavaKrishnaSreepathi let me know when I can test for the cooling loads

**Pull request merged**
