### PR TITLE
Release 2.9.0

### PR DESCRIPTION
**Pull request by daren-thomas**
This is it: The final version we will release as 2.9.0 - currently, it is set to 2.9.0a0 while I test the installer. Once that works, we can change the version number and merge, create branch, upload to PyPI.

### CODE REVIEW

**Comment by daren-thomas** [comment]
@JIMENOFONSECA can you please check the CREDITS.md file? I have done my best to update it but you might have better information.

**Comment by daren-thomas** [comment]
image

It seems the SupplySystemSimulationTool doesn't work. debugging it. @BhargavaKrishnaSreepathi do you know what this means: `KeyError: 'Invalid option in option_list: optimization:iscooling'`?

**Comment by BhargavaKrishnaSreepathi** [comment]
yep. The flag has been replaced with `district-cooling-network` in `general` section in config file

**Comment by daren-thomas** [comment]
@JIMENOFONSECA hold the merge!!!!

@BhargavaKrishnaSreepathi I'm getting the following errror now:

```
λ cea supply-system-simulation
City Energy Analyst version 2.9.0a0
Running `cea supply-system-simulation` with the following parameters:
- general:scenario = c:\reference-case-open\baseline
- general:region = CH
- general:weather = c:\users\darthoma\documents\github\cityenergyanalyst\cea\databases\weather\Zug.epw
- supply-system-simulation:centralized-vcc = 0.5
- supply-system-simulation:centralized-ach = 0.4
- supply-system-simulation:centralized-storage = 0.1
- supply-system-simulation:reduced-timesteps = True
- supply-system-simulation:decentralized-systems = Vapor Compression Chiller
- supply-system-simulation:dc-connected-buildings = []
- general:district-heating-network = False
- general:district-cooling-network = False
- thermal-network:network-type = DH
- thermal-network:network-names = []
- decentralized:ahuflag = True
- decentralized:aruflag = True
- decentralized:scuflag = True
- decentralized:ahuaruflag = True
- decentralized:ahuscuflag = True
- decentralized:aruscuflag = True
[...]
Process-heat
Traceback (most recent call last):
  File "C:\Users\darthoma\AppData\Local\conda\conda\envs\cea\Scripts\cea-script.py", line 11, in <module>
    load_entry_point('cityenergyanalyst', 'console_scripts', 'cea')()
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\interfaces\cli\cli.py", line 65, in main
    script_module.main(config)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\supply\supply_system_simulation.py", line 658, in main
    solarFeat, network_features, gv, config, prices, lca)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\supply\supply_system_simulation.py", line 73, in supply_calculation
    DHN_barcode, DCN_barcode, DHN_configuration, DCN_configuration = sFn.individual_to_barcode(individual,
NameError: global name 'sFn' is not defined
```

**Comment by BhargavaKrishnaSreepathi** [comment]
Need to rename `sFn` to `supportFn`

**Comment by daren-thomas** [comment]
It seems the signature for `addCosts` has changed...

```
Traceback (most recent call last):
  File "C:\Users\darthoma\AppData\Local\conda\conda\envs\cea\Scripts\cea-script.py", line 11, in <module>
    load_entry_point('cityenergyanalyst', 'console_scripts', 'cea')()
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\interfaces\cli\cli.py", line 65, in main
    script_module.main(config)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\supply\supply_system_simulation.py", line 658, in main
    solarFeat, network_features, gv, config, prices, lca)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\supply\supply_system_simulation.py", line 200, in supply_calculation
    config, prices, lca)
TypeError: addCosts() takes exactly 11 arguments (13 given)
```

**Comment by JIMENOFONSECA** [comment]
@daren-thomas alright, I just added some info to the credits. Is there anything else? or should I get to merge?

**Comment by BhargavaKrishnaSreepathi** [comment]
@daren-thomas: it should work now. Just a caveat, `supply_system_simulation.py` is prepared exclusively for the cooling scenario. It does give the following message when it is run for the heating scenario, `This function only works for cooling case at the moment.`

**Pull request merged**
