### PR TITLE
I998 update shp for zug

### PR DESCRIPTION
**Pull request by shanshanhsieh**
This PR resolves issue #998 
There are two parts of changes:
1. In `reference-case-zug`, the `DC` and `DH` are updated with new .shp files. These files are generated from the `network_layout` scripts in cea.
2. In the cea, the scripts within the `network_layout` folder are updated to read `cea.config`

To test:
1. Update cea-reference-case from master, and run `thermal_network_matrix` for both `DC` and `DH` in `reference-case-zug` 
2. In cea, run `substations_location.py`, `connectivity_potential.py`, and `minimum_spanning_tree.py` (follow the Readme to check outputs)

### CODE REVIEW

**Comment by JIMENOFONSECA** [comment]
@shanshanhsieh so it runs until minimum_spanning_tree, then I get

**Comment by JIMENOFONSECA** [comment]
It runs until minimum spanning tree, then I get this:

image

**Comment by JIMENOFONSECA** [comment]
let me I check

**Comment by JIMENOFONSECA** [comment]
@shanshanhsieh I am gonan take a look at it

**Comment by shanshanhsieh** [comment]
@JIMENOFONSECA great, thanks!

**Pull request merged**
