### PR TITLE
fixes #1394 - Restrict `config` to the inputs for the tool when running from cli/arcgis interfaces

### LINKED ISSUE #1394: Restrict `config` to the inputs for the tool when running from cli/arcgis interfaces
When running the CEA from the `cea.interfaces.cli.cli` interface (and by extension also from arcgis and the dashboard), the config object should be restricted to the options specified in the `cli.config` file.

Why? This makes sure that when the tool is tested, any parameters that are used in the scripts that are not defined in the interface will create an error. That way, we can avoid running scripts with "hidden" parameters and creating confusing results.

### PR DESCRIPTION
**Pull request by daren-thomas**
This PR introduces a `cea.config.Configuration.restrict_to` method that get's called when running `cea.interfaces.cli.cli` (as is done from the `cea` command, the ArcGIS interface and the dashboard) and restricts the `config` object to only the parameters defined in the `cli.config` file for a specific script.

Why? Because, this will help uncover scripts that use parameters without defining them in the `cli.config` file. This is useful because hiding parameters read from the config file is a source of errors.

Of course, this means we should test run each script from the ArcGIS interface again.

### CODE REVIEW

**Comment by gabriel-happle** [comment]
@daren-thomas in this case reviewing means to "run each script from the ArcGIS interface again", am I right?

**Comment by daren-thomas** [comment]
@gabriel-happle yes, you're right - but we're doing that anyways for the executive course, right? continuously... because any change we push (and we seem to be pushing a lot of changes) _could_ in theory break the interface and we don't want that...

**Comment by JIMENOFONSECA** [comment]
@daren-thomas it is not passing the tests

**Comment by gabriel-happle** [comment]
Checking it today

- [ ]  Data helper
- [ ]  
- [ ]  
- [ ]  
- [ ]  
- [ ]  
- [ ]  
- [ ]  
- [ ]  
- [ ]  
- [ ]  
- [ ]  
- [ ]

**Comment by gabriel-happle** [comment]
@daren-thomas solar collector script fails.
Is that what you were looking for with this change?

```Executing: SolarCollectorPanelsTool C:\cea-case-studies-local-05-06-2018\reference-case-WTP-reduced\WTP_RES_h Singapore-2016 c:\Users\Gabriel\documents\GitHub\ceaforarcgis\cea\databases\weather\Singapore-2016.epw FP true false 800000 4 75
Start Time: Thu Jun 07 12:12:34 2018
Running script SolarCollectorPanelsTool...
Executing: C:\Users\Gabriel\Anaconda2\envs\cea\python.exe -u -m cea.interfaces.cli.cli solar-collector --panel-on-roof true --scenario C:\cea-case-studies-local-05-06-2018\reference-case-WTP-reduced\WTP_RES_h --solar-window-solstice 4 --type-scpanel FP --annual-radiation-threshold 8e+05 --weather c:\users\gabriel\documents\github\ceaforarcgis\cea\databases\weather\Singapore-2016.epw --panel-on-wall false --t-in-sc 75
Running `cea solar-collector` with the following parameters:
- general:scenario = C:\cea-case-studies-local-05-06-2018\reference-case-WTP-reduced\WTP_RES_h
- general:weather = c:\users\gabriel\documents\github\ceaforarcgis\cea\databases\weather\Singapore-2016.epw
- solar:type-scpanel = FP
- solar:panel-on-roof = True
- solar:panel-on-wall = False
- solar:annual-radiation-threshold = 800000.0
- solar:solar-window-solstice = 4
- solar:t-in-sc = 75.0
Running solar-collector with scenario = C:\cea-case-studies-local-05-06-2018\reference-case-WTP-reduced\WTP_RES_h
Running solar-collector with annual-radiation-threshold = 800000.0
Running solar-collector with panel-on-roof = True
Running solar-collector with panel-on-wall = False
Running solar-collector with solar-window-solstice = 4
Running solar-collector with t-in-sc = 75.0
Running solar-collector with type-scpanel = FP
Traceback (most recent call last):
  File "C:\Users\Gabriel\Anaconda2\envs\cea\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Users\Gabriel\Anaconda2\envs\cea\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "c:\users\gabriel\documents\github\ceaforarcgis\cea\interfaces\cli\cli.py", line 109, in <module>
    main(cea.config.Configuration())
  File "c:\users\gabriel\documents\github\ceaforarcgis\cea\interfaces\cli\cli.py", line 45, in main
    script_module.main(config)
  File "c:\users\gabriel\documents\github\ceaforarcgis\cea\technologies\solar\solar_collector.py", line 863, in main
    panel_properties = calc_properties_SC_db(locator.get_supply_systems(config.region), config)
  File "c:\users\gabriel\documents\github\ceaforarcgis\cea\config.py", line 48, in __getattr__
    return getattr(self.sections['general'], cid)
  File "c:\users\gabriel\documents\github\ceaforarcgis\cea\config.py", line 207, in __getattr__
    "Parameter not configured to work with this script: {%s}" % self.parameters[cid].fqname)
AttributeError: Parameter not configured to work with this script: {general:region}


Traceback (most recent call last):
  File "C:\Users\Gabriel\AppData\Roaming\ESRI\Desktop10.5\ArcToolbox\My Toolboxes\cea\interfaces\arcgis\arcgishelper.py", line 95, in execute
    run_cli(self.cea_tool, **kwargs)
  File "C:\Users\Gabriel\AppData\Roaming\ESRI\Desktop10.5\ArcToolbox\My Toolboxes\cea\interfaces\arcgis\arcgishelper.py", line 184, in run_cli
    raise Exception('Tool did not run successfully')
Exception: Tool did not run successfully

Failed to execute (SolarCollectorPanelsTool).
Failed at Thu Jun 07 12:12:35 2018 (Elapsed Time: 0.93 seconds)```

**Comment by gabriel-happle** [comment]
same for photovoltaic

```Running script PhotovoltaicPanelsTool...
Executing: C:\Users\Gabriel\Anaconda2\envs\cea\python.exe -u -m cea.interfaces.cli.cli photovoltaic --panel-on-roof true --scenario C:\cea-case-studies-local-05-06-2018\reference-case-WTP-reduced\WTP_RES_h --type-pvpanel PV1 --solar-window-solstice 4 --panel-on-wall false --annual-radiation-threshold 8e+05 --weather c:\users\gabriel\documents\github\ceaforarcgis\cea\databases\weather\Singapore-2016.epw
Running `cea photovoltaic` with the following parameters:

...

Traceback (most recent call last):
  File "C:\Users\Gabriel\Anaconda2\envs\cea\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Users\Gabriel\Anaconda2\envs\cea\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "c:\users\gabriel\documents\github\ceaforarcgis\cea\interfaces\cli\cli.py", line 109, in <module>
    main(cea.config.Configuration())
  File "c:\users\gabriel\documents\github\ceaforarcgis\cea\interfaces\cli\cli.py", line 45, in main
    script_module.main(config)
  File "c:\users\gabriel\documents\github\ceaforarcgis\cea\technologies\solar\photovoltaic.py", line 769, in main
    latitude=latitude, longitude=longitude, weather_path=config.weather, building_name=building)
  File "c:\users\gabriel\documents\github\ceaforarcgis\cea\technologies\solar\photovoltaic.py", line 61, in calc_PV
    date_local = solar_equations.cal_date_local_from_weather_file(weather_data, config)
  File "c:\users\gabriel\documents\github\ceaforarcgis\cea\utilities\solar_equations.py", line 92, in cal_date_local_from_weather_file
    if config.region == 'SIN':
  File "c:\users\gabriel\documents\github\ceaforarcgis\cea\config.py", line 48, in __getattr__
    return getattr(self.sections['general'], cid)
  File "c:\users\gabriel\documents\github\ceaforarcgis\cea\config.py", line 207, in __getattr__
    "Parameter not configured to work with this script: {%s}" % self.parameters[cid].fqname)
AttributeError: Parameter not configured to work with this script: {general:region}


Traceback (most recent call last):
  File "C:\Users\Gabriel\AppData\Roaming\ESRI\Desktop10.5\ArcToolbox\My Toolboxes\cea\interfaces\arcgis\arcgishelper.py", line 95, in execute
    run_cli(self.cea_tool, **kwargs)
  File "C:\Users\Gabriel\AppData\Roaming\ESRI\Desktop10.5\ArcToolbox\My Toolboxes\cea\interfaces\arcgis\arcgishelper.py", line 184, in run_cli
    raise Exception('Tool did not run successfully')
Exception: Tool did not run successfully

Failed to execute (PhotovoltaicPanelsTool).
Failed at Thu Jun 07 12:15:15 2018 (Elapsed Time: 1.01 seconds)
```

**Comment by daren-thomas** [comment]
@gabriel-happle _exactly_!

**Comment by daren-thomas** [comment]
@gabriel-happle can you test these again please?

**Comment by gabriel-happle** [comment]
@daren-thomas tomorrow morning.

**Comment by JIMENOFONSECA** [comment]
@daren-thomas closing this, please reopen when ready to test again

**Pull request closed without merging**
