### PR TITLE
Change naming of weather files

### PR DESCRIPTION
**Pull request by JIMENOFONSECA**

### CODE REVIEW

**Comment by daren-thomas** [comment]
First quick test: `locator.get_default_weather()` creates a `RuntimeError: maximum recursion depth exceeded in cmp`.

This PR hasn't been tested properly yet. Please don't merge.

**Comment by daren-thomas** [comment]
Where is the rationale for this change? For documentation purposes, connecting this to an issue that explains _why_ we're changing the naming would be a good idea.

**Comment by daren-thomas** [comment]
The build failed because of an exception:

> Exception: Temperature in RC-Model of building B05 out of bounds! First occured at timestep = 4195. The results were Tint = 50.1732998021, theta_c = 49.7425616687, theta_m = 49.3880330959, Check building geometry and internal loads! Building might be too small in size or architecture parameter Hs = 0.95 might be too small for this geometry. Current bounds of range for RC-model temperatures are between -30.0 and 50.0.

**Comment by JIMENOFONSECA** [comment]
@daren-thomas I erased the weather files that we normally do not use. I keep those that we created on our own and some of meteonorm

**Comment by JIMENOFONSECA** [comment]
@daren-thomas any update?

**Pull request merged**
