### PR TITLE
I1018 simple indoor humidity

### PR DESCRIPTION
**Pull request by gabriel-happle**
This pull request is not ready to merge.
It is here to facilitate the discussion with @shanshanhsieh about the further procedure.

It addresses issues in epic #811

### CODE REVIEW

**Comment by gabriel-happle** [comment]
@JIMENOFONSECA and @shanshanhsieh and @BhargavaKrishnaSreepathi 

Check out these graphs (unfortunately I can't upload html here directly).
They are a hundred hours of cooling system loads, moisture balance, etc. for Swiss climate.
All loads are split up between up to three cooling system components. They are: AHU (Air handling unit, treating mechanical ventilation air), ARU (Air recirculation unit, treating indoor air) and SCU (sensible cooling unit).

B01: T4 (3for2 = AHU + ARU + SCU)
B02: T1 (ceiling cooling = SCU)
B03: T2 (mini-split = ARU)
B04: T3 (central AC = AHU = ARU)

https://drive.google.com/open?id=19h0jHHquSYqfqZwH1rffe2wNKeMUQ4Ym

**Comment by gabriel-happle** [comment]
New Branch:

read input files
done
data for test_calc_thermal_loads:

values = [154769.87699999998, 2659.0640000000003, 0.0, 158819.73500000002, 19683.957, 261795.55000000005, 0.0, 0.0, 17536.531000000003, 19683.957, 191603.432, 218997.65899999999, 38686.476, 42797.879, 2907.0, 76797.71399999999, 80206.56000000003, 2052.0, 88714.55, 525600.0] 
[154769.87699999998, 2659.0640000000003, 0.0, 158819.73500000002, 19683.957, 261795.55000000005, 0.0, 0.0, 17536.531000000003, 19683.957, 191603.432, 218997.65899999999, 38686.476, 42797.879, 2907.0, 76797.71399999999, 80206.56000000003, 2052.0, 88714.55, 525600.0]
data for test_calc_thermal_loads_other_buildings:
'B01': (19683.95700, 261795.55000),
'B03': (21519.86000, 209104.41100),
'B02': (10093.28300, 485997.04700),
'B05': (21519.86500, 209104.44100),
'B04': (21519.86600, 209104.44700),
'B07': (21519.86700, 209104.45600),
'B06': (0.00000, 0.00000),
'B09': (21519.86500, 209104.43300),
'B08': (21519.86500, 209104.44500),


Master:

read input files
done
data for test_calc_thermal_loads:
Index([u'B01', u'B02', u'B03', u'B04', u'B05', u'B07', u'B08', u'B09', u'B06'], dtype='object', name=u'Name')

values = [154769.87699999998, 4805.076999999999, 0.0, 160653.77000000002, 15240.904, 261794.653, 0.0, 0.0, 13104.153999999999, 15240.904, 191603.436, 218996.755, 38686.476, 42797.875, 2890.0, 76797.629, 80206.56000000003, 2040.0, 88714.439, 525600.0] 
[154769.87699999998, 4805.076999999999, 0.0, 160653.77000000002, 15240.904, 261794.653, 0.0, 0.0, 13104.153999999999, 15240.904, 191603.436, 218996.755, 38686.476, 42797.875, 2890.0, 76797.629, 80206.56000000003, 2040.0, 88714.439, 525600.0]
data for test_calc_thermal_loads_other_buildings:
'B01': (15240.90400, 261794.65300),
'B03': (17020.17400, 209103.57200),
'B02': (6490.59700, 485995.68500),
'B05': (17020.17600, 209103.59400),
'B04': (17020.17600, 209103.60800),
'B07': (17020.17700, 209103.61200),
'B06': (0.00000, 0.00000),
'B09': (17020.17500, 209103.59000),
'B08': (17020.17600, 209103.60100),

**Comment by gabriel-happle** [comment]
Dodo fails because of some unrelated stuff:

```C:\Users\Gabriel\Anaconda2\envs\cea\python.exe C:/Users/Gabriel/Documents/GitHub/CEAforArcGIS/cea/tests/dodo.py
.  run_unit_tests
C:\Users\Gabriel\Documents\GitHub\CEAforArcGIS\cea\demand\preprocessing\data_helper.py:162: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  names_df[field] = 0
...........................
.  download_reference_cases
----------------------------------------------------------------------
Ran 27 tests in 40.226s

OK
.  run_data_helper:open
.  download_radiation:open
.  run_demand:open@Zug
.  run_embodied_energy:open
.  run_emissions_operation:open
.  run_emissions_mobility:open
.  run_scenario_plots:open
.  run_calibration
WARNING (theano.configdefaults): g++ not available, if using conda: `conda install m2w64-toolchain`
C:\Users\Gabriel\Anaconda2\envs\cea\lib\site-packages\theano\configdefaults.py:560: UserWarning: DeprecationWarning: there is no c++ compiler.This is deprecated and with Theano 0.11 a c++ compiler will be mandatory
  warnings.warn("DeprecationWarning: there is no c++ compiler."
WARNING (theano.configdefaults): g++ not detected ! Theano will be unable to execute optimized C-implementations (for both CPU and GPU) and will default to Python implementations. Performance will be severely degraded. To remove this warning, set Theano flags cxx to an empty string.
WARNING (theano.configdefaults): install mkl with `conda install mkl-service`: No module named mkl
WARNING (theano.tensor.blas): Using NumPy C-API based implementation for BLAS functions.
########################################
TaskError - taskid:run_calibration
PythonAction Error
Traceback (most recent call last):
  File "C:\Users\Gabriel\Anaconda2\envs\cea\lib\site-packages\doit\action.py", line 383, in execute
    returned_value = self.py_callable(*self.args, **kwargs)
  File "C:/Users/Gabriel/Documents/GitHub/CEAforArcGIS/cea/tests/dodo.py", line 301, in run_calibration
    import cea.demand.calibration.bayesian_calibrator.calibration_main as calibration_main
  File "C:\Users\Gabriel\Documents\GitHub\CEAforArcGIS\cea\demand\calibration\bayesian_calibrator\calibration_main.py", line 16, in <module>
    import seaborn as sns
ImportError: No module named seaborn


WARNING (theano.configdefaults): g++ not available, if using conda: `conda install m2w64-toolchain`
C:\Users\Gabriel\Anaconda2\envs\cea\lib\site-packages\theano\configdefaults.py:560: UserWarning: DeprecationWarning: there is no c++ compiler.This is deprecated and with Theano 0.11 a c++ compiler will be mandatory
  warnings.warn("DeprecationWarning: there is no c++ compiler."
WARNING (theano.configdefaults): g++ not detected ! Theano will be unable to execute optimized C-implementations (for both CPU and GPU) and will default to Python implementations. Performance will be severely degraded. To remove this warning, set Theano flags cxx to an empty string.
WARNING (theano.configdefaults): install mkl with `conda install mkl-service`: No module named mkl
WARNING (theano.tensor.blas): Using NumPy C-API based implementation for BLAS functions.


Process finished with exit code 2
```

**Comment by gabriel-happle** [comment]
@daren-thomas can you tell me why the checks fail? Thanks.

**Comment by gabriel-happle** [comment]
@daren-thomas After doing:
- `conda install m2w64-toolchain`
- `conda install mkl-service`
- `conda install seaborn`

This is my error in `dodo`. It is not related to anything I changed. How does this happen?

```C:\Users\Gabriel\Anaconda2\envs\cea\python.exe C:/Users/Gabriel/Documents/GitHub/CEAforArcGIS/cea/tests/dodo.py
.  run_unit_tests
C:\Users\Gabriel\Documents\GitHub\CEAforArcGIS\cea\demand\preprocessing\data_helper.py:162: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  names_df[field] = 0
...........................
.  download_reference_cases
----------------------------------------------------------------------
Ran 27 tests in 44.135s

OK
.  run_data_helper:open
.  download_radiation:open
.  run_demand:open@Zug
.  run_embodied_energy:open
.  run_emissions_operation:open
.  run_emissions_mobility:open
.  run_scenario_plots:open
.  run_calibration
########################################
TaskError - taskid:run_calibration
PythonAction Error
Traceback (most recent call last):
  File "C:\Users\Gabriel\Anaconda2\envs\cea\lib\site-packages\doit\action.py", line 383, in execute
    returned_value = self.py_callable(*self.args, **kwargs)
  File "C:/Users/Gabriel/Documents/GitHub/CEAforArcGIS/cea/tests/dodo.py", line 301, in run_calibration
    import cea.demand.calibration.bayesian_calibrator.calibration_main as calibration_main
  File "C:\Users\Gabriel\Documents\GitHub\CEAforArcGIS\cea\demand\calibration\bayesian_calibrator\calibration_main.py", line 15, in <module>
    import pymc3 as pm
  File "C:\Users\Gabriel\Anaconda2\envs\cea\lib\site-packages\pymc3\__init__.py", line 5, in <module>
    from .distributions import *
  File "C:\Users\Gabriel\Anaconda2\envs\cea\lib\site-packages\pymc3\distributions\__init__.py", line 1, in <module>
    from . import timeseries
  File "C:\Users\Gabriel\Anaconda2\envs\cea\lib\site-packages\pymc3\distributions\timeseries.py", line 1, in <module>
    import theano.tensor as tt
  File "C:\Users\Gabriel\Anaconda2\envs\cea\lib\site-packages\theano\__init__.py", line 110, in <module>
    from theano.compile import (
  File "C:\Users\Gabriel\Anaconda2\envs\cea\lib\site-packages\theano\compile\__init__.py", line 12, in <module>
    from theano.compile.mode import *
  File "C:\Users\Gabriel\Anaconda2\envs\cea\lib\site-packages\theano\compile\mode.py", line 11, in <module>
    import theano.gof.vm
  File "C:\Users\Gabriel\Anaconda2\envs\cea\lib\site-packages\theano\gof\vm.py", line 673, in <module>
    from . import lazylinker_c
  File "C:\Users\Gabriel\Anaconda2\envs\cea\lib\site-packages\theano\gof\lazylinker_c.py", line 127, in <module>
    preargs=args)
  File "C:\Users\Gabriel\Anaconda2\envs\cea\lib\site-packages\theano\gof\cmodule.py", line 2359, in compile_str
    (status, compile_stderr.replace('\n', '. ')))
. 


You can find the C code in this temporary file: c:\users\gabriel\appdata\local\temp\theano_compilation_error_houekb



Process finished with exit code 2
```

**Comment by daren-thomas** [comment]
@gabriel-happle this has to do with your conda environment. You could try a `conda env update` in the CityEnergyAnalyst folder. OR, if that doesn't work, do a `conda env remove --name cea`, Answer the "remove packages [y]/n" question, then go grab a coffee. Then re-create your environment (`conda env create`).

When done, you should get this error instead (after updating the test data with `python -m cea.tests.create_unittest_data`):
```
TaskError - taskid:run_calibration
PythonAction Error
Traceback (most recent call last):
  File "C:\Users\darthoma\AppData\Local\conda\conda\envs\cea\lib\site-packages\doit\action.py", line 383, in execute
    returned_value = self.py_callable(*self.args, **kwargs)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\tests\dodo.py", line 314, in run_calibration
    calibration_sampling.sampling_main(locator=locator, config=config)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\demand\calibration\bayesian_calibrator\calibration_sampling.py", line 79, in sampling_main
    simulation = simulate_demand_sample(locator, building_name, building_load, config)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\demand\calibration\bayesian_calibrator\calibration_sampling.py", line 116, in simulate_demand_sample
    _ , time_series = demand_main.demand_calculation(locator, gv, config)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\demand\demand_main.py", line 109, in demand_calculation
    format_output)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\demand\demand_main.py", line 153, in calc_demand_singleprocessing
    format_output)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\demand\thermal_loads.py", line 119, in calc_thermal_loads
    hourly_procedure_heating_cooling_system_load.calc_heating_cooling_loads(bpr, tsd, t)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\demand\hourly_procedure_heating_cooling_system_load.py", line 97, in calc_heating_cooling_loads
    rc_model_temperatures = calc_cool_loads_central_ac(bpr, t, tsd)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\demand\hourly_procedure_heating_cooling_system_load.py", line 460, in calc_cool_loads_central_ac
    g_dhu_demand_aru = latent_loads.calc_dehumidification_moisture_load(bpr, tsd, t)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\demand\latent_loads.py", line 95, in calc_dehumidification_moisture_load
    x_set_max = calc_max_moisture_set_point(bpr, tsd, t)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\demand\latent_loads.py", line 162, in calc_max_moisture_set_point
    phi_int_set_dhu = bpr.comfort['rhum_max_pc']
KeyError: 'rhum_max_pc'
```

**Comment by gabriel-happle** [comment]
@daren-thomas that's a cool command.
So what step is the jenkins failing at?
I added columns to excel databases. Is the jenkins running the datahelper before running the demand? If not, for sure it will fail.

**Comment by gabriel-happle** [comment]
@daren-thomas I take that back! that command messed up everything :(

**Comment by gabriel-happle** [comment]
@daren-thomas I have the same error now. After installing the cea environment new.
I'm sorry, I don't understand the `task_run_calibration` that fails. 
It seems we have to change the inputs into that functions, because the `demand` test runs.
Can you please make the `task_run_calibration` use the same files as the demand. I.e. the same building data?

I added columns to excel databases `construction_properties.xlsx` and `emission_systems.xls`. This additional data should be added to `bpr` when the `data_helper` is executed. But somehow this additional data can not be accessed in the calibration test.

**Comment by daren-thomas** [comment]
@gabriel-happle I have updated the branch to include a version of `cea/examples/reference-case-open.zip` the has gone through the new `cea data-helper` and the test now runs through. Thank you for helping me debug this problem! Would you mind mentioning the new fields in the **critical updates** slack channel? I think that's kind of important.

**Comment by gabriel-happle** [comment]
@shanshanhsieh this is passing tests now

**Comment by gabriel-happle** [comment]
@shanshanhsieh testing now with `region = SIN`
there seem to be some mess ups.

**Comment by gabriel-happle** [comment]
Some test results for location Singapore:
B01 = T01
B02 = T02
B03 = T03
B04 = T04 

https://drive.google.com/open?id=1p0EzWQKVF-xd5ritw6kWq5ya-5FFjvYq

**Comment by gabriel-happle** [comment]
Info:
When running the demand with buildings that do not have heating or cooling demand (e.g., Singapore case), there will be warnings from the temporary fix of re-aggregating outputs:
This is intended behavior! Not nice, but exactly what is supposed to happen.

```
Running demand calculation for scenario C:\reference-case-open\baseline
Running demand calculation with weather file C:\Users\Gabriel\Documents\GitHub\CEAforArcGIS\cea\databases\weather\Singapore.epw
Running demand calculation for region SIN
Running demand calculation with dynamic infiltration=False
Running demand calculation with multiprocessing=False
Running demand calculation with daysim radiation=True
read input files
done
Running demand calculation for the next buildings=['B01', 'B02', 'B03', 'B04']
C:\Users\Gabriel\Documents\GitHub\CEAforArcGIS\cea\demand\thermal_loads.py:158: RuntimeWarning: All-NaN axis encountered
  tsd['Tcsf_sup'] = np.nanmin([tsd['Tcsf_sup_ahu'],tsd['Tcsf_sup_aru'],tsd['Tcsf_sup_scu']], axis=0)
C:\Users\Gabriel\Documents\GitHub\CEAforArcGIS\cea\demand\thermal_loads.py:159: RuntimeWarning: All-NaN axis encountered
  tsd['Tcsf_re'] = np.nanmax([tsd['Tcsf_re_ahu'], tsd['Tcsf_re_aru'], tsd['Tcsf_re_scu']], axis=0)
C:\Users\Gabriel\Documents\GitHub\CEAforArcGIS\cea\demand\thermal_loads.py:160: RuntimeWarning: All-NaN axis encountered
  tsd['Thsf_sup'] = np.nanmax([tsd['Thsf_sup_ahu'], tsd['Thsf_sup_aru'], tsd['Thsf_sup_shu']], axis=0)
C:\Users\Gabriel\Documents\GitHub\CEAforArcGIS\cea\demand\thermal_loads.py:161: RuntimeWarning: All-NaN axis encountered
  tsd['Thsf_re'] = np.nanmin([tsd['Thsf_re_ahu'], tsd['Thsf_re_aru'], tsd['Thsf_re_shu']], axis=0)
Building No. 1 completed out of 4: B01
Building No. 2 completed out of 4: B02
Building No. 3 completed out of 4: B03
Building No. 4 completed out of 4: B04

Process finished with exit code 0
```

**Comment by shanshanhsieh** [comment]
@JIMENOFONSECA this branch is ready to be merged!

**Comment by JIMENOFONSECA** [comment]
@gabriel-happle while running demand in single core. I get the next warning worthwhile to check.
image

**Comment by gabriel-happle** [comment]
@JIMENOFONSECA the globalvars bug is fixed!
I think it's quite weird that I never got this error/warning when running the `dodo`.
Does the `dodo` not run multiprocessing @daren-thomas ?
The other warning is intended behavior. It is part of the temporary re-aggregation of the output variables. See also my comment above,

**Pull request merged**
