### PR TITLE
2192 single plot view

### PR DESCRIPTION
**Pull request by daren-thomas**
This PR implements #2192 - users can click on a plot title in the new (react) dashboard and a new tab opens up with an uncluttered view of the plot.

To test:
- open the dashboard for a project/scenario
- click on the title of a plot
- you should see a new tab with the plot
- try different dashboard styles (row / grid layout)

### CODE REVIEW

**Comment by daren-thomas** [comment]
@JIMENOFONSECA assigning to you for now as you opened the issue. Feel free to delegate.

**Comment by reyery** [comment]
It does not work with the supply system map plot, still trying to figure out why. Could be because of how the scripts are ordered/executed when mounting it in the body?

**Comment by daren-thomas** [comment]
@reyery: I figured it out... the map _is_ being plotted. it's just that the container div has no fixed height... to test, open the single plot version of the supply system map plot. use the inspector to navigate to the div with id={hash}. set height="500px" (just an example) - voilà! there's your map.

Now... I'd like some help with you: Could you figure out what we should be using for the "height" attribute? how did you specify it for the react stuff? care to lend a hand? thank you!

**Comment by reyery** [comment]
yeah. I have noticed that too, regarding the height of the div. But I still get something like this when I try to change it to 3D. Still not sure why. I noticed that it will try to download the deckgl script (dist.min.js) even though it's already downloaded. Something to do will jquery `get` caching set to `off` since there are some kind of timestamp behind the js file

image
image

Anyway, regarding the height I am thinking of making it 50% of view port with a min-height of 450, that would mean we would need to resize the plots accordingly with a window resize event listener, will push a commit for this. For React, the div container has a height style property probably that's why it worked.

**Comment by daren-thomas** [comment]
your update works for me (I was nearly about to push something similar). I can't do 3D plots toggling either. BUT: i think we should not bother with this right now, but instead merge and create an issue, since we'll be using the react containers anyway soon - it would just be a waste of resources.

@reyery what do you think?

**Comment by reyery** [comment]
Created issue for supply system map. #2312

**Pull request merged**
