### PR TITLE
I1024 absorption chiller

### LINKED ISSUE #1024: Model of absorption chiller

### PR DESCRIPTION
**Pull request by shanshanhsieh**
This PR resolves #1024 and #1154. Major changes include two new scripts:
1. Model of absorption chiller `technologies/chiller_absorption.py`, a database of absorption chiller in the `supply_systems.xls`. 
2. Optimization of supply systems for disconnected buildings in cooling dominated region (SIN) `optimization/preprocessing/decentralized_buildings_cooling.py`. Please read the documentation of `disconnected_cooling_main` for more details on the supply systems.

To test:
1. pip install sympy
2. extract `reference-case-open` in the example, run `demand_main.py`.
3. download folder `solar` and paste it at `baseline/outputs/data/potentials` , skip 3a&3b
click here to download: https://drive.google.com/drive/folders/1a7DRJUYFJYF_1zxv87SnBC7ONTGIzOGC?usp=sharing 
(3a.) run `solar_collector.py` with `type-scpanel` = 'SC1' and `t-in-sc`=75. this calculates the potential of flat plate collectors. (~10 min)
(3b.) run `solar_collector.py` with `type-scpanel` = 'SC2' and `t-in-sc`=150. this calculated the potential of evacuated tube collectors. (~90min)
4. run `disconnected_buildings_cooling.py` 
5. the results of optimization are stored in `...\baseline\outputs\data\optimization\disconnected`

### CODE REVIEW

**Comment by JIMENOFONSECA** [comment]
@shanshanhsieh could you check the conflicts?

**Comment by shanshanhsieh** [comment]
@JIMENOFONSECA i ran `cea test` from my pc, everything went through until the *unit_tests*

here's the error:
image

**Comment by shanshanhsieh** [comment]
when running `cea test` in master, the same error occurs. shall i make an issue on updating the test data, @JIMENOFONSECA ?

**Comment by shanshanhsieh** [comment]
Hi @daren-thomas , is it possible that you can review this PR since @JIMENOFONSECA is away? we will need this in master so that @BhargavaKrishnaSreepathi and I can work on new additions in optimization.
Thanks!

**Pull request merged**
