### PR TITLE
1451/1368 fix databases copy

### PR DESCRIPTION
**Pull request by daren-thomas**
A proposal to solve the issue #1451 and the duplicate  #1368

All region-specific files are copied to the scenario if they do not exist yet - but are never overwritten once copied so the user can make changes as he pleases.

The region-specific files in the scenario are saved in databases/<region>/<folder>/<filename>, so when switching regions, the files get copied again to the new region subfolder as outlined in #1451.

The special region "custom" can also be used, e.g. for regions that are not specified in the CEA. When accessing a database from that region, an error is generated if the file is not present in the scenario.

### CODE REVIEW

**Comment by JIMENOFONSECA** [comment]
@daren-thomas so I run the datahelper with CH and then SIN in the reference case. In both cases it copied only the archetypes database to the case study.

**Comment by daren-thomas** [comment]
databases are copied as used. otherwise, we can "touch" them all in the archetypes... do we have the complete lists....

**Comment by JIMENOFONSECA** [comment]
I other to initialise all inputs, I will suggest we copy all at once (whenever we run the first script of CEA). So during the exercise we can show where all databases are and what they have.

On 7 Jun 2018, 3:51 PM +0800, Daren Thomas <notifications@github.com>, wrote:

databases are copied as used. otherwise, we can "touch" them all in the archetypes... do we have the complete lists....

**Comment by daren-thomas** [comment]
@JIMENOFONSECA i'm not sure checking this on _all_ the CEA scripts is a good idea. But I _do_ see the teaching advantage of having all the databases copied.

hm... maybe the easiest way is to check for  the databases whenever an InputLocator is created for a scenario... or... what if we added it to the create-new-scenario script?

which would you prefer:

- check whenever _any_ script is run
- check whenever an `InputLocator` is created for a scenario
- check on the `create-new-scenario` script (and possibly also the `data-helper` script)

?

**Comment by JIMENOFONSECA** [comment]
I think this: "Check whenever an InputLocator is created for a scenario"

In this way, even before we run the tool we will have the databases which is a good thing.

ANOTHER alternative and maybe a bit more transparent is that we create a tool called “Create default databases” which will create these databases in an scenario. This will also allow that the user re-creates these databases if he messes it al up.

what do you think?

On 7 Jun 2018, 4:41 PM +0800, wrote:

• check whenever an InputLocator is created for a scenario

**Comment by daren-thomas** [comment]
I like the `Create default databases` idea best so far. 

The code already ensures that the databases are copied when required, so nothing can really go wrong if the step is not run. Making the step _explicit_ is good for user understanding, though. And having the tool actually go and overwrite the databases if something gets messed up is an awesome idea!

**Comment by JIMENOFONSECA** [comment]
cool. So what about this?:

1. we make in this PR the step of copying all databases once we call input locator.

2. we create an issue to create the tool in the future.

On 7 Jun 2018, 6:17 PM +0800, Daren Thomas <notifications@github.com>, wrote:

I like the Create default databases idea best so far.

The code already ensures that the databases are copied when required, so nothing can really go wrong if the step is not run. Making the step explicit is good for user understanding, though. And having the tool actually go and overwrite the databases if something gets messed up is an awesome idea!

**Comment by daren-thomas** [comment]
At `InputLocator` creation time there is no `config` object and therefore no region set. So... I am going to implement the other step instead - this is the same amount of work anyway, but won't introduce a (possibly) buggy hack to get at the region.

**Comment by JIMENOFONSECA** [comment]
What about, we create all databases when we run the first tool?

The thing is that i do not want to introduce a new tool in the workflow as we are out of time for testing.

So it would be good if i run any tool and i have access to all databases straight away.
On 7 Jun 2018, 19:16 +0800, Daren Thomas <notifications@github.com>, wrote:

At InputLocator creation time there is no config object and therefore no region set. So... I am going to implement the other step instead - this is the same amount of work anyway, but won't introduce a (possibly) buggy hack to get at the region.

**Comment by daren-thomas** [comment]
@JIMENOFONSECA please check out `cea create-default-databases` and the ArcGIS tool "Create Default Databases" in the "Datamanagement" toolbox.

**Comment by JIMENOFONSECA** [comment]
Cool, but can we still have the function that all databases be created at once without the tool?
On 7 Jun 2018, 19:58 +0800, Daren Thomas <notifications@github.com>, wrote:

@JIMENOFONSECA<https://github.com/JIMENOFONSECA> please check out cea create-default-databases and the ArcGIS tool "Create Default Databases" in the "Datamanagement" toolbox.

**Comment by daren-thomas** [comment]
ok. done. i will create an issue to remove the functionality afterwards again, because i think it makes the tool harder to understand. I do see your point on how the exercises etc. would need to be changed. But I think, from a teaching aspect (for the future) it's easier to communicate running the copy-default-databases tool as a step than "run any cea tool, that will copy the default databases by magic, oh, but also have side-effects".

**Comment by daren-thomas** [comment]
@JIMENOFONSECA this is the output from running the `cea data-helper` tool after removing the folder `C:\reference-case-open\baseline\databases`:

```
λ cea data-helper
Running `cea data-helper` with the following parameters:
- general:scenario = C:\reference-case-open\baseline
- general:region = SIN
- data-helper:archetypes = ['comfort', 'architecture', 'HVAC', 'internal-loads', 'supply', 'restrictions']
Copied file: C:\reference-case-open\baseline\databases\SIN\archetypes\construction_properties.xlsx
Copied file: C:\reference-case-open\baseline\databases\SIN\archetypes\occupancy_schedules.xlsx
Copied file: C:\reference-case-open\baseline\databases\SIN\archetypes\system_controls.xlsx
Copied file: C:\reference-case-open\baseline\databases\SIN\systems\supply_systems.xls
Copied file: C:\reference-case-open\baseline\databases\SIN\lifecycle\LCA_infrastructure.xlsx
Copied file: C:\reference-case-open\baseline\databases\SIN\lifecycle\LCA_buildings.xlsx
Copied file: C:\reference-case-open\baseline\databases\SIN\systems\emission_systems.xls
Copied file: C:\reference-case-open\baseline\databases\SIN\systems\envelope_systems.xls
Copied file: C:\reference-case-open\baseline\databases\SIN\systems\thermal_networks.xls
Copied file: C:\reference-case-open\baseline\databases\SIN\benchmarks\benchmark_2000W.xls
Copied file: C:\reference-case-open\baseline\databases\SIN\uncertainty\uncertainty_distributions.xls
Running data-helper with scenario = C:\reference-case-open\baseline
Running data-helper with archetypes = ['comfort', 'architecture', 'HVAC', 'internal-loads', 'supply', 'restrictions']
c:\users\darthoma\documents\github\cityenergyanalyst\cea\datamanagement\data_helper.py:219: UserWarning: Specified building database does not contain renovated building properties. Buildings are treated as new construction.
  'Specified building database does not contain renovated building properties. Buildings are treated as new construction.')
c:\users\darthoma\documents\github\cityenergyanalyst\cea\datamanagement\data_helper.py:164: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  names_df[field] = 0
```
and this is what the `databases` folder looks like after running the tool:

```
c:\reference-case-open\baseline\databases
λ tree /F
Folder PATH listing
Volume serial number is C84C-1BEB
C:.
└───SIN
    ├───archetypes
    │       construction_properties.xlsx
    │       occupancy_schedules.xlsx
    │       system_controls.xlsx
    │
    ├───benchmarks
    │       benchmark_2000W.xls
    │
    ├───lifecycle
    │       LCA_buildings.xlsx
    │       LCA_infrastructure.xlsx
    │
    ├───systems
    │       emission_systems.xls
    │       envelope_systems.xls
    │       supply_systems.xls
    │       thermal_networks.xls
    │
    └───uncertainty
            uncertainty_distributions.xls
```

What files am I missing? As far as I can tell, this should be all the databases, but if there are some missing, then please tell me where to find them.

**Comment by daren-thomas** [comment]
@JIMENOFONSECA the `cea test` is failing with this message: `XLRDError: No sheet named <'HEATING'>`

Do you know what that is about? Here's the traceback:

```
Traceback (most recent call last):
  File "C:\Users\darthoma\AppData\Local\conda\conda\envs\cea\lib\site-packages\doit\action.py", line 383, in execute
    returned_value = self.py_callable(*self.args, **kwargs)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\tests\dodo.py", line 358, in run_calibration
    calibration_sampling.sampling_main(locator=locator, config=config)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\demand\calibration\bayesian_calibrator\calibration_sampling.py", line 80, in sampling_main
    simulation = simulate_demand_sample(locator, building_name, building_load, config)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\demand\calibration\bayesian_calibrator\calibration_sampling.py", line 117, in simulate_demand_sample
    _ , time_series = demand_main.demand_calculation(locator, gv, config)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\demand\demand_main.py", line 91, in demand_calculation
    override_variables)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\demand\demand_main.py", line 133, in properties_and_schedule
    building_properties = BuildingProperties(locator, gv, use_daysim_radiation, region, override_variables)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\demand\building_properties.py", line 75, in __init__
    prop_supply_systems = get_properties_supply_sytems(locator, prop_supply_systems_building, region).set_index(
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\demand\building_properties.py", line 692, in get_properties_supply_sytems
    supply_heating = pd.read_excel(locator.get_life_cycle_inventory_supply_systems(region), "HEATING")
  File "C:\Users\darthoma\AppData\Local\conda\conda\envs\cea\lib\site-packages\pandas\io\excel.py", line 212, in read_excel
    **kwds)
  File "C:\Users\darthoma\AppData\Local\conda\conda\envs\cea\lib\site-packages\pandas\io\excel.py", line 438, in _parse_excel
    sheet = self.book.sheet_by_name(asheetname)
  File "C:\Users\darthoma\AppData\Local\conda\conda\envs\cea\lib\site-packages\xlrd\book.py", line 441, in sheet_by_name
    raise XLRDError('No sheet named <%r>' % sheet_name)
XLRDError: No sheet named <'HEATING'>
```

The interesting line seems to be this one:

```
 supply_heating = pd.read_excel(locator.get_life_cycle_inventory_supply_systems(region), "HEATING")
```

Did something change in the LCA databases?

**Comment by JIMENOFONSECA** [comment]
@daren-thomas quite weird. I am running the data-helper tool from pycharm and it only copies the archetypes folder. I do not receive any error there.

**Comment by JIMENOFONSECA** [comment]
ALSO when I run cea test The tool seems to use my present config file to run the tests.  So it points to another scenarios than the one of the tests

image

**Comment by daren-thomas** [comment]
@JIMENOFONSECA good catch about it not happening when running from PyCharm - the functionality is hooked into the `cea` tool as hooking it into the `InputLocator` has the problems described in the issue.

BUT: you're right, running `cea test` does end up adding the databases to your current scenario as `config.scenario` file. hm... I don't think this is much of a problem, because it only copies the files if they don't exist yet (test: re-run `cea test`). also, the files still get copied when first requested, so the scenario being tested by `cea test` will still get the databases copied (to the TEMP folder). and lastly, we'll be removing this "feature" after the executive course as described in the issue as I believe it is much easier to explain this if it happens explicitly (from the Zen of Python: explicit is better than implicit). Also, as you see here, there are problems with automagically doing it.

**Comment by JIMENOFONSECA** [comment]
I get it. So does this work from arcgis?
On 11 Jun 2018, 20:00 +0800, Daren Thomas <notifications@github.com>, wrote:

@JIMENOFONSECA<https://github.com/JIMENOFONSECA> good catch about it not happening when running from PyCharm - the functionality is hooked into the cea tool as hooking it into the InputLocator has the problems described in the issue.

BUT: you're right, running cea test does end up adding the databases to your current scenario as config.scenario file. hm... I don't think this is much of a problem, because it only copies the files if they don't exist yet (test: re-run cea test). also, the files still get copied when first requested, so the scenario being tested by cea test will still get the databases copied (to the TEMP folder). and lastly, we'll be removing this "feature" after the executive course as described in the issue as I believe it is much easier to explain this if it happens explicitly (from the Zen of Python: explicit is better than implicit). Also, as you see here, there are problems with automagically doing it.

**Pull request merged**
