### PR TITLE
1808 autodoc build for inputs/outputs graphviz 

### PR DESCRIPTION
**Pull request by Jack-Hawthorne**
this should hopefully fix the issue with graph rendering

### CODE REVIEW

**Comment by daren-thomas** [comment]
Can one of the admins verify this patch?

**Comment by daren-thomas** [comment]
image

Close, but the digraph for the `trace-inputlocator` script is missing indentation. Also, maybe that script doesn't need to be shown as it's more backstage...

Also, the paragraph leading in to the page (what are the cea scripts) will need some editing.

I couldn't find this script anywhere by following links. How does it fit into the whole documentation tree? Where to put it?

**Comment by Jack-Hawthorne** [comment]
dang, close but no cigar.

so to get this clear:
- remove the 'core' section with multiple scripts
- edit intro paragraph (to include all possible script names and description? - how do you want it to read?)
- the ``what-are-the-cea-scripts.rst`` is currently in the developers toctree in ``tutorials.rst``. Let me know where to put it ;)

**Comment by daren-thomas** [comment]
@Jack-Hawthorne not quite sure what you mean with 'core' section? let's meet in person :)

**Comment by Jack-Hawthorne** [comment]
ok so i've updated the default.config to include the following:
```
[trace-inputlocator]
scripts = data-helper, demand, emissions
scripts.type = MultiChoiceParameter
scripts.choices = benchmark-graphs,
    compile,
    copy-default-databases,
    create-new-project,
    dashboard,
    data-helper,
    dbf-to-excel-to-dbf,
    decentralized,
    demand,
    emissions,
    excel-to-shapefile,
    extract-reference-case,
    install-arcgis,
    install-grasshopper,
    lake-potential,
    list-demand-graphs-fields,
    multi-criteria-analysis,
    network-layout,
    operation-costs,
    optimization,
    photovoltaic,
    photovoltaic-thermal,
    plots,
    plots-optimization,
    plots-scenario-comparisons,
    plots-supply-system,
    radiation-daysim,
    scenario-plots,
    sensitivity-demand-analyze,
    sensitivity-demand-samples,
    sensitivity-demand-simulate,
    sewage-potential,
    shapefile-to-excel,
    solar-collector,
    supply-system-simulation,
    test,
    thermal-network,
    thermal-network-optimization
scripts.help = sequential list of scripts to run
```
did a rebuild of the reference-case and run data-helper.

still can't run the necessary scripts:

```
(cea) C:\Users\Jack\Documents\GitHub\CityEnergyAnalyst>cea network-layout
City Energy Analyst version 2.9.2
Running `cea network-layout` with the following parameters:
- general:scenario = C:\reference-case-open\baseline
  (default: C:\reference-case-open\baseline)
- network-layout:network-type = DC
  (default: DC)
- network-layout:buildings = []
  (default: [])
- network-layout:pipe-diameter = 150
  (default: 150)
- network-layout:type-mat = T1
  (default: T1)
- network-layout:create-plant = True
  (default: True)
- network-layout:allow-looped-networks = False
  (default: False)
Traceback (most recent call last):
  File "C:\Users\Jack\Miniconda2\envs\cea\Scripts\cea-script.py", line 11, in <module>
    load_entry_point('cityenergyanalyst', 'console_scripts', 'cea')()
  File "c:\users\jack\documents\github\cityenergyanalyst\cea\interfaces\cli\cli.py", line 65, in main
    script_module.main(config)
  File "c:\users\jack\documents\github\cityenergyanalyst\cea\technologies\thermal_network\network_layout\main.py", line 57, in main
    network_layout(config, locator, plant_building_names)
  File "c:\users\jack\documents\github\cityenergyanalyst\cea\technologies\thermal_network\network_layout\main.py", line 46, in network_layout
    disconnected_building_names = config.thermal_network.disconnected_buildings
  File "c:\users\jack\documents\github\cityenergyanalyst\cea\config.py", line 236, in __getattr__
    "Parameter not configured to work with this script: {%s}" % self.parameters[cid].fqname)
AttributeError: Parameter not configured to work with this script: {thermal-network:disconnected-buildings}
```

```
(cea) C:\Users\Jack\Documents\GitHub\CityEnergyAnalyst>cea thermal-network
City Energy Analyst version 2.9.2
Running `cea thermal-network` with the following parameters:
- general:scenario = C:\reference-case-open\baseline
  (default: C:\reference-case-open\baseline)
- general:region = CH
  (default: CH)
- general:weather = c:\users\jack\documents\github\cityenergyanalyst\cea\databases\weather\Zug.epw
  (default: c:\users\jack\documents\github\cityenergyanalyst\cea\databases\weather\Zug.epw)
- general:multiprocessing = True
  (default: True)
- general:number-of-cpus-to-keep-free = 1
  (default: 1)
- thermal-network:network-type = DH
  (default: DH)
- thermal-network:network-names = []
  (default: [])
- thermal-network:file-type = shp
  (default: shp)
- thermal-network:set-diameter = True
  (default: True)
- thermal-network:load-max-edge-flowrate-from-previous-run = False
  (default: False)
- thermal-network:start-t = 0
  (default: 0)
- thermal-network:stop-t = 8760
  (default: 8760)
- thermal-network:minimum-mass-flow-iteration-limit = 30
  (default: 10)
- thermal-network:minimum-edge-mass-flow = 0.1
  (default: 0.1)
- thermal-network:diameter-iteration-limit = 10
  (default: 5)
- thermal-network:substation-cooling-systems = ['ahu', 'aru', 'scu']
  (default: ['ahu', 'aru', 'scu'])
- thermal-network:substation-heating-systems = ['ahu', 'aru', 'shu', 'ww']
  (default: ['ahu', 'aru', 'shu', 'ww'])
- thermal-network:disconnected-buildings = []
  (default: [])
Traceback (most recent call last):
  File "C:\Users\Jack\Miniconda2\envs\cea\Scripts\cea-script.py", line 11, in <module>
    load_entry_point('cityenergyanalyst', 'console_scripts', 'cea')()
  File "c:\users\jack\documents\github\cityenergyanalyst\cea\interfaces\cli\cli.py", line 63, in main
    script_module = importlib.import_module(cea_script.module)
  File "C:\Users\Jack\Miniconda2\envs\cea\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "c:\users\jack\documents\github\cityenergyanalyst\cea\technologies\thermal_network\thermal_network_matrix.py", line 28, in <module>
ImportError: cannot import name FULL_COOLING_SYSTEMS_LIST
````

**Comment by Jack-Hawthorne** [comment]
@daren-thomas can we merge this so the graphs are at least rendered properly for now, we can add rest of the scripts with a new issue and pr when my version of cea is running properly

**Pull request merged**
