### PR TITLE
Plot cache for dashboard

### PR DESCRIPTION
**Pull request by daren-thomas**
This pull request implements a caching system for plots and their data (see `cea.plots.cache.PlotCache`)

Data used by plots can be cached using `PlotCache.lookup(...)` to the folder `$project/.cache/<category_name>/<data_or_plot_name>/`. The filename for the cached data is made by using a md5 hash of the sorted parameter dictionary. This guarantees unique names for the same data with different parameters.

Each plot lists it's `input_files` in the `__init__` method. The timestamps of these files are compared with the cached data and if a newer one is found, the data is re-calculated.

The `<div/>` version of the plots are cached using the same mechanism to speed up the display of the dashboard.

### CODE REVIEW

**Comment by JIMENOFONSECA** [comment]
I am trying to add the plot 'energy demand' = 'comfort-chart' and get the next error:

chrome_5TsGLSa3IW

I also tried with several of the plots of the category 'energy demand', and get a similar error

**Comment by JIMENOFONSECA** [comment]
@daren-thomas also the function of adding a new dashboard is broken too....

**Comment by daren-thomas** [comment]
Good testing! I'm on it!

**Comment by JIMENOFONSECA** [comment]
@daren-thomas your welcome!. while I was at it I also found #1868 #1869 and #1870

**Comment by daren-thomas** [comment]
It should work now. I've tested adding new dashboards, deleting dashboards (remove all plots in a dashboard to delete it), adding plots to dashboard, moving plots around. Also, made sure `.cache` does not show up as a scenario...

**Comment by daren-thomas** [comment]
I think #1868, #1869, #1870 are probably unrelated to this PR - I'd like to address them in a separate branch. Feel free to merge this when you're ready :)

**Comment by JIMENOFONSECA** [comment]
alright the cache seems to work, the only thing is that when I create new dashboards and then switch among them, the data seem to be reloaded (it makes it slow, especially with the the 'heating reset' diagram. 

is this an error?

**Comment by daren-thomas** [comment]
@JIMENOFONSECA as far as I can tell it's not the data being reloaded, it's in plotly itself - so the way plotly works is that it creates the plot with javascript on the page. To test this, open up the heating reset schedule created by the old plots command (the html file in outputs/plots/basic/demand) and wait for it to show up in the browser. Then refresh. This is the same behavior as the dashboard - ergo not a caching problem.

**Pull request merged**
