### PR TITLE
I837 ecocampus demand check

### PR DESCRIPTION
**Pull request by JIMENOFONSECA**

### CODE REVIEW

**Comment by JIMENOFONSECA** [comment]
@BhargavaKrishnaSreepathi coul you try this out for ecocampus in your computer? the results seem to be coherent now... bear in mind that the config file default changed. so you need to change yours for testing

**Comment by JIMENOFONSECA** [comment]
It takes 20 min to run :-)

**Comment by daren-thomas** [comment]
Build finished.

**Comment by daren-thomas** [comment]
Build finished.

**Comment by daren-thomas** [comment]
Build finished.

**Pull request merged**
