### PR TITLE
Fix EV input validation in editor

### LINKED ISSUE #3327: Bug in EV schedule
Under the Input Editor/schedules/electromobility the input accepts only binary values and can not be modified for integer values.
Path to reproduce error:
Input Editor -> Schedules->Electromobility-> Select building-> input EV number -> ERROR

image

### PR DESCRIPTION
**Pull request by reyery**
Closes #3327

Run to test
```
cea dashboard --browser true
```

Non-browser version (GUI application) will not be updated

### CODE REVIEW

**Comment by jimenofonseca** [comment]
Is the Idea that from now on we will not support the normal version? if so how do we Install and Launch CEA from now on? und starting as of when is this ready?
I missed the discussion about this important change :)

**Comment by jimenofonseca** [comment]
Fun!So i guess the webversion has full funktionality now?On the other hand:Do I define the schemas for that table in the same way as the others?On 19 Jun 2023, at 17:18, Reynold Mok ***@***.***> wrote:﻿
Significant changes were made to enable the browser version and most fixes have been applied to it. Applying the same fixes to the non-browser version would require quite a bit of work. And I currently do not have the resources to support two versions of the frontend.
As long as you have the dev version, you should be able to run the browser version without any problems or installing anything else.

**Comment by reyery** [comment]
@jimenofonseca I have included this fix into the GUI application. A new release will be up soon that includes this and can be installed.

**Comment by jimenofonseca** [comment]
Very cool. Please let me know!On 29 Jun 2023, at 14:12, Reynold Mok ***@***.***> wrote:﻿
@jimenofonseca I have included this fix into the GUI application. A new release will be up soon that includes this and can be installed.

**Pull request merged**
