### PR TITLE
1971 check input files

### PR DESCRIPTION
**Pull request by daren-thomas**
This pull request addresses 1971 by checking the input files for each script before running it via `cea.api`.

The logic used depends on `scripts.yml` having containing a list of input-files for each script as determined by their locator. This is... maybe not the best way to do it, but works quickly with what we currently have. A better solution would be to move scripts configuration into classes similar to plots, but this is out of scope for the MuSES project - we'd have to revisit each script and we really just don't have time for this.

The information for `scripts.yml` input-files was taken from `schemas.yml` which is currently being updated using @Jack-Hawthorne's work. I expect newer results tomorrow.

To test:
- run a script from the Dashboard that you know works (operation-costs runs quickly)
- delete an input file for that script
- run the script again

expected output is something like this:

```
City Energy Analyst version 2.16
Running `cea operation-costs` with the following parameters:
- general:scenario = C:\Users\daren-thomas\Downloads\reference-case-cooling\baseline
  (default: C:\reference-case-open\baseline)

---------------------------
ERROR: Missing input files:
- C:\Users\daren-thomas\Downloads\reference-case-cooling\baseline\outputs\data\demand\Total_demand.csv
  - try running demand
```
The output includes a hint on what tool to run to fix the error.

### CODE REVIEW

**Comment by reyery** [comment]
@daren-thomas do we need to do version control for files in `notebooks/.ipynb_checkpoints`? I thought it is usually ignored.

**Comment by daren-thomas** [comment]
you're right. we don't need to. wait. i'll add that to .gitignore.

**Comment by reyery** [comment]
So far it works for the scripts that I have tried running, but `multi-criteria-analysis` does not seem to show the new prompt for a missing file.

```
City Energy Analyst version 2.17a0
Running `cea multi-criteria-analysis` with the following parameters:
- general:scenario = C:\new-project\new-scenario
  (default: C:\reference-case-open\baseline)
- general:detailed-electricity-pricing = False
  (default: False)
- multi-criteria:generations = 3
  (default: 3)
- multi-criteria:network-type = DH
  (default: DC)
- multi-criteria:economicsustainability = 0.8
  (default: 0.8)
- multi-criteria:environmentalsustainability = 0.1
  (default: 0.1)
- multi-criteria:socialsustainability = 0.1
  (default: 0.1)
- multi-criteria:annualizedcosts = 0.8
  (default: 0.8)
- multi-criteria:capextotal = 0.1
  (default: 0.1)
- multi-criteria:opex = 0.1
  (default: 0.1)
- multi-criteria:emissions = 0.5
  (default: 0.5)
- multi-criteria:primaryenergy = 0.5
  (default: 0.5)
- multi-criteria:renewableshare = 1.0
  (default: 1.0)
- thermal-network:network-names = []
  (default: [])
- thermal-network:network-type = DH
  (default: DH)
Running multicriteria with scenario = C:\new-project\new-scenario
Running multicriteria for generation = 3
Process Process-9:
Traceback (most recent call last):
  File "C:\Users\Admin\Documents\CityEnergyAnalyst\Dependencies\Python\lib\multiprocessing\process.py", line 267, in _bootstrap
    self.run()
  File "C:\Users\Admin\Documents\CityEnergyAnalyst\Dependencies\Python\lib\multiprocessing\process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Admin\Documents\CityEnergyAnalyst\CityEnergyAnalyst\cea\interfaces\dashboard\tools\worker.py", line 19, in run_script
    script(**kwargs)
  File "C:\Users\Admin\Documents\CityEnergyAnalyst\CityEnergyAnalyst\cea\api.py", line 32, in script_runner
    script_module.main(config)
  File "C:\Users\Admin\Documents\CityEnergyAnalyst\CityEnergyAnalyst\cea\analysis\multicriteria\main.py", line 427, in main
    multi_criteria_main(locator, config)
  File "C:\Users\Admin\Documents\CityEnergyAnalyst\CityEnergyAnalyst\cea\analysis\multicriteria\main.py", line 44, in multi_criteria_main
    data_address = locating_individuals_in_generation_script(generation, locator)
  File "C:\Users\Admin\Documents\CityEnergyAnalyst\CityEnergyAnalyst\cea\analysis\multicriteria\optimization_post_processing\locating_individuals_in_generation_script.py", line 58, in locating_individuals_in_generation_script
    data_generation = preprocessing_generations_data(locator, generation)
  File "C:\Users\Admin\Documents\CityEnergyAnalyst\CityEnergyAnalyst\cea\analysis\multicriteria\optimization_post_processing\locating_individuals_in_generation_script.py", line 135, in preprocessing_generations_data
    with open(locator.get_optimization_checkpoint(generations), "rb") as fp:
IOError: [Errno 2] No such file or directory: 'C:\\new-project\\new-scenario\\outputs\\data\\optimization\\master\\CheckPoint_3'
```

**Comment by daren-thomas** [comment]
@reyery this is mainly due to the trace-inputlocator not having been run for the multi-criteria-analysis yet. so we don't have that data in `schemas.yml` yet. i'll be running the optimization script over the weekend and will then follow with the `multi-criteria-analysis` script once done. it just takes forever, as tracing adds an overhead to each function call.

**Comment by daren-thomas** [comment]
@JIMENOFONSECA can you please comment on why you moved this to M2.19? We're currently in M2.18 and leaving the PR (which works fine as far as i can tell) for 4 weeks to grow stale... I just feel I'd like to know more about your reasoning for this.

**Comment by JIMENOFONSECA** [comment]
@daren-thomas my bad! i thought 2.19 was the the next one

**Comment by daren-thomas** [comment]
@JIMENOFONSECA ah! that explains a lot :-)

**Comment by daren-thomas** [comment]
Is there a reason this was never merged? It's probably better to wait until after the demo, but... it _has_ been here for a while...

**Comment by reyery** [comment]
Oh sorry, thought there were further edits so I did not merge it.

**Pull request merged**
