### PR TITLE
1870 dashboard settings not working for capex vs opex

### PR DESCRIPTION
**Pull request by daren-thomas**
This pull request implements most of #1870. 

What is missing (and I don't feel competent to provide - @JIMENOFONSECA maybe?) is the definite list of parameters each of the optimization plots requires. The current list is taken from those required by the tool `cea plots-optimization` and is basically modeled after the config parameters. The place to edit the required parameters for all optimization plots is here: `cea.plots.optimization.OptimizationOverviewPlotBase` (check the `expected_parameters` attribute. Subclasses can also override this if they need more parameters.

To test: Create a dashboard and add the optimization plots. open up the parameters dialog. Make a change. Save. Or don't make a change and save. Expect: The plot to be updated based on the parameter data.

### CODE REVIEW

**Comment by JIMENOFONSECA** [comment]
@daren-thomas could you test this again in your computer? this does not work in mine, I get an error in the server while switching inside the options of DC and DH inside the plots..

**Comment by daren-thomas** [comment]
@JIMENOFONSECA what error are you getting?

**Comment by JIMENOFONSECA** [comment]
A white page in the browser saying "route not found / or similar". does the chart work for you straightaway?

**Comment by daren-thomas** [comment]
image

**Comment by daren-thomas** [comment]
When switching from DC to DH, I get this:

image

(there isn't any DH optimization data, so that would explain a lot!) I'm looking into adding some input_files to make that distinction raise a more sensible error.

**Comment by daren-thomas** [comment]
I just ran the `trace_inputlocator` to find possible candidate input files to detect whether DC or DH was used for the optimization. It turns out that this doesn't really work, because of the way the InputLocator is used for optimization: It seems, there are separate methods used contain the network type as part of their method name instead of as arguments (`get_optimization_decentralized_folder_building_result_cooling` vs. `get_optimization_decentralized_folder_building_result_heating` instead of the network type being an argument to a (supposed) `get_optimization_decentralized_folder_building_result`)

This is a result of big `if` statements duplicating code for heating / cooling cases and can only really be fixed by refactoring the optimization code. So, for the purposes of this issue, I suggest merging as the original bug as far as I can tell is fixed. We just still have issues with DC vs. DH optimization...

**Comment by daren-thomas** [comment]
Created issue #2122 to track the issue of switching from DC to DH.

**Comment by daren-thomas** [comment]
updated from master. @JIMENOFONSECA are we going to merge this?

**Comment by reyery** [comment]
I tried plotting all 4 plots but I keep getting this error.
```
Traceback (most recent call last):
  File "C:\Users\Admin\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Admin\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Admin\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Admin\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Admin\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Admin\Documents\CityEnergyAnalyst\CityEnergyAnalyst\cea\interfaces\dashboard\plots\routes.py", line 109, in route_add_plot_to_dashboard
    dashboard.add_plot(category, plot_id)
  File "C:\Users\Admin\Documents\CityEnergyAnalyst\CityEnergyAnalyst\cea\plots\__init__.py", line 109, in add_plot
    plot = plot_class(self.config.project, parameters, self.cache)
  File "C:\Users\Admin\Documents\CityEnergyAnalyst\CityEnergyAnalyst\cea\plots\optimization\pareto_curve.py", line 27, in __init__
    super(ParetoCurveForOneGenerationPlot, self).__init__(project, parameters, cache)
  File "C:\Users\Admin\Documents\CityEnergyAnalyst\CityEnergyAnalyst\cea\plots\optimization\__init__.py", line 63, in __init__
    self.data_address = locating_individuals_in_generation_script(self.generation, self.locator)
  File "C:\Users\Admin\Documents\CityEnergyAnalyst\CityEnergyAnalyst\cea\analysis\multicriteria\optimization_post_processing\locating_individuals_in_generation_script.py", line 58, in locating_individuals_in_generation_script
    data_generation = preprocessing_generations_data(locator, generation)
  File "C:\Users\Admin\Documents\CityEnergyAnalyst\CityEnergyAnalyst\cea\analysis\multicriteria\optimization_post_processing\locating_individuals_in_generation_script.py", line 156, in preprocessing_generations_data
    with open(locator.get_optimization_checkpoint(generations), "rb") as fp:
IOError: [Errno 2] No such file or directory: 'C:\\plot-test\\baseline\\outputs\\data\\optimization\\master\\CheckPoint_3'
```

**Comment by daren-thomas** [comment]
@reyery the data i gave you only has 2 generations - for some reason the default value is 3 generations (see default.config and your cea.config).

**Comment by reyery** [comment]
@daren-thomas I have changed the config here

```
[plots-optimization]
generation = 2
network-type = DC
multicriteria = true
categories = pareto_curve, system_sizes, costs_analysis
```

but is still get the same error

**Comment by reyery** [comment]
@daren-thomas I could not find any plots that have boolean parameters so I could not test the new green toggle thing. Other than that I think I can merge this already.

**Pull request merged**
