### PR TITLE
DE database supply technolgies fix

### PR DESCRIPTION
**Pull request by ddceruti**
I assgined all TABULA supply technologies and addded all required technologies with costs and efficienceies to the BOILER and HEATPUMP sheets in the CONVERSION excel file as discussed in the issue #3573. I also updated the documentation accordingly. As the CAPEX can be calulcated in two places at the same time, I have left the SUPPLY file cost parameters untouched and just assigned the technologies. 

@MatNif can you provide some feedback if the changes are enough and if you require some more changes?

Disclaimer: the main cost source of KEA Baden Württenberg is quite a lot cheaper than the current CH database costs - mainly due to the very high fixed costs defined in CONVERSION. For a 60kW gas boiler: old CAPEX = 40 800 USD; new CAPEX = 6400 USD.
Maybe we can discuss some approaches to homogenize the costs. 

@ShiZhongming, @ whole CEA dev team: these changes are very difficult to follow since excel files are not supported properly and you cannot see the changes line by line. If more countries want to contribute their databases, this should be changed urgently to allow proper collaborative workflows.

### CODE REVIEW

**Comment by MatNif** [comment]
Hi @ddceruti, as far I can tell so far, the changes look good and the databases look complete.
As you correctly mentioned though, it is a bit difficult to review the details of the changes made in the databases. As such I still need a bit more time for testing since in the process of testing the new databases I have run into a related issue but that doesn't concern your changes directly. 

The issue is more with how the developersversion of CEA loads the databases for me. While the DE databases of my CEA installation were changed according to your latest updates within the CEA installations database folders, when I created a new test case the databases in the inputs did not adequately reflect these changes, but loaded the outdated versions of the databases instead. As expected, this lead to the previously encountered crash of the optimisation script.

@reyery or @ShiZhongming, do you have an idea of how to change/fix this behaviour? As far as I could determine when I ran the data-initialiser, the databases actually are loaded in from the dependencies instead of the CityEnergyAnalst folder, specifically from:
`- data-initializer:databases-path = C:\Users\nimathia\Documents\GitHub\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\site-packages\cea\databases\DE`
I assume the intended behaviour would be that the database in the dependencies gets updated adequately when the github branch that the installation points to changes. That did not happen in my case.

**Comment by ShiZhongming** [comment]
Thanks @ddceruti and @MatNif !
Rey and I will take a look at this next week.

**Comment by reyery** [comment]
@MatNif are you running it via pycharm or the CEA console. It should change accordingly when CEA is installed as "editable" in the python environment. i.e. `pip install -e .`

Could you try running `pip list` and see if `cityenergyanalyst` has a `Editable project location`?

**Comment by MatNif** [comment]
Hi @reyery.

I ran the majority of the scripts through the dashboard (including the `Database initializer`).
And, yes, you were right. I seem to have mad a mistake in the installation process indeed.

After reinstalling in 'editable mode', the path in the database initialiser now points to the correct location as well, i.e.:
`- data-initializer:databases-path = C:\Users\nimathia\Documents\GitHub\CityEnergyAnalyst\CityEnergyAnalyst\cea\databases\DE`

So, in my opinion, the database updates are now functional and good to go. The layout of the `CONVERSION` database is a bit messed up in parts (e.g., the boilers tab), but that doesn't prevent it from working as intended.

**Comment by ShiZhongming** [comment]
Thank you @ddceruti for providing this. Also many thinks to @Mar-Ges @ululele.
Thanks to @MatNif for reviewing it.

**Pull request merged**
