### PR TITLE
1069 db metadata

### PR DESCRIPTION
**Pull request by Jack-Hawthorne**
The new ``trace-inputlocator`` script is functional. Added methods:
- get_schema: returns a dict containing the schema depending on file type
- get_meta: returns a dict of each attribute mapped to a sample value and  data type
- is_date: checks if any data types are date
- replace_repetitive_attr: checks for srf, PIPE, NODE and building based attributes and writes them as only the first (index = 0).

Potential issues:
- xlsx files are currently transposed if the sheet contains an unassigned column name (attribute name). this is due to the occupancy schedules having weird indexing.

### CODE REVIEW

**Comment by daren-thomas** [comment]
Can one of the admins verify this patch?

**Comment by JIMENOFONSECA** [comment]
@Jack-Hawthorne I am not sure if the recent PR, which puts the region parameter only inside of the 'data-helper' function messes with this PR. @daren-thomas maybe you are the most suitable to check this PR?

**Comment by daren-thomas** [comment]
@JIMENOFONSECA yes, I'll check it on monday. So far, looks good. But I'd like to test. Just don't have time.

**Comment by Jack-Hawthorne** [comment]
@JIMENOFONSECA @daren-thomas 
update:
trace successful for the decentralized script.

optimization script is not working on branch ``1069-db-metadata`` (pulled from master friday 12/4/19) due to issue #1883 

results pending for optimization.

**Comment by Jack-Hawthorne** [comment]
@daren-thomas has asked for a complete overview of how to run the new ``trace-inputlocator`` script and what outputs to expect. it operates essentially exactly the same as the old trace-inputlocator, which is called from the cli using ``cea trace-inputlocator --scripts <insert script>``.

outputs:
- graph viz file containing the names of the scripts for which trace was run.
- yaml file containing a nested dict whose main keys are the inputlocator methods

note:
If more than one script is entered (separated by commas), it will change the viz output but will not influence the yaml

it is most likely best to run this using a batch file, running through the sequence of singular scripts:
instead of: 
``cea trace-inputlocator --scripts data-helper, radiation-daysim, demand``
with outputs: 
- ``trace_inputlocator.output.yml`` 
- ``data-helper_radiation-daysim_demand.gv``

it would be best to use three separate commands via a bat:
``cea trace-inputlocator --scripts data-helper``
``cea trace-inputlocator --scripts radiation-daysim``
``cea trace-inputlocator --scripts demand``

with outputs: 
- ``trace_inputlocator.output.yml`` 
- ``data-helper.gv``
- ``radiation-daysim.gv``
- ``demand.gv``


the yaml output is stored in a singular file whose keys are only overwritten when used by the script for which trace is overseeing:

```
get_building_architecture:
    created_by: [data-helper]
    description: "scenario/inputs/building-properties/architecture.dbf\n        This\
        \ file is generated by the properties script.\n        This file is used in\
        \ the embodied energy script (cea/embodied.py)\n        and the demand script\
        \ (cea/demand_main.py)"
    file_path: c:\reference-case-open\WTP_CBD_h\inputs/building-properties\architecture.dbf
    file_type: dbf
    schema:
        Es:
            sample_data: 0.9
            types_found: [float]
        Hs:
            sample_data: 0.9
            types_found: [float]
        Name:
            sample_data: B010
            types_found: [string]
        Ns:
            sample_data: 0.9
            types_found: [float]
        type_cons:
            sample_data: T3
            types_found: [string]
        type_leak:
            sample_data: T2
            types_found: [string]
        type_roof:
            sample_data: T4
            types_found: [string]
        type_shade:
            sample_data: T1
            types_found: [string]
        type_wall:
            sample_data: T5
            types_found: [string]
        type_win:
            sample_data: T2
            types_found: [string]
        void_deck:
            sample_data: 0
            types_found: [int]
        wwr_east:
            sample_data: 0.4
            types_found: [float]
        wwr_north:
            sample_data: 0.4
            types_found: [float]
        wwr_south:
            sample_data: 0.4
            types_found: [float]
        wwr_west:
            sample_data: 0.4
            types_found: [float]
    used_by: [radiation-daysim, emissions, demand]
```
each time a script uses the method as an 'input', it is added to the list under the key `used_by`
each time a script writes an output, it is added to the list under the key 'created_by'

some of the automatically assigned python variables get in the way, for example when a element is passed as a int or float:
```
            month:
                sample_data: 1.0
                types_found: [int, float, null]
```

hope this clears things up.

**Comment by Jack-Hawthorne** [comment]
additionally:
if you want to update the documentation for the viz graphs in the readthedocs documentation:

copy all the viz files and dump them in ``CityEnergyAnalyst\docs\script_dependencies``
then run the script ``script_dependencies_gen.py`` (in the same dir)

note: this will only use viz files which are in the list of scripts (i.e. will not use combined files such as ``data-helper_demand_radiation-daysim.gv``)

it will create ``CityEnergyAnalyst\docs\script-input-outputs.rst`` based on the jinja template in the ``docs\script_dependencies'' dir

**Pull request merged**
