### PR TITLE
Bugfix for input editor

### LINKED ISSUE #2136: Bugfixes for input editor in dashboard
There still a few bugs that need to be squashed before it is fully usable.

### PR DESCRIPTION
**Pull request by reyery**
This PR resolves #2136. It includes mostly cosmetic changes to the input editor and some minor fixes.

Fixes
---
- Fix a bug where hidden layers reappear when editing properties of buildings
- Only show the delete warning message in the saving prompt when there are buildings being deleted
- Make sure cursor is a pointer instead of a caret when hovering over property tab
- Reformat tooltips such as precision of number values
- Remove some redundant code

Additions
---
- Bootstrap tooltips are now shown when hovering over tools in the side navigation and column headers in the editor table
- User will be alerted when leaving the editing page without saving changes

### CODE REVIEW

**Comment by daren-thomas** [comment]
@reyery what am I supposed to test? What are the bugs that were fixed?

**Comment by daren-thomas** [comment]
BTW: @reyery great job on commit messages!

**Comment by reyery** [comment]
Testing
---
- Hide the `zone` layer and edit some properties of `zone` buildings. 
Save the changes and the zone building should not reappear.

- Edit properties only and attempt to save.
Saving prompt should not should not show the delete warning.

- Edit properties and attempt to navigate out of the page.
A prompt should appear for confirmation of leaving page.

**Comment by daren-thomas** [comment]
@reyery the last point only works when editing in the table directly - as opposed to the "Edit Selection" dialog. I'm creating a separate issue for this (#2149)

**Pull request merged**
