### PR TITLE
fix according to calc_temperature_ground

### PR DESCRIPTION
**Pull request by JIMENOFONSECA**
this fixes #914

### CODE REVIEW

**Comment by gabriel-happle** [comment]
Cool!
Looks good.
With this fix I believe we can remove the `seasonhours` parameter from `gv`. Could you please test that and remove it, if the checks pass.

**Comment by JIMENOFONSECA** [comment]
@gabriel-happle thanks :-). unfortunately seson hours is still used by the neural network...

**Comment by JIMENOFONSECA** [comment]
@gabriel-happle if it is ok, would you add a review so we can merge?

**Comment by JIMENOFONSECA** [comment]
@gabriel-happle if it is ok, would you add a review so we can merge?

**Pull request merged**
