### PR TITLE
Fix bug on I_rad calculation

### PR DESCRIPTION
**Pull request by pajotca**
The calculation of the external radiative heat transfer coefficient should use the arithmetic average of the surface temperature and the sky temperature, in degree Celcius.
(cf http://www.cres.gr/greenbuilding/PDF/prend/set3/WI_14_TC-draft-ISO13790_2006-07-10.pdf p64)

### CODE REVIEW

**Comment by daren-thomas** [comment]
Can one of the admins verify this patch?

**Comment by gabriel-happle** [comment]
dear @pajotca many thanks for your pull request!
I checked ISO 13790, and there seems to be some bug here indeed.
However, I'm not sure if you fixed it in the correct way.

**Comment by gabriel-happle** [comment]
By the way, section 11.4.6 also specifies the range of `delta_theta_er` to be approximately `9 K <= delta_theta_er <= 11 K`. We should check that during testing.

**Comment by gabriel-happle** [comment]
@daren-thomas what kind of workflow are you suggesting here?
Should I make a new branch and fix the bug?
But then how is @pajotca's contribution accounted for?

**Comment by gabriel-happle** [comment]
> 
> 
> The calculation of the external radiative heat transfer coefficient should use the arithmetic average of the surface temperature and the sky temperature, in degree Celcius.
> (cf http://www.cres.gr/greenbuilding/PDF/prend/set3/WI_14_TC-draft-ISO13790_2006-07-10.pdf p64)

This is the norm @pajotca (or at least the draft for the norm).

**Comment by daren-thomas** [comment]
@gabriel-happle can you fix the bug on @pajotca's branch and we merge that? please also make sure to add @pajotca to the CREDITS.md file in that branch (for version 2.10?)

**Comment by gabriel-happle** [comment]
fixing this in branch #i-1767-fix-longwave-radiation-bug

**Comment by gabriel-happle** [comment]
@daren-thomas Is there any way to directly convert this PR to an issue and connect to PR #1778 ?
Otherwise I can copy the conversation to a new issue and delete this PR.

**Comment by daren-thomas** [comment]
@gabriel-happle googling "github convert pr to issue" suggests that this is not possible.

**Comment by daren-thomas** [comment]
@gabriel-happle googling "github convert pr to issue" suggests that this is not possible. You can however connect this PR with an issue and close it.

**Comment by gabriel-happle** [comment]
closing this. see #1778 and #1779 for more info.

**Pull request closed without merging**
