### PR TITLE
Cost analysis plots

### PR DESCRIPTION
**Pull request by BhargavaKrishnaSreepathi**
This PR, removes the small bug in optimization. 
It also includes a script for lake potential, which currently creates an array of zeros, which can be changed in future.
It also creates a script for cost-analysis.

To test this, use a fresh copy of `reference-case-open`, run all the corresponding files before optimization as given in the workflow. Apart from this also run `cea\technologies\lake_potential.py` file and then run optimization and follow this with cea plots

### CODE REVIEW

**Comment by JIMENOFONSECA** [comment]
@BhargavaKrishnaSreepathi you need to add a tool to arcgis to call lake potential too. coudl you include that as part of this PR?

**Comment by BhargavaKrishnaSreepathi** [comment]
sure.

**Comment by BhargavaKrishnaSreepathi** [comment]
The interface is ready, and I also updated the workflow. From now on, we should even run lake potential in the ArcGIS interface.

**Comment by JIMENOFONSECA** [comment]
@BhargavaKrishnaSreepathi do the tests pass locally?

**Comment by BhargavaKrishnaSreepathi** [comment]
@jimenofonseca: Yes they pass for me locally, tested it just now

**Comment by BhargavaKrishnaSreepathi** [comment]
@JIMENOFONSECA, @amraladdin @shanshanhsieh @gabriel-happle @roglen @ongbolie @shizhongming @martin-mosteiro 

Hi All,

Can you all test your respective case studies in this PR. This is the last update from optimization side to the CEA before the executive course. This PR tries to address most of the discussed issues which were encountered while running the respective case studies. It would be very helpful if you provide your feedback about the PR and any issues you face. 
The way to test this PR is basically run the entire workflow of CEA, from datahelper to plots and tell if you have any errors.

Thanks a lot.

Cheers,
Bhargav

**Comment by BhargavaKrishnaSreepathi** [comment]
@daren-thomas: I have run the `cea test` locally and it passes all the 27 tests. I am not sure why the PR here say `All checks have failed`. Can you help me with this problem? Thank you.

**Comment by daren-thomas** [comment]
@BhargavaKrishnaSreepathi I think I know what might be going on - I'm currently working on a fix for the Jenkins tests. I'll keep you guys posted!

**Pull request merged**
