### PR TITLE
Cea open case study updated

### PR DESCRIPTION
**Pull request by JIMENOFONSECA**
@gabriel-happle @shanshanhsieh I am seeing that specific combinations of controls and cooling systems (t4: 3for2, result in no cooling demand. It seems a bug.

### CODE REVIEW

**Comment by JIMENOFONSECA** [comment]
@gabriel-happle @shanshanhsieh I updated the issue. It was other problem. but still exists.

The issue happens in this new case study for buildings 04 and 05. In building 04 it is expected to not be cooling load. but in B05 it is strange

image

**Comment by JIMENOFONSECA** [comment]
@gabriel-happle @shanshanhsieh I did some more tests. the problem was in the archetypes. 

@gabriel-happle please review just if the case study works in your PC. thanks

**Comment by gabriel-happle** [comment]
@JIMENOFONSECA  the case study runs for me. However, I get this message:

```Building No. 2 completed out of 9
Building No. 3 completed out of 9
Building No. 4 completed out of 9
**Warning: Soil-water HP currently not available.**
Building No. 5 completed out of 9```

**Comment by JIMENOFONSECA** [comment]
@shanshanhsieh @BhargavaKrishnaSreepathi any idea about this warning? (see above)

**Comment by shanshanhsieh** [comment]
The warning comes from calculating electricity for on-sight generation.
It happens when `type_cs` in the `supply_systems.xls` is `T1`
check `calc_heatpump_cooling_electricity` in `cea/demand/electrical_loads.py`

**Comment by gabriel-happle** [comment]
@JIMENOFONSECA This is your code from legacy. I haven't touched it yet.
Only the options for air-water heatpumps are coded as far as I know.

**Comment by JIMENOFONSECA** [comment]
Now I remember, the value Egenf accounts when the building has a heat pump. This is the fraction of electricity used in the building. Important to take this into account when running the optimization. @BhargavaKrishnaSreepathi

**Pull request merged**
