### PR TITLE
Remove abort from exception handling

### LINKED ISSUE #2911: refactor cea/interfaces/dashboard/api/inputs.py to display relavent errors
it seems like the errors that are showing are not relevant to the actual problem.
see examples in #2906
we are hoping that refactoring could help

### PR DESCRIPTION
**Pull request by reyery**
This PR resolves #2911 by cleaning up how error handling is done during processing network type files.

Hopefully this helps with #2906 as well

Testing
-
Start `cea dashboard` in console first before opening GUI
Try opening a scenario input editor with/without `streets.shp`
Delete `streets.prj` file and open input editor. Input editor should still open but the error will be shown in the console.

### CODE REVIEW

**Comment by shanshanhsieh** [comment]
when opening a scenario without `streets.shp`, i got this:
```
C:\Users\Shanshan\Documents\CEA-Projects\altstetten\8048_i2913_2\inputs\networks\streets.shp: No such file or directory
```
when i tried to open a scenario without `streets.prj`, i got this:
```
Traceback (most recent call last):
  File "c:\users\shanshan\documents\cityenergyanalyst_py3\cityenergyanalyst\cea\interfaces\dashboard\api\inputs.py", line 311, in df_to_json
    lat, lon = get_lat_lon_projected_shapefile(table_df)
  File "c:\users\shanshan\documents\cityenergyanalyst_py3\cityenergyanalyst\cea\utilities\standardize_coordinates.py", line 68, in get_lat_lon_projected_shapefile
    data = data.to_crs(get_geographic_coordinate_system())
  File "C:\Users\Shanshan\Documents\CityEnergyAnalyst_py3\Dependencies\Python\lib\site-packages\geopandas\geodataframe.py", line 816, in to_crs
    geom = df.geometry.to_crs(crs=crs, epsg=epsg)
  File "C:\Users\Shanshan\Documents\CityEnergyAnalyst_py3\Dependencies\Python\lib\site-packages\geopandas\geoseries.py", line 527, in to_crs
    "Cannot transform naive geometries.  "
ValueError: Cannot transform naive geometries.  Please set a crs on the object first.
```

i think these are the expected behaviors, can you confirm, @reyery ?

maybe @nasty-bos could try opening the corrunpted altstetten case again?

**Comment by nasty-bos** [comment]
I opened the corrupted case study and got exactly the same error as @shanshanhsieh.

```
Traceback (most recent call last):                                                                                                                             
  File "c:\users\abosova\documents\cityenergyanalyst\cityenergyanalyst\cea\interfaces\dashboard\api\inputs.py", line 311, in df_to_json                        
    lat, lon = get_lat_lon_projected_shapefile(table_df)                                                                                                       
  File "c:\users\abosova\documents\cityenergyanalyst\cityenergyanalyst\cea\utilities\standardize_coordinates.py", line 68, in get_lat_lon_projected_shapefile  
    data = data.to_crs(get_geographic_coordinate_system())                                                                                                     
  File "C:\Users\abosova\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\geopandas\geodataframe.py", line 816, in to_crs                     
    geom = df.geometry.to_crs(crs=crs, epsg=epsg)                                                                                                              
  File "C:\Users\abosova\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\geopandas\geoseries.py", line 527, in to_crs                        
    "Cannot transform naive geometries.  "                                                                                                                     
ValueError: Cannot transform naive geometries.  Please set a crs on the object first.                                                                          
           
```

**Comment by reyery** [comment]
@shanshanhsieh I can confirm it's expected behavior. The console will still try print out the stack trace if there are any errors opening files so that we can debug any errors in the future. CEA will still send over the other working files to the GUI to ensure that the input editor is still working.

However, even though this solves the problem regarding opening the scenario in the input editor, it does not exactly solve the source of the problem I think. That error still implies that there is something wrong with the streets file, more specifically the projection system, i.e. `crs`. There might be a script that is modifying it somehow. Not being able to reproduce this error consistently makes it difficult to find the source of this issue.

**Comment by shanshanhsieh** [comment]
okay, merging this PR now.
we will continue logging the errors observed in the corrupted case that @nasty-bos has in #2906.

**Pull request merged**
