### PR TITLE
I2182 read occupancy schedules

### PR DESCRIPTION
**Pull request by gabriel-happle**
This addresses issue #2182.
As discussed with @daren-thomas, the first step towards user defined occupancy schedules, is to make the occupancy model read (user-defined) schedules without changing too much of the code.
This PR does exactly this.
- during execution of the demand calculation it checks if there is a file `{building_name}_schedules.csv` is present in `inputs/building_properties`.
- if yes, it will import these schedules for the calculation
- if not, it will create the schedules with @martin-mosteiro's occupancy model and save them to a csv file

This file could then be modified by the user (in excel) for a second run or for other scenarios (before we have more sophisticated tools).

How to test:
(1) run the demand of any scenario -> the script should create schedule files in your input folder
(2) keep some of the files and delete others
(3) re-run the demand -> now the script should only create the missing files

### CODE REVIEW

**Comment by daren-thomas** [comment]
@gabriel-happle I'm getting the following error when running `cea test` on this branch:

```
======================================================================
FAIL: test_calc_thermal_loads (test_calc_thermal_loads.TestCalcThermalLoads)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\tests\test_calc_thermal_loads.py", line 74, in test_calc_thermal_loads
    column, values[i], df[column].sum()), places=3)
AssertionError: Sum of column E_sys_kWh differs, 330605.132000 != 275292.425000

======================================================================
FAIL: test_calc_thermal_loads_other_buildings (test_calc_thermal_loads.TestCalcThermalLoads)
Test some other buildings just to make sure we have the proper data
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\tests\test_calc_thermal_loads.py", line 97, in test_calc_thermal_loads_other_buildings
    places=3)
AssertionError: qhs_sys_kwh for B01 should be: 189364.75900, was 163960.51000
```

**Comment by gabriel-happle** [comment]
@daren-thomas yes, I'm getting the same error.
Maybe I have messed up the testing script. I'm trying to figure out what is happening. Any help is appreciated.
This is NOT supposed to change the results.
When I run the `reference-case-open` with my branch and with the master, the resulting spreadsheets are identical. As they should be.

**Comment by gabriel-happle** [comment]
@daren-thomas this PR is failing the tests, because the testing functions share some data in the temp folder.
Specifically, the newly created schedule files.
To change this, is a bit too high level for me. I need to ask for your help.
This is what I have figured out:
- nosetest `test_calc_thermal_loads.test_calc_thermal_loads` individually passes
- nosetest `test_calc_thermal_loads.test_calc_thermal_loads_other_buildings` individually passes
- nosetest `test_calc_thermal_loads` (both functions) passes the first test, fails the second -> reference case is extracted only once
- `dodo` fails both tests -> calibration  and sensitivity are tested prior on the same reference case

To avoid this, I think we need to unpack the reference case newly for all tests.
For that, maybe we have to split up the `test_calc_thermal_loads` into two scripts (two classes).

**Comment by daren-thomas** [comment]
@gabriel-happle, adding the following method to the class `TestCalcThermalLoads` let's the code run through:

```
    def tearDown(self):
        """Remove schedule files created by previous runs"""
        for building in self.locator.get_zone_building_names():
            if os.path.exists(self.locator.get_building_schedules(building)):
                os.remove(self.locator.get_building_schedules(building))
```

But here's the rub: Why doesn't it work if the schedules are already there? This leads me to assume that the schedules saved/loaded are not the same as those computed?

Also, looking at the schedules file, I noticed there is no column for the hour - I think it would be good to add that.

**Comment by daren-thomas** [comment]
also, note that `test_schedules.py` doesn't work either.

**Comment by daren-thomas** [comment]
@gabriel-happle I added a test (`cea.tests.test_schedules.TestSavingLoadingSchedules#test_get_building_schedules`) that runs `get_building_schedules` twice on the same reference case, deleting the generated .csv file before the first run (if it exists). That way, we get two dicts that are supposed to be exactly the same. They're not. This means `get_building_schedules` does not produce the same results when reading from disk than when creating the schedules normally... and that explains why the thermal loads tests are failing too. You'll need to fix this first.

**Comment by daren-thomas** [comment]
@gabriel-happle it's rounding errors... 

```
EqualsAssertionError:  :: 236.7224963019687 != 236.72249630196868
```

**Comment by gabriel-happle** [comment]
@daren-thomas Thanks a lot. I think rounded values is a good idea. It will have the nice side effect of making the files smaller.

**Comment by gabriel-happle** [comment]
@daren-thomas we also need rounding during the reading. Apparently, when reading files and converting to numpy arrays there might be decimals added again.

**Comment by gabriel-happle** [comment]
> 
> 
> @gabriel-happle, adding the following method to the class `TestCalcThermalLoads` let's the code run through:
> 
> ```
>     def tearDown(self):
>         """Remove schedule files created by previous runs"""
>         for building in self.locator.get_zone_building_names():
>             if os.path.exists(self.locator.get_building_schedules(building)):
>                 os.remove(self.locator.get_building_schedules(building))
> ```
> 
> But here's the rub: Why doesn't it work if the schedules are already there? This leads me to assume that the schedules saved/loaded are not the same as those computed?
> 
> Also, looking at the schedules file, I noticed there is no column for the hour - I think it would be good to add that.

hmm. OK. The hour is very straightforward. you can just look at the column in excel. What would be more informative maybe, would be the hour of the day and the type of day (Saturday, Sunday, Monday, etc.) plus the date and month.
Should we add the `date_range` timestamp directly?

**Comment by gabriel-happle** [comment]
Results of `test_calc_thermal_loads()` with different rounding of schedules
15 decimals: `AssertionError: Sum of column E_sys_kWh differs, 330605.132000 != 330605.141000`
10 decimals: `AssertionError: Sum of column E_sys_kWh differs, 330605.132000 != 330766.426000`
5 decimals: `AssertionError: Sum of column E_sys_kWh differs, 330605.132000 != 333157.804000`

The changes in results introduced by rounding to 5 decimals remain smaller than 1% of annual energy demand. Therefore I'm choosing to update the thermal loads' test results.

image
image
image
image

**Comment by gabriel-happle** [comment]
@daren-thomas, so the last problem we have is, that apparently unittests and sensitivity/calibration tests are sharing data when executed in sequence.

I changed the sequence in the config:
```
[test]
reference-cases = open
tasks = run_unit_tests, run_calibration
verbosity = 1
```

- unit tests after calibration:
```
C:\Users\Gabriel\Documents\CityEnergyAnalyst\Dependencies\Python\python.exe C:/Users/Gabriel/Documents/CityEnergyAnalyst/CityEnergyAnalyst/cea/tests/dodo.py
Configuring task run_calibration
Configuring task run_unit_tests
.  run_calibration
Only 100 samples in chain.
Sequential sampling (2 chains in 1 job)
CompoundStep
>Metropolis: [sigma]
>Metropolis: [var6]
>Metropolis: [var5]
>Metropolis: [var4]
>Metropolis: [var3]
>Metropolis: [var2]
>Metropolis: [var1]
100%|##########| 1100/1100 [00:05<00:00, 184.63it/s]
100%|##########| 1100/1100 [00:05<00:00, 213.72it/s]
The number of effective samples is smaller than 25% for some parameters.
.  run_unit_tests
FF.........................
======================================================================
FAIL: test_calc_thermal_loads (test_calc_thermal_loads.TestCalcThermalLoads)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\Gabriel\Documents\CityEnergyAnalyst\CityEnergyAnalyst\cea\tests\test_calc_thermal_loads.py", line 73, in test_calc_thermal_loads
    column, values[i], df[column].sum()), places=3)
AssertionError: Sum of column E_sys_kWh differs, 333157.804000 != 275332.064000

======================================================================
FAIL: test_calc_thermal_loads_other_buildings (test_calc_thermal_loads.TestCalcThermalLoads)
Test some other buildings just to make sure we have the proper data
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\Gabriel\Documents\CityEnergyAnalyst\CityEnergyAnalyst\cea\tests\test_calc_thermal_loads.py", line 96, in test_calc_thermal_loads_other_buildings
    places=3)
AssertionError: qhs_sys_kwh for B01 should be: 189417.63200, was 164227.41300

----------------------------------------------------------------------
Ran 27 tests in 50.179s

FAILED (failures=2)
########################################
TaskFailed - taskid:run_unit_tests
Python Task failed: '<function run_unit_tests at 0x000000000445E048>' returned False

read input files
done
Schedules for building B01 detected. Using these schedules.
Schedules for building B01 detected. Using these schedules.
Running demand calculation for scenario c:\users\gabriel\appdata\local\temp\reference-case-open\baseline
Running demand calculation with weather file C:\Users\Gabriel\Documents\CityEnergyAnalyst\CityEnergyAnalyst\cea\databases\weather\Zug.epw
Running demand calculation with dynamic infiltration=False
Running demand calculation with multiprocessing=True
Running demand calculation with stochastic occupancy=False
(6192.0, 3216.0)
read input files
done
No schedules detected for building B01. Creating schedules from archetypes database
Saving schedules for building B01 to inputs/building-properties directory.
Schedules for building B01 detected. Using these schedules.
read input files
done



Process finished with exit code 1
```

- unit tests before calibration
```
C:\Users\Gabriel\Documents\CityEnergyAnalyst\Dependencies\Python\python.exe C:/Users/Gabriel/Documents/CityEnergyAnalyst/CityEnergyAnalyst/cea/tests/dodo.py
Configuring task run_unit_tests
Configuring task run_calibration
.  run_unit_tests
...........................
----------------------------------------------------------------------
Ran 27 tests in 108.283s

OK
.  run_calibration
Only 100 samples in chain.
Sequential sampling (2 chains in 1 job)
CompoundStep
>Metropolis: [sigma]
>Metropolis: [var6]
>Metropolis: [var5]
>Metropolis: [var4]
>Metropolis: [var3]
>Metropolis: [var2]
>Metropolis: [var1]
100%|##########| 1100/1100 [00:05<00:00, 210.97it/s]
100%|##########| 1100/1100 [00:04<00:00, 235.80it/s]
The gelman-rubin statistic is larger than 1.05 for some parameters. This indicates slight problems during sampling.
The number of effective samples is smaller than 10% for some parameters.

Process finished with exit code 0
```

**Comment by daren-thomas** [comment]
I removed the functionality of only extracting the reference-case once per run. This adds 2 seconds each time we create such an InputLocator, but I think it's better than the headache of having state left over from other tests. Thank you for tracking this down. I'll merge as soon as the Jenkins is happy :)

**Pull request merged**
