### PR TITLE
I1073 stochastic

### PR DESCRIPTION
**Pull request by martin-mosteiro**
This PR adds the option to use stochastic occupancy based on the model by Page et al. (2007). The stochastic model affects the number of people in the building, the humidity and heat gains, and the ventilation required. Since the CEA calculation for electricity and water demand does not depend on the number of people in the building, these are *not* affected by the stochastic model.

In order to be able to choose between a deterministic or stochastic occupancy modeling, a new variable ('use-stochastic-occupancy') was added to the config file. The default value for this variable is set to False.

### CODE REVIEW

**Comment by JIMENOFONSECA** [comment]
@martin-mosteiro about your comment:
"Since the CEA calculation for electricity and water demand does not depend on the number of people in the building, these are not affected by the stochastic model."

I think the electricity and water demand depend on people in CEA.

**Comment by martin-mosteiro** [comment]
@JIMENOFONSECA they don't, they are just taken from the electricity schedules in the database.

**Comment by martin-mosteiro** [comment]
All tests passed on my computer, but I didn't run the tests after merging from master, now the tests do not pass due to the following:
```
======================================================================
ERROR: test_calc_thermal_loads_other_buildings (test_calc_thermal_loads.TestCalcThermalLoads)
Test some other buildings just to make sure we have the proper data
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\User\Documents\GitHub\CityEnergyAnalyst\cea\tests\test_calc_thermal_loads.py", line 97, in test_calc_thermal_loads_other_buildings
    self.format_output)
  File "C:\Users\User\Documents\GitHub\CityEnergyAnalyst\cea\tests\test_calc_thermal_loads.py", line 113, in run_for_single_building
    massflows_output, temperatures_output, format_output)
  File "C:\Users\User\Documents\GitHub\CityEnergyAnalyst\cea\demand\thermal_loads.py", line 207, in calc_thermal_loads
    writer.results_to_csv(tsd, bpr, locator, date, building_name)
  File "C:\Users\User\Documents\GitHub\CityEnergyAnalyst\cea\demand\demand_writers.py", line 79, in results_to_csv
    columns, hourly_data = self.calc_hourly_dataframe(building_name, date, tsd)
  File "C:\Users\User\Documents\GitHub\CityEnergyAnalyst\cea\demand\demand_writers.py", line 105, in calc_hourly_dataframe
    data = dict((x + '_kWh', np.nan_to_num(tsd[x]) / 1000) for x in self.load_vars)  # TODO: convert nan to num at the very end.
  File "C:\Users\User\Documents\GitHub\CityEnergyAnalyst\cea\demand\demand_writers.py", line 105, in <genexpr>
    data = dict((x + '_kWh', np.nan_to_num(tsd[x]) / 1000) for x in self.load_vars)  # TODO: convert nan to num at the very end.
KeyError: 'Qhsf_shu'
```
I will look into this.

**Comment by JIMENOFONSECA** [comment]
@gabriel-happle would you mind testing this? thanks!

**Comment by martin-mosteiro** [comment]
@gabriel-happle I updated the documentation as requested
@JIMENOFONSECA If everything is otherwise okay, this PR is ready to be merged

**Pull request merged**
