### PR TITLE
Bugfix around GDF-completion

### PR DESCRIPTION
**Pull request by MatNif**
Check if the hard coded headers-list of columns that are  critical columns actually appear in the OSM GeoDataFrame for a given zone.

### CODE REVIEW

**Comment by lguilhermers** [comment]
```
Traceback (most recent call last):
  File "c:\users\luis.santos\documents\cityenergyanalyst\cityenergyanalyst\cea\interfaces\dashboard\api\project.py", line 176, in post
    cea.api.zone_helper(config)
  File "c:\users\luis.santos\documents\cityenergyanalyst\cityenergyanalyst\cea\api.py", line 60, in __call__
    self._runner.__call__(*args, **kwargs)
  File "c:\users\luis.santos\documents\cityenergyanalyst\cityenergyanalyst\cea\api.py", line 38, in script_runner
    script_module.main(config)
  File "c:\users\luis.santos\documents\cityenergyanalyst\cityenergyanalyst\cea\datamanagement\zone_helper.py", line 525, in main
    zone_helper(locator, config)
  File "c:\users\luis.santos\documents\cityenergyanalyst\cityenergyanalyst\cea\datamanagement\zone_helper.py", line 306, in zone_helper
    calculate_typology_file(locator, zone_df, year_construction, occupancy_type, typology_output_path)
  File "c:\users\luis.santos\documents\cityenergyanalyst\cityenergyanalyst\cea\datamanagement\zone_helper.py", line 334, in calculate_typology_file
    typology_df = calculate_age(zone_df, year_construction)
  File "c:\users\luis.santos\documents\cityenergyanalyst\cityenergyanalyst\cea\datamanagement\zone_helper.py", line 419, in calculate_age
    data_osm_floors_joined = int(math.ceil(np.nanmedian(data_age)))  # median so we get close to the worse case
ValueError: cannot convert float NaN to integer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\luis.santos\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\luis.santos\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\luis.santos\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\flask_restx\api.py", line 405, in wrapper
    resp = resource(*args, **kwargs)
  File "C:\Users\luis.santos\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\flask\views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "C:\Users\luis.santos\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\flask_restx\resource.py", line 46, in dispatch_request
    resp = meth(*args, **kwargs)
  File "c:\users\luis.santos\documents\cityenergyanalyst\cityenergyanalyst\cea\interfaces\dashboard\api\project.py", line 186, in post
    raise Exception(f'{tool}_helper: {e}') from e
Exception: zone_helper: cannot convert float NaN to integer
```

I still get this error when trying to create a scenario (both in this PR and in the master branch).
I think it is better to leave this branch open until this is fixed.

**Comment by lguilhermers** [comment]
```
Traceback (most recent call last):
  File "C:\Users\luis.santos\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\pandas\core\indexes\range.py", line 385, in get_loc
    return self._range.index(new_key)
ValueError: 0 is not in range

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\users\luis.santos\documents\cityenergyanalyst\cityenergyanalyst\cea\interfaces\dashboard\api\project.py", line 176, in post
    cea.api.zone_helper(config)
  File "c:\users\luis.santos\documents\cityenergyanalyst\cityenergyanalyst\cea\api.py", line 60, in __call__
    self._runner.__call__(*args, **kwargs)
  File "c:\users\luis.santos\documents\cityenergyanalyst\cityenergyanalyst\cea\api.py", line 38, in script_runner
    script_module.main(config)
  File "c:\users\luis.santos\documents\cityenergyanalyst\cityenergyanalyst\cea\datamanagement\zone_helper.py", line 525, in main
    zone_helper(locator, config)
  File "c:\users\luis.santos\documents\cityenergyanalyst\cityenergyanalyst\cea\datamanagement\zone_helper.py", line 306, in zone_helper
    calculate_typology_file(locator, zone_df, year_construction, occupancy_type, typology_output_path)
  File "c:\users\luis.santos\documents\cityenergyanalyst\cityenergyanalyst\cea\datamanagement\zone_helper.py", line 365, in calculate_typology_file
    typology_df.loc[~typology_df['1ST_USE'].isin(['NONE', 'PARKING']), '1ST_USE'].mode()[0]
  File "C:\Users\luis.santos\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\pandas\core\series.py", line 958, in __getitem__
    return self._get_value(key)
  File "C:\Users\luis.santos\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\pandas\core\series.py", line 1069, in _get_value
    loc = self.index.get_loc(label)
  File "C:\Users\luis.santos\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\pandas\core\indexes\range.py", line 387, in get_loc
    raise KeyError(key) from err
KeyError: 0

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\luis.santos\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\luis.santos\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\luis.santos\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\flask_restx\api.py", line 405, in wrapper
    resp = resource(*args, **kwargs)
  File "C:\Users\luis.santos\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\flask\views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "C:\Users\luis.santos\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\flask_restx\resource.py", line 46, in dispatch_request
    resp = meth(*args, **kwargs)
  File "c:\users\luis.santos\documents\cityenergyanalyst\cityenergyanalyst\cea\interfaces\dashboard\api\project.py", line 186, in post
    raise Exception(f'{tool}_helper: {e}') from e
Exception: zone_helper: 0
```
Other location (in cbd) is giving this error

**Comment by lguilhermers** [comment]
I am being able to create scenarios without any problems when I am using this branch, I think it can be merged into master.

**Review by lguilhermers — APPROVED** [review]

**Comment by martin-mosteiro** [comment]
Thanks @MatNif for this fix. I won't have time to review this PR in the coming days, but if @lguilhermers tested it and it works I think you can just merge.

**Comment by MatNif** [comment]
> Thanks @MatNif for this fix. Some of the checks appear not to be successful? I won't have time to review this PR in the coming days, so @lguilhermers approves the PR, then you can just merge once the tests pass.

Yeah, @lguilhermers I think you can merge it now. Had to make an update from master to include the latest changes to the interaction with the conda environment. So now, the Github tests finally run successfully. The fact the Jenkins-test fails is expected, since the conda environment has not yet been updated on it.

**Pull request merged**
