### PR TITLE
2477 wrong column name in piping catalog

### LINKED ISSUE #2477: Wrong column name in the piping catalog (cooling)
when running `cea workflow` for `cooling`
the process is stuck at thermal network calculation:
```
KeyError: (u'the label [Code] is not in the [index]', u'occurred at index PIPE0')
```

This is because the column names in the piping catalog do not contain `Code`

To solve this issue:
The column name `Description` should be replaced by `Code`

### PR DESCRIPTION
**Pull request by shanshanhsieh**
this PR resolves #2477 the correct column name is updated

to test:
1. run `cea workflow` for `district-cooling-systems`

### CODE REVIEW

**Comment by daren-thomas** [comment]
@shanshanhsieh running the workflow as I type this. I'll get back to you with results and merge when done.

**Comment by gabriel-happle** [comment]
after updating the mysterious function name the workflow runs through.
Thanks @reyery for the detective work.

**Comment by gabriel-happle** [comment]
@shanshanhsieh workflow for heating is also running

**Comment by shanshanhsieh** [comment]
@daren, both heating and cooling workflows ran through from my machine.
please merge this branch once the tests are passed from your side.

**Comment by daren-thomas** [comment]
@shanshanhsieh I'm having a problem with the cooling workflow: It stops at the optimization step with `AttributeError: 'module' object has no attribute 'uniform_reference_points'`. I'm restarting it again just to make sure. Please don't merge yet.

**Comment by shanshanhsieh** [comment]
@daren-thomas yes, we will only merge if that pass the test from your side
in both machine we tested, cea 2.26 is installed

**Comment by daren-thomas** [comment]
@shanshanhsieh I'm having a problem with the cooling workflow: It stops at the optimization step with `AttributeError: 'module' object has no attribute 'uniform_reference_points'`. I'm restarting it again just to make sure. Please don't merge yet.

**Comment by daren-thomas** [comment]
@shanshanhsieh confirmed: it doesn't work. blocks in the optimization step.

**Comment by shanshanhsieh** [comment]
@daren-thomas please update your `deap` to v1.3.0 and try again

**Comment by daren-thomas** [comment]
Updating `deap` did the trick! Thanks for the tip! merging :)

**Pull request merged**
