### PR TITLE
Remove brackets from `sheet_name` instances

### PR DESCRIPTION
**Pull request by martin-mosteiro**
There were a number of instances of `pd.read_excel(file_path, sheet_name=['sheet_name'])['sheet_name']`. This is unnecessarily complicated and it creates issues when running on Euler, so they have been changed to `pd.read_excel(file_path, sheet_name='sheet_name')`

### CODE REVIEW

**Comment by martin-mosteiro** [comment]
@daren-thomas You can test this by running `thermal_network.py` - if the simulation starts (i.e., the time steps start to be printed out), then the script is working as expected.

This should be tested both locally (to make sure that it's still reading the right information) and remotely on Euler (to make sure the `KeyError` issue is solved)

**Comment by martin-mosteiro** [comment]
Cannot test on Euler due to issue #2064. The specific changes can alternatively be tested indirectly by running python on, doing `pd.read_excel(file_path, sheet_name='sheet_name')` and comparing the results when running on python locally.

The dataframes produced are the same.

**Comment by martin-mosteiro** [comment]
@daren-thomas Removing the contrived way that line was written worked locally, but it didn't solve the issue on Euler. So I had to change `sheet_name` to the deprecated `sheetname`, which creates a warning (`C:\ProgramData\Miniconda2\envs\cea\lib\site-packages\pandas\io\excel.py:329: FutureWarning: The `sheetname` keyword is deprecated, use `sheet_name` instead
  **kwds)`) but still works both locally and on Euler, while `sheet_name` is not recognized on Euler.

**Comment by martin-mosteiro** [comment]
The tests described above pass both locally and on Euler.

1. Running the original code `pd.read_excel(locator.get_thermal_networks(), sheet_name=['MATERIAL PROPERTIES'])['MATERIAL PROPERTIES']` produces
```
       material code  lambda_WmK  rho_kgm3  Cp_JkgK
0         Steel   T1      76.000      8930      480
1          Soil   T2       1.600      1600     2000
2  Polyethylene   T3       0.430       940     1800
3           PUR   T4       0.023        60     1500
4           PEX   T5       0.380       938      550
```

2. Running that same line on Euler produces:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/cluster/apps/python/2.7.14/x86_64/lib64/python2.7/site-packages/pandas/core/frame.py", line 1964, in __getitem__
    return self._getitem_column(key)
  File "/cluster/apps/python/2.7.14/x86_64/lib64/python2.7/site-packages/pandas/core/frame.py", line 1971, in _getitem_column
    return self._get_item_cache(key)
  File "/cluster/apps/python/2.7.14/x86_64/lib64/python2.7/site-packages/pandas/core/generic.py", line 1645, in _get_item_cache
    values = self._data.get(item)
  File "/cluster/apps/python/2.7.14/x86_64/lib64/python2.7/site-packages/pandas/core/internals.py", line 3590, in get
    loc = self.items.get_loc(item)
  File "/cluster/apps/python/2.7.14/x86_64/lib64/python2.7/site-packages/pandas/core/indexes/base.py", line 2444, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 132, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 154, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1210, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1218, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'MATERIAL PROPERTIES'
```

3. Running the new line `pd.read_excel(locator.get_thermal_networks(), sheetname='MATERIAL PROPERTIES')` produces:
```
       material code  lambda_WmK  rho_kgm3  Cp_JkgK
0         Steel   T1      76.000      8930      480
1          Soil   T2       1.600      1600     2000
2  Polyethylene   T3       0.430       940     1800
3           PUR   T4       0.023        60     1500
4           PEX   T5       0.380       938      550
```

4. Running that same line on Euler produces:
```
       material code  lambda_WmK  rho_kgm3  Cp_JkgK
0         Steel   T1      76.000      8930      480
1          Soil   T2       1.600      1600     2000
2  Polyethylene   T3       0.430       940     1800
3           PUR   T4       0.023        60     1500
4           PEX   T5       0.380       938      550
```

i.e., 1, 3 and 4 all produce the desired result, 2 produces a `KeyError`.

**Comment by martin-mosteiro** [comment]
@daren-thomas Seems like Jenkins is having a booboo again:
```
GitHub pull request #2059 of commit 48a1e38e6ae82c8d2bf70a1b698bdf4f736ee3e4, no merge conflicts.
Setting status of 48a1e38e6ae82c8d2bf70a1b698bdf4f736ee3e4 to PENDING with url https://ceajenkins.ngrok.io/job/run%20cea%20test%20for%20pull%20requests/1653/ and message: 'Build started for merge commit.'
Building in workspace C:\Program Files (x86)\Jenkins\workspace\run cea test for pull requests
[WS-CLEANUP] Deleting project workspace...
[WS-CLEANUP] Deferred wipeout is used...
ERROR: [WS-CLEANUP] Cannot delete workspace: Unable to delete 'C:\Program Files (x86)\Jenkins\workspace\run cea test for pull requests'. Tried 3 times (of a maximum of 3) waiting 0.1 sec between attempts.
ERROR: Cannot delete workspace: Unable to delete 'C:\Program Files (x86)\Jenkins\workspace\run cea test for pull requests'. Tried 3 times (of a maximum of 3) waiting 0.1 sec between attempts.
Setting status of 48a1e38e6ae82c8d2bf70a1b698bdf4f736ee3e4 to FAILURE with url https://ceajenkins.ngrok.io/job/run%20cea%20test%20for%20pull%20requests/1653/ and message: 'Build finished. '
Finished: FAILURE
```

**Comment by daren-thomas** [comment]
@martin-mosteiro i'm rebooting (and updating). let's see if that helps.

**Pull request merged**
