### PR TITLE
1684 test supply system and optimization

### PR DESCRIPTION
**Pull request by daren-thomas**
This PR implements the script `cea cooling-case-workflow` (see `cea/tests/cooling_case_workflow.py`) which runs through a whole cooling-case workflow of the cea exercising all the cea scripts for a cooling case.

It will create a new folder with current date and time in your temp folder and extract the cooling case there. You can restart a failed run by running `cea cooling-case-workflow --scenario PATH_TO_THE_COOLING_CASE_SCENARIO` - it saves a copy of the config file to that folder which includes a variable `cooling-case-workflow:last`, an index into the scripts to run, so it can pick up where it dropped off (assuming, you fixed the problem).

### CODE REVIEW

**Comment by JIMENOFONSECA** [comment]
@shanshanhsieh I assign this to you since this is connected to your work?

**Comment by shanshanhsieh** [comment]
Hi Daren, 
i tried to run `cea/tests/cooling_case_workflow.py` from Pycharm, and it is stuck at daysim
"""
Generating geometry for building B010
burning building  B010
Sending the scene: geometry and materials to daysim
	radiation_main: rad.base_file_path: c:\users\shanshan\appdata\local\temp\default_materials.rad
	radiation_main: rad.data_folder_path: c:\users\shanshan\appdata\local\temp
	radiation_main: rad.command_file: c:\users\shanshan\appdata\local\temp\command.txt
	radiation_main: rad.rad_file_path: c:\users\shanshan\appdata\local\temp\geometry.rad
Traceback (most recent call last):
isolation_daysim: daysim_dir=c:\users\shanshan\appdata\local\temp\temp0
  File "C:/Users/Shanshan/Documents/GitHub/CityEnergyAnalyst/cea/tests/cooling_case_workflow.py", line 92, in <module>
    main(cea.config.Configuration())
  File "C:/Users/Shanshan/Documents/GitHub/CityEnergyAnalyst/cea/tests/cooling_case_workflow.py", line 82, in main
    run(script, **kwargs)
  File "C:/Users/Shanshan/Documents/GitHub/CityEnergyAnalyst/cea/tests/cooling_case_workflow.py", line 50, in run
    f(config=config, **kwargs)
  File "C:\Users\Shanshan\Documents\GitHub\CityEnergyAnalyst\cea\api.py", line 27, in script_runner
    script_module.main(config)
  File "C:\Users\Shanshan\Documents\GitHub\CityEnergyAnalyst\cea\resources\radiation_daysim\radiation_main.py", line 216, in main
    radiation_singleprocessing(rad, geometry_3D_zone, locator, config.weather, settings)
  File "C:\Users\Shanshan\Documents\GitHub\CityEnergyAnalyst\cea\resources\radiation_daysim\radiation_main.py", line 165, in radiation_singleprocessing
    daysim_main.isolation_daysim(chunk_n, rad, building_dict, locator, weather_path, settings)
  File "C:\Users\Shanshan\Documents\GitHub\CityEnergyAnalyst\cea\resources\radiation_daysim\daysim_main.py", line 132, in isolation_daysim
    rad.initialise_daysim(daysim_dir, os.path.join(settings.daysim_bin_directory, ''))
TypeError: initialise_daysim() takes exactly 2 arguments (3 given)

Process finished with exit code 1



"""

**Comment by shanshanhsieh** [comment]
also tried to run the script from the command line by doing `cea cooling-case-workflow`, but it is not recognizing this command. maybe i am not doing it properly.
could you please give me the steps to test this PR? e.g. should the old config be deleted before running the scrips? and what files to check?
thank you!

**Comment by daren-thomas** [comment]
hi @shanshanhsieh I think you're using an old version of py4design. maybe a `pip install -U --no-cache py4design` could help?

**Comment by shanshanhsieh** [comment]
Hi @daren-thomas ,
The script ran all the way until optimization, and some errors occurred.
These are the folders that were created in the `optimization folder`, it seems like the `decentralized` and `substations` folders are completed, but the `network` folder is uncompleted. 
image

And here is the error message that was repeated:
```
ConfigParser.ParsingError: File contains parsing errors: C:\Users\Zhongming/cea.config
	[line 325]: '= 0\n'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Zhongming\Anaconda2\envs\cea\lib\multiprocessing\forking.py", line 380, in main
    prepare(preparation_data)
  File "C:\Users\Zhongming\Anaconda2\envs\cea\lib\multiprocessing\forking.py", line 510, in prepare
    '__parents_main__', file, path_name, etc
  File "C:\Users\Zhongming\Documents\Github\CityEnergyAnalyst\cea\tests\cooling_case_workflow.py", line 12, in <module>
    import cea.api
  File "C:\Users\Zhongming\Documents\Github\CityEnergyAnalyst\cea\api.py", line 35, in <module>
    register_scripts()
  File "C:\Users\Zhongming\Documents\Github\CityEnergyAnalyst\cea\api.py", line 13, in register_scripts
    config = cea.config.Configuration()
  File "C:\Users\Zhongming\Documents\Github\CityEnergyAnalyst\cea\config.py", line 34, in __init__
    self.user_config.read([DEFAULT_CONFIG, config_file])
  File "C:\Users\Zhongming\Anaconda2\envs\cea\lib\ConfigParser.py", line 305, in read
    self._read(fp, filename)
  File "C:\Users\Zhongming\Anaconda2\envs\cea\lib\ConfigParser.py", line 546, in _read
    raise e
ConfigParser.ParsingError: File contains parsing errors: C:\Users\Zhongming/cea.config
	[line 325]: '= 0\n'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Zhongming\Anaconda2\envs\cea\lib\multiprocessing\forking.py", line 380, in main
    prepare(preparation_data)
  File "C:\Users\Zhongming\Anaconda2\envs\cea\lib\multiprocessing\forking.py", line 510, in prepare
    '__parents_main__', file, path_name, etc
  File "C:\Users\Zhongming\Documents\Github\CityEnergyAnalyst\cea\tests\cooling_case_workflow.py", line 12, in <module>
    import cea.api
  File "C:\Users\Zhongming\Documents\Github\CityEnergyAnalyst\cea\api.py", line 35, in <module>
    register_scripts()
  File "C:\Users\Zhongming\Documents\Github\CityEnergyAnalyst\cea\api.py", line 13, in register_scripts
    config = cea.config.Configuration()
  File "C:\Users\Zhongming\Documents\Github\CityEnergyAnalyst\cea\config.py", line 34, in __init__
    self.user_config.read([DEFAULT_CONFIG, config_file])
  File "C:\Users\Zhongming\Anaconda2\envs\cea\lib\ConfigParser.py", line 305, in read
    self._read(fp, filename)
  File "C:\Users\Zhongming\Anaconda2\envs\cea\lib\ConfigParser.py", line 546, in _read
    raise e
```

**Comment by shanshanhsieh** [comment]
on the other hand, i had to add this line after updating from master in order to set the region for datahelper. hope that's not why it crashed...
image

**Comment by shanshanhsieh** [comment]
Hi @daren-thomas ,
you can ignore the previous comment, because that was solved by renewing `cea.config`
and now i am able to proceed until the end of `thermal-network-optimization`
will keep you updated!

**Comment by shanshanhsieh** [comment]
Hi @daren-thomas , 
i am not able to run `cea plots-supply-system`

it seems like the function`preprocessing_generation_data` in `cea\plots\supply_system\main.py` is not updated with the new names
i tried to compare it with `preprocessing_generation_data` in  `cea\analysis\multicriteria\main.py`, and update the column names, but they are not exactly the same

was this script running for you?

**Comment by daren-thomas** [comment]
@shanshanhsieh not sure - I tried to run the workflow all the way through, but my computer went to sleep over the weekend. We're still not on speaking terms, PC and I...

So... I can't really tell how far I'd get with the simulations. Thank you for updating with the `config.data_helper.region` thing. That got overlooked in the big refactoring (or maybe it just wasn't part of the branch that got refactored...

So... The way I see it is this: The workflow itself works. But the code doesn't run through. Which is kind of a win in the sense that that is what the workflow is designed to find out, right? To check if all the simulations will run through if run in order?

Do we merge? Is `cea\plots\supply_system\main.py` changed at all by this PR? I don't think so, right?

**Comment by daren-thomas** [comment]
@shanshanhsieh - could the `cea plots-supply-system` issue be a separate issue? if you think it is, I'd very much appreciate if you created an issue on GitHub, maybe along with some additional info for debugging.

**Comment by shanshanhsieh** [comment]
hey @daren-thomas , the testing is finished. 
I commented the line that runs the supply system plot, and added some more config settings to make the workflow cohesive. (matching generation numbers from optimization with the plots)

this branch is ready to be merged once it's updated from master!

**Pull request merged**
