### PR TITLE
Update CEA installation for Mac

### PR DESCRIPTION
**Pull request by reyery**
Notable Changes:
- Updated Daysim binaries in repo to Universal App to support both Intel and Apple silicon macs natively.
- Updated mac install docs. Changed `yarn dist:dir` to `yarn package`
- Added `CONDA_SUBDIR=osx-64` to `conda env create` to support Apple silicon, by forcing it to use x86 environment
- Added a way to automate removing unidentified developer warning (needs testing, not sure if it works on other machines other than mine)
https://github.com/architecture-building-systems/CityEnergyAnalyst/blob/8046f5d509d0610dfd8c977053955dff1656bb7e/cea/resources/radiation_daysim/radiation_main.py#L142-L148

### CODE REVIEW

**Comment by reyery** [comment]
@justinfmccarty I need your help to test it for Apple silicon. Mostly for the conda environment creation.

**Comment by martin-mosteiro** [comment]
@reyery I don't have Apple silicon, so I can't test that part. What else (and how) should I be testing, though? Uninstall and reinstall using `/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/architecture-building-systems/CityEnergyAnalyst/update-mac-installation/install/mac_installation.sh)`?

**Comment by reyery** [comment]
@martin-mosteiro yes that would be great! The installation script should work on non Apple silicon Macs as well. Help me review the docs as well to make sure it's easy to understand, if you have time.

**Comment by shanshanhsieh** [comment]
@justinfmccarty and @martin-mosteiro , please let us know the status if you get to try it out by any chance.
Thanks!

**Comment by justinfmccarty** [comment]
@shanshanhsieh working on it. I removed CEA from my system this time, so crossing my fingers.
Screenshot 2022-01-11 at 15 07 26

**Comment by justinfmccarty** [comment]
Alright, I have tried a few different things and have not been successful in using @reyery's script. I cut out the portion above "#Install Environment" and inserted my own cea conda env that I created beforehand. I ran the new .sh once and had a problem where it was having on package installation (searching for compatible versions). I cancelled that iteration and reran it. The CLI seems to work now. I will do more testing later this week. The GUI is not working though, it just hangs at app launch.

**Comment by reyery** [comment]
Hey @justinfmccarty, thanks for testing out the script! I have a few questions to help me debug this. What were the errors for the package installation, does it have something to do with forcing the architecture when creating the environment?

For the GUI, did you run `cea dashboard` before launching the it? That is usually the problem if it is stuck after launching. Currently the GUI does not automatically start the cea backend. But I think I have an idea that I have to test on my end first.

**Comment by shanshanhsieh** [comment]
@MatNif , how's it going with testing?

**Comment by MatNif** [comment]
> @MatNif , how's it going with testing?

@shanshanhsieh: I had a call with @reyery last week as I was mid installation. Reynold told me he would expand the script to take into account cases in which parts of the packages and tools were installed already and that it would not be worth testing the script before he had done so. He will contact me again as soon as he has finished that extension of the script and I will test it then.

**Comment by justinfmccarty** [comment]
@reyery I ran `cea dashboard` and immediately opened to GUI it was still hanging. However on a second try, when I run it after waiting for "start socketio.run" to print in the terminal (the first print after the settings are shown) then the GUI starts up no problem. 

Regarding errors...I have the entire printout from when I completed the installation. You can see at the end of the print that the installer reports success, but no `cea` environment was created. 


[Terminal Saved Output.txt](https://github.com/architecture-building-systems/CityEnergyAnalyst/files/7924600/Terminal.Saved.Output.txt)

**Comment by reyery** [comment]
> > @MatNif , how's it going with testing?
> 
> @shanshanhsieh: I had a call with @reyery last week as I was mid installation. Reynold told me he would expand the script to take into account cases in which parts of the packages and tools were installed already and that it would not be worth testing the script before he had done so. He will contact me again as soon as he has finished that extension of the script and I will test it then.

Yeah, after some feedback, I think I need to update the installation script a bit more to take into account some common cases that would cause some errors or is unfavorable (e.g. user already has their own cea env or local repo). I will update again in this PR when that is done.

**Comment by reyery** [comment]
> @reyery I ran `cea dashboard` and immediately opened to GUI it was still hanging. However on a second try, when I run it after waiting for "start socketio.run" to print in the terminal (the first print after the settings are shown) then the GUI starts up no problem.
> 
> Regarding errors...I have the entire printout from when I completed the installation. You can see at the end of the print that the installer reports success, but no `cea` environment was created.
> 
> [Terminal Saved Output.txt](https://github.com/architecture-building-systems/CityEnergyAnalyst/files/7924600/Terminal.Saved.Output.txt)

Thanks so much for the output! Will take a look later and see what the problem is. 

Ah yes, you would have to wait for `start socketio.run` to turn up first (sometimes it takes a while, especially the very first time, still not too sure what is causing that) before opening the GUI. Just realized that this is not mentioned in the docs. I will add that in.

**Comment by shanshanhsieh** [comment]
@reyery @justinfmccarty , @martin-mosteiro , @MatNif what is the status of reviewing?

**Comment by shanshanhsieh** [comment]
merging this branch and opening a new issue #3090 regarding the fixes required in the automation script

**Pull request merged**
