### PR TITLE
836 multiprocessing not working in demand main

### PR DESCRIPTION
**Pull request by daren-thomas**
multiprocessing should now work in demand_main as defined in the configuration script.

### CODE REVIEW

**Comment by daren-thomas** [comment]
@JIMENOFONSECA can you check this PR out please? It solves the issue of multiprocessing not working when running the demand_main.py script from PyCharm.

To configure your system, add a file called `cea.config` to your home directory (`%USERPROFILE%`, normally something like `C:\Users\USERNAME` but IT might have changed that for you).

The important content of that file is this section:

```
[general]
default-scenario: C:\reference-case-open\baseline
weather: Zug
multiprocessing = true
```

(but feel free to copy anything you want from the `cea\default.config` file and overwrite the default values as you please)

The `weather` setting can either be the name of an `*.epw` file in the cea database or a full path to a weather file to use.

After the first run, you will find a `scenario.config` file in the scenario - you can use that to change the values local to the scenario.

**Comment by JIMENOFONSECA** [comment]
@daren-thomas it does not pass the first iteration from PyCharm

C:\Users\Jimeno\AppData\Local\conda\conda\envs\cea\python.exe C:/Users/Jimeno/Documents/CityEnergyAnalyst/cea/demand/demand_main.py
failed to import from rc_model_sia_cc.pyd, falling back to pure python functions
failed to import from storagetank_cc.pyd, falling back to pure python functions
Traceback (most recent call last):
  File "C:/Users/Jimeno/Documents/CityEnergyAnalyst/cea/demand/demand_main.py", line 164, in <module>
    multiprocessing=config.multiprocessing)
  File "C:/Users/Jimeno/Documents/CityEnergyAnalyst/cea/demand/demand_main.py", line 136, in run_as_script
    assert os.path.exists(scenario_path), 'Scenario not found: %s' % scenario_path
AssertionError: Scenario not found: c:\users\jimeno\appdata\local\temp\reference-case-open\baseline
failed to save configuration file to default scenario.

Process finished with exit code 1


@daren-thomas could you also add to the docs a guide on how to work with the config file in this branch? I see this as the first step in interacting with CEA from now on. It is important to avoid confusion with all the dev team after this PR is merged

**Comment by daren-thomas** [comment]
@JIMENOFONSECA sure! it needs documentation!

It looks like you have not configured the `default-scenario` option in your user-config. I'm going to push a change that copies the default configuration to your home folder - that way it will be easier to edit.

**Comment by daren-thomas** [comment]
@JIMENOFONSECA check out the added bits to the installation-guide. Is that enough? I think we should also create a whole document on the configuration file...

**Comment by JIMENOFONSECA** [comment]
@daren-thomas it is a good starting.  But as you said, there should be a whole document on the configuration file to avoid confusion. Also, we need to clear out how to add new settings variables to the config file on our own, otherwise we will keep creating these settings files all the time.

Would you mind adding it to accept this PR? thanks?

**Comment by daren-thomas** [comment]
@JIMENOFONSECA this PR was a hotfix because you said you were stuck because of a bug. Issues #858 and #833 address a wider scope and will change any documentation about the configuration files.

Did you see the change to the installation guide in this PR? Is that enough? Otherwise, it will take about two weeks before I'm ready for a PR with the documentation.

**Pull request merged**
