### PR TITLE
CEA Occupancy-Schedule Updates

### PR DESCRIPTION
**Pull request by martin-mosteiro**
Had some issues merging @prakharmehta95's PR #2300, so I'm creating it again here.

### CODE REVIEW

**Comment by daren-thomas** [comment]
@martin-mosteiro could you please fix the merge conflicts? Also, maybe assigning the PR to yourself is not helping it getting merged - who should review this for you?

**Comment by martin-mosteiro** [comment]
@daren-thomas I didn't assign an issue to myself, @prakharmehta95 did - but then I had to create a new PR from his since I wasn't able to modify his branch directly. But this PR was created by @prakharmehta95. Let me know if I should assign someone else.

**Comment by martin-mosteiro** [comment]
@daren-thomas Also, I'm not sure how to resolve the conflicts above. This PR is about modifying the Excel databases in CEA, so the xlsx files should indeed be different.

**Comment by daren-thomas** [comment]
@martin-mosteiro so the conflicts probably mean that since the branch was created / last updated from master, those two files changed _and then_ you / @prakharmehta95 changed them.

If you're confident that the new version is correct, you can resolve the conflicts by using the version from this PR as opposed to the one from master.

If you're the person to test this then, is there any way I can help to get this merged? Anything blocking you?

**Pull request merged**
