### PR TITLE
Remove leap day from weather data

### LINKED ISSUE #2645: Solar Potential Calculation on HQ
**Describe the bug**
Rey, everything works fine…. Exept the calculation of the solar potential:
City Energy Analyst version 2.32.0
Running `cea photovoltaic` with the following parameters:
- general:scenario = C:\Users\sum\Documents\CEA\Hochshulquartier_status_quo New\MBS Case Study HQ
  (default: {general:project}\{general:scenario-name})
- general:multiprocessing = True
  (default: True)
- solar:type-pvpanel = PV1
  (default: PV1)
- general:number-of-cpus-to-keep-free = 1
  (default: 1)
- solar:panel-on-roof = True
  (default: True)
- solar:panel-on-wall = True
  (default: True)
- solar:annual-radiation-threshold = 800.0
  (default: 800.0)
- solar:solar-window-solstice = 4
  (default: 4)
Running photovoltaic with scenario = C:\Users\sum\Documents\CEA\Hochshulquartier_status_quo New\MBS Case Study HQ
Running photovoltaic with annual-radiation-threshold-kWh/m2 = 800.0
Running photovoltaic with panel-on-roof = True
Running photovoltaic with panel-on-wall = True
Running photovoltaic with solar-window-solstice = 4
Running photovoltaic with type-pvpanel = PV1
Using 3 CPU's
calculating solar properties doneTraceback (most recent call last):
  File "c:\users\sum\documents\cea\cityenergyanalyst\cityenergyanalyst\cea\worker.py", line 146, in worker
    run_job(config, job, server)
  File "c:\users\sum\documents\cea\cityenergyanalyst\cityenergyanalyst\cea\worker.py", line 108, in run_job
    script(config=config, **parameters)
  File "c:\users\sum\documents\cea\cityenergyanalyst\cityenergyanalyst\cea\api.py", line 53, in __call__
    self._runner.__call__(*args, **kwargs)
  File "c:\users\sum\documents\cea\cityenergyanalyst\cityenergyanalyst\cea\api.py", line 33, in script_runner
    script_module.main(config)
  File "c:\users\sum\documents\cea\cityenergyanalyst\cityenergyanalyst\cea\technologies\solar\photovoltaic.py", line 782, in main
    buildings_names)
  File "c:\users\sum\documents\cea\cityenergyanalyst\cityenergyanalyst\cea\utilities\parallel.py", line 97, in wrapper
    result = map_result.get()
  File "C:\Users\sum\Documents\CEA\CityEnergyAnalyst\Dependencies\Python\lib\multiprocessing\pool.py", line 572, in get
    raise self._value
ValueError: operands could not be broadcast together with shapes (8784,) (8784,) (8784,) () (8760,) (8760,) () () () 

gathering properties of PV panel
filtering low potential sensor points done
calculating optimal tile angle and separation done
generating groups of sensor points done
Could you give me a hint, what is wrong?

Best,

Matthias

**To Reproduce**

**Expected behaviour**

**Screenshots**

**Hardware (please complete the following information):**
 - OS and version: [e.g. iOS 10.7 or Windows 10]
 - Version of CEA you are using [e.g. v. 2.31.1]

### PR DESCRIPTION
**Pull request by reyery**
This PR fixes #2645 by removing the leap day when reading the weather file and also removing it from the radiation output data.

### CODE REVIEW

**Comment by reyery** [comment]
Testing
-
You would need to run the `radiation` and `photovoltaic` with a weather file that is from a leap year such as **Zuerich-SMA_2016** that we have in CEA.


**It should be noted that even after removing the leap day (from weather and radiation data), any pandas operations that involve a date range index (such as resampling date data) would still take into account the year and include the leap day. One example would be the solar radiation plot.

image

I am not sure how this would affect any other calculations but it seems to be passing tests on my end

**Comment by shanshanhsieh** [comment]
hey @reyery ,
the fix in `epw_reader` works fine!
but i think this PR needs another fix in function `get_dates_from_year`.
`get_dates_from_year` is used by many scripts to generate datetime in the output files, and maybe fixing this, or finding other similar functions that fetch the datatime data for the plot will fix the plotting error.
thanks for your time!

**Comment by reyery** [comment]
It seems that the problem with the plots is on the **Plotly** side as they try to interpolate the x-axis tickers even when the data/timeframe does not exist. But I think it is a separate issue.
Other than that, I have fixed the `get_dates_from_year` function to take into account the leap day, so it should hopefully fix any script that generates a date_range index.

**Comment by shanshanhsieh** [comment]
@reyery 
i made a small commit on `get_date_range_hours_From_year` becasue the operation seems to be inplace when i tested it.
however, the `epw_reader` function is not working since the length of `result` is not matching `date_range`
please take a look at it.
after your fix, please test `cea radiation`, `cea schedule_maker`, and `cea demand` to make sure it go through.
thank you!

**Comment by reyery** [comment]
I have fixed `epwreader` and had to do `reset_index` since it was affecting something in `demand`. I also reverted 3b08ca1 since it was still returning a date range with the leap day. Tested `cea radiation`, `cea schedule_maker`, and `cea demand` which seems to work on my end.

**Pull request merged**
