### PR TITLE
1777 optimize decentralized script for speed

### PR DESCRIPTION
**Pull request by daren-thomas**
This PR addresses #1777 but actually goes a bit farther. The calculation in `cea.technologies.chiller_absorption.calc_operating_conditions` was replaced - the `sympy.linsolve` method call is not needed if you already have a symbolic solution to the equation. See the docstring for that method on how this was done. The end product is a really long and hairy expression but _so much faster_.

Execution speed went from:
- original: 2931.58s
- using expression: 226.28s
- smarter use of AbsorptionChiller (less pandas __getitem__ calls): ~180s
- added multiprocessing, 7 cores:  96.41s

I only worked on the cooling case. Do we need to do the same for heating?

### CODE REVIEW

**Comment by JIMENOFONSECA** [comment]
@daren-thomas awesome!!, yes, the same for heating, please!

**Comment by shanshanhsieh** [comment]
@daren-thomas , the implementation works well!
i will wait until PR #2478 is merged, so i can run the workflows and tests before merging this branch.

**Comment by shanshanhsieh** [comment]
@daren-thomas could you please resolve the conflict? thanks

**Comment by daren-thomas** [comment]
@shanshanhsieh: no conflicts found :) let's merge already!

**Pull request merged**
