### PR TITLE
1956 glossary to dashboard

### PR DESCRIPTION
**Pull request by Jack-Hawthorne**
Hallo all,
I have been working on merging the `schema.yml` and `naming.csv` to have a broad overview of all the variables written by each script.

the documentation can now be done via the cli by calling the doc script:
```cea doc --mode <mode>```
with current modes being:
```gloss, viz, html, clean, api, merge```

most of these just run the batch files in the docs dir, however, some notable ones include:
- merge: merges the information in the `schema.yml` with that of the `naming.csv` to form a robust record of the variables (currently it references the old glossary but this can be removed once the full `schema.yml` is complete)
- gloss: generates a glossary based on the `naming_new.csv` which is an intermediate `naming.csv` until the merge is complete. Note: there are still some issues with the sphinx build of this, which will need to be hammered out.
- viz: not yet complete, i'll attempt recreating the trace_data from trace_inputlocator and run an altered version of viz method in trace_inputlocator (creates the graphviz images for script input/outputs

the plan is to have the dashboard reference the newest `naming.csv`, for which all the variables should be recorded.

note: there are a lot of variable overlaps in the current databasing system which will @daren-thomas most likely be a pain to get to sql format (I'm sure you're well aware of this already)

as always, feedback is welcome.

### CODE REVIEW

**Comment by daren-thomas** [comment]
Can one of the admins verify this patch?

**Comment by Jack-Hawthorne** [comment]
@daren-thomas i've made a few changes as recommended in the comments. i'm having trouble doing the `make html` part of the script without using the chdir command. also, i will need your help regarding the `cea-dev` tool integration. not quite sure how to accomplish this. 

i've added a lot of documentation explaining what each step does, and changed abbreviated names to more verbose ones. please let me know what you think about the changes! thanks

**Comment by daren-thomas** [comment]
@Jack-Hawthorne let's sit together and look at it. The way the `default.config` is set up is not the way to go and we can do the finishing touches together. When's a good time for you?

**Comment by Jack-Hawthorne** [comment]
ok so functionality for all new ``cea-doc`` tools has been tested, they are working ok.

I also updated the documentation for ``how-to-document-cea.rst`` to include this tool and what each function actually does.

trace-inputlocator has been updated but not tested yet, @daren-thomas if you could please look and manipulate it how you would like, that would be smashing.

**Comment by daren-thomas** [comment]
merging. thank you @Jack-Hawthorne for your hard work on this.

**Pull request merged**
