### PR TITLE
I712 sensitivity analysis tool

### PR DESCRIPTION
**Pull request by martin-mosteiro**
This PR incorporates the sensitivity analysis tool for the ArcGIS interface required by issue #712 .

The tutorial needs to be created next as a slideshow like the other CEA tutorials.

### CODE REVIEW

**Comment by JIMENOFONSECA** [comment]
@gabriel-happle please kindly give us a hand checking this PR, thanks!

**Comment by martin-mosteiro** [comment]
Perhaps even before that @daren-thomas would like to check this as well - I remember he had some suggestions to make the tool more user-friendly.

**Comment by JIMENOFONSECA** [comment]
@martin-mosteiro could you please check the conflics? thanks! and run cea test?
thanks!

**Comment by daren-thomas** [comment]
@martin-mosteiro, @JIMENOFONSECA - I'll look at the conflicts tomorrow: there's a bunch of stuff going on here. it's not so easy.

**Comment by daren-thomas** [comment]
@martin-mosteiro I have merged this branch with master. could you please check to see if your stuff is still working? a quick test of each tool should do the trick...

**Comment by martin-mosteiro** [comment]
@daren-thomas Tested the tool: works as expected!
Issue: I had to rename one variable in the uncertainty distributions database, so now the branch has a conflict.

**Comment by daren-thomas** [comment]
as far as i can tell, this is now good.

**Pull request merged**
