### PR TITLE
I1031 implement looped networks

### PR DESCRIPTION
**Pull request by roglen**
Major changes to the thermal network matrix code to incorporate looped networks.

Changes made to thermal_network_matrix.py and minor changes to substation_matrix.py.

Code validated in DH & DC mode for looped, branched and mixed networks with 1 or 2 plants. 

To check code:
- [x] read documentation on master-thesis-LR git, chapter 2.2 Looped Networks
(Master-Thesis-LR/Report/Master_Thesis_LR.pdf)
- [x] run case study (preferably not open case since already tested) for DH and DC

Code is not tested for .csv input files. 
For looped networks runtime significantly increased due to iteration of edge mass flows.

### CODE REVIEW

**Comment by roglen** [comment]
Updated the validation
Made suggest changes to code
Updated Validation documentation
Updated Master Thesis documentation
@shanshanhsieh please check again, should be ready to merge now

**Comment by shanshanhsieh** [comment]
@JIMENOFONSECA the new validation files are moved to cea-validation, but those in the master remain untouched in this PR.

**Comment by JIMENOFONSECA** [comment]
@roglen can you tell me about the steps to run this?

Thnaks!

**Comment by roglen** [comment]
@JIMENOFONSECA: 

The prerequisite to run is the demand files and a valid network of .shp files in the corresponding output and input folders. Then you should be able to just run the thermal_network_matrix.py script which will evaluate either the DH or DC case of the scenario, as specified in the config file.

**Comment by JIMENOFONSECA** [comment]
@roglen  thanks!, testing..

**Pull request merged**
