### PR TITLE
Fixes to demand simulation for Switzerland

### PR DESCRIPTION
**Pull request by jimenofonseca**
THis aims to solve #2944

### CODE REVIEW

**Comment by shanshanhsieh** [comment]
hi @jimenofonseca, 
thanks for the patch!
i have reviewed/test most of the changes, and they are working.
however, i cant get the unittest running even after updating the test data
any idea where this is coming from?

**Comment by shanshanhsieh** [comment]
also, please update from master, thanks!

**Comment by shanshanhsieh** [comment]
@shanshanhsieh will install `numpy_financial` in `C:\ProgramData\ceajenkins\ceatest-py3\Python\python.exe`

**Comment by shanshanhsieh** [comment]
@jimenofonseca please update the numbers for unittest, see error below:
"""
FAIL: test_calc_thermal_loads_other_buildings (test_calc_thermal_loads.TestCalcThermalLoads)
Test some other buildings just to make sure we have the proper data
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Program Files (x86)\Jenkins\workspace\run cea test for pull requests\cea\tests\test_calc_thermal_loads.py", line 101, in test_calc_thermal_loads_other_buildings
    self.assertAlmostEqual(expected_qhs_sys_kwh, qhs_sys_kwh,
AssertionError: 255070.44 != 255062.93 within 3 places (7.510000000009313 difference) : qhs_sys_kwh for B1006 should be: 255062.93000, was 255070.44000
"""

**Comment by jimenofonseca** [comment]
Some stuff still to be changed in here. I will take it down and do it another time

**Comment by shanshanhsieh** [comment]
okay!
it would be nice to simplify the changes in a single PR especially when the changes involve changing output values,
this will greatly speed up the testing process!

**Pull request closed without merging**
