### PR TITLE
fixes i1527

### PR DESCRIPTION
**Pull request by gabriel-happle**
additionally normalizes individual building monthly energy balance by GFA as well.

### CODE REVIEW

**Comment by gabriel-happle** [comment]
energy balance now in kWh/GFA

**Comment by gabriel-happle** [comment]
why do checks fail @daren-thomas ? I only changed some values in the plots. And the plots work for me. Is there a test that checks values inside plots?

**Comment by daren-thomas** [comment]
@gabriel-happle - it's the heatmaps... :-( i did create a pull request to fix them... i might just merge it myself...

**Comment by JIMENOFONSECA** [comment]
@gabriel-happle this diagram will be really cool at the district level showing the yearly balance per building. that will help to compare multiple buildings. what do you think?

**Pull request merged**
