### PR TITLE
3346 added detail on optimal district energy networks

### PR DESCRIPTION
**Pull request by MatNif**
Add a file detailing the properties of the thermal networks of the non-dominated solutions.

_EDIT:_ 

To test this branch:
1. Run the new optimisation script on a district of your choice, with the setting 'Advanced > generate-detailed-outputs' set to 'True'.
2. Check the detailed optimisation results by navigating to 'YOUR_CASE\outputs\data\optimization_new\DXS_XXX\Supply_system_operation_details'. You should now see two new files that were not generated before the introduction of this branch: 'NXXXX_annual_breakdown.csv' and 'network_performance.csv'.

'NXXXX_annual_breakdown.csv' will provide more information on a thermal network's supply system, like the annual consumption of specific energy carriers and their associated cost and Heat and GHG emissions.

 'network_performance.csv' will provide additional details on the piping of all of the thermal networks within a system, e.g. thermal losses, length of the network, etc.

### CODE REVIEW

**Comment by ShiZhongming** [comment]
Hi @MatNif 

Thanks for the detailed instructions. Testing in progress.

**Comment by ShiZhongming** [comment]
Hi @MatNif 

I have just finished testing this PR. I tested for both DC and DH cases.
For the DC case in Singapore, all worked fine as described.
For the DH case in Zurich, it reverted the error below. However, the script ran through when I switched off the `generate-detailed-outputs` toggle.
See the error message attached.

[error.pdf](https://github.com/architecture-building-systems/CityEnergyAnalyst/files/13072407/error.pdf)

**Comment by MatNif** [comment]
Great, thanks for testing. I'll try to replicate the error you get for DH on my side, but could you send me your test scenario in case I can't replicate the error?

**Comment by MatNif** [comment]
Hi @ShiZhongming,

I just tested the branch using a DH case but could not replicate your error. Could you send me your case?

**Comment by ShiZhongming** [comment]
Sure. I have just sent you via Slack.

**Pull request merged**
