### PR TITLE
I 1055 more legible plots

### PR DESCRIPTION
**Pull request by JIMENOFONSECA**
@roglen Hi lenny, would you mind checking the network plots in this branch for the open case? I get an error saying that the graph is too big to plot.

### CODE REVIEW

**Comment by roglen** [comment]
I'll have a look

**Comment by JIMENOFONSECA** [comment]
DH..

On 9 May 2018, 17:21 +0800, Lennart Rogenhofer <notifications@github.com>, wrote:

@JIMENOFONSECA<https://github.com/JIMENOFONSECA>
I checked the open case with DH and I don't get this error.
The legend and plot are slightly overlapping though, not sure if this is new but it should be fixed.
Were you running DC or DH?

**Comment by JIMENOFONSECA** [comment]
@gabriel-happle @shanshanhsieh @roglen @BhargavaKrishnaSreepathi  would you guys mind checking your plots and adding a description to the variables (of your plots) to the cea/plots/naming.csv please? Thanks!!

**Comment by gabriel-happle** [comment]
@JIMENOFONSECA do I get it right that we are all supposed to commit to the same (this) branch?

**Comment by gabriel-happle** [comment]
@JIMENOFONSECA I think my part is done.
I also fixed #1293 in this branch
I don't think we need naming for the comfort plots. They are not working here, but fixed with PR #1287 (other branch)

**Comment by shanshanhsieh** [comment]
@JIMENOFONSECA changes from my part has been committed

**Pull request merged**
