### PR TITLE
967 - dashboard first step: running tools (#1146 - Launcher)

### PR DESCRIPTION
**Pull request by daren-thomas**
@JIMENOFONSECA to test this, run the cea/interfaces/dashboard/dashboard.py script. A `conda env update` should install flask. Please report back any missing libraries - I'll update the `environment.yml` file to match. 

When the dashboard is running, check `https://localhost:5050` - in the sidebar, you can choose the cea tools and run them. This is a first prototype. My next step will be adding dashboard visualizations.

This implements a first stab at #1146 (Port the CEA Launcher to the dashboard interface)

### CODE REVIEW

**Comment by JIMENOFONSECA** [comment]
@daren-thomas so it runs, but it does not show anything in the browser. 

image

**Comment by JIMENOFONSECA** [comment]
@daren-thomas a new error while trying to run the webbrowser

image

**Comment by daren-thomas** [comment]
@JIMENOFONSECA I think you can check it out now - i've installed it on another computer from scratch and worked out all the missing stuff. do `cea dashboard` and then point your browser to `localhost:5050/`.

Of course, this is still very much work-in-progress. but as you find stuff, you can create issues and i'll tackle them in order of importance.

**Comment by JIMENOFONSECA** [comment]
@daren-thomas I just tried it out and found the same error. maybe we try a teamviewer session?

**Comment by daren-thomas** [comment]
I just installed the CEA in a clean virtual machine according to the installation guide, then checked out the `967-interface-and-dashboard-for-cea` branch and did `conda env update`. It works!

So... @JIMENOFONSECA maybe your system has some problems? maybe create a fresh environment like this: `conda env create --name cea-dashboard` and try running from there?

**Comment by JIMENOFONSECA** [comment]
@daren-thomas great I got it to work!, the trick was on making some of the libraries (those connected to GDAL, fiona and geopandas) to maintain one version that works. I modified the environment.yml variable for this. 

I suggest we write "libraryxxx = 1.3.4" instead of "libraryxxx >= 1.3.4". This will avoid that a future library breaks compatibility with other libraries.

**Comment by daren-thomas** [comment]
Build finished.

**Comment by daren-thomas** [comment]
@JIMENOFONSECA closing this pull request, merge #1431 instead

**Pull request closed without merging**
