### PR TITLE
1005 fix installation guide for ubuntu

### PR DESCRIPTION
**Pull request by daren-thomas**
This pull request revises the installation guide for Ubuntu. I went through each step to make sure it works. There is still an issue with running `cea test` to completion, but we're most of the way there and the goal of the issue #1005 (to fix the installation guide) is met.

To test this, follow the guide step by step on an Ubuntu (18 LTS) installation - either on a dedicated machine or in a virtual machine (if you're using Docker, e.g. on Windows, you already have hyper-v installed as a requirement and can create it there. That's what I used).

Please also check for spelling errors / grammar etc.

It also adds a Dockerfile for building a Docker container that can run the CEA. That can be tested with the following steps:

- `cd docker`
- `docker build -t your-user-name:cea .`
- `docker run -it your-user-name:cea cea test`

We will probably end up publishing the image to DockerHub, maybe with the tag `cityenergyanalyst:v2.12` or whatever the current version is...

### CODE REVIEW

**Comment by JIMENOFONSECA** [comment]
@daren-thomas we will have to trust you in this one since we do not count with Ubuntu machines around.  

It would be great to assign it though to somebody who uses ubuntu. Unfortunately, the only one was Jose, and he finished already his work...

One question. Does this work is equivalent for running things in a Linux and Mac OS?

MacOS systems probably could be used the most.  I personally would prefer to work with CEA from MacOS instead of windows....

**Comment by daren-thomas** [comment]
@JIMENOFONSECA I believe a lot of the ground-work done here is applicable to OS X. We'd have to try. I _do_ have an (old) macbook I could test this on. And I _will_ be setting up an Ubuntu machine for running CEA stuff in my office as soon as I find time. We're just short on hands, remember? ;-)

Ubuntu is a Linux distribution. Not all distributions use the `apt-get` package manager (e.g. RedHat uses `rpm` or used to back in the day, I'm not à-jour anymore) etc. but it will be similar to do. Besides, having the docker images might even be easier to run.

**Comment by daren-thomas** [comment]
@JIMENOFONSECA are you volunteering to be our go-to mac tester? That'd be awesome!!

**Comment by JIMENOFONSECA** [comment]
hehe, cool, so should I try this branch in my mac and see how it goes?




On 4 Apr 2019, 4:53 PM +0800, Daren Thomas <notifications@github.com>, wrote:

@JIMENOFONSECA<https://github.com/JIMENOFONSECA> are you volunteering to be our go-to mac tester? That'd be awesome!!

**Pull request merged**
