### PR TITLE
Test epanet - simple thermal model

### PR DESCRIPTION
**Pull request by JIMENOFONSECA**
So the thermal model we have is way too detailed and computationally expensive.

-> for 17 building it takes >10 hours with 3 cores.
-> with the new engine it takes 9.3 sec with one core.

The basis of the engine are
1. Planet for hydraulic calculations (simplified model of the reservoir with adjusted elevation according to pressure losses in the network.
2. supply and return pipes have the same pressure losses.
3. pressure losses at the heat exchanger = 2m
4. maximum velocity in pipes = 2m/s
4. Heat transfer equations (simplified) for thermal losses.

It was tested for the heating case and it seems to be working quite well.

1. pip install -e . (this should install the new dependency wntr==0.1.7)
2. run network layout
3 run thermal netowork (use simplified model)
4 ENJOY!!

@shanshanhsieh please test as soon as possible.

### CODE REVIEW

**Comment by JIMENOFONSECA** [comment]
image

**Comment by shanshanhsieh** [comment]
Assumptions:
1. fixed pressure losses at all substations (user-defined)
2. fixed plant `base_head` = 1 (hard-coded)
3. maximum velocity at pipe = 2m/s (user-defined)
4. thermal losses of supply pipes is calculated with average supply temperatures (same in all pipes) 
5. thermal losses of return pipes are calculated with average return temperature (same in all pipes)

**Comment by shanshanhsieh** [comment]
@JIMENOFONSECA 
some testing results:
1. in `reference-case-heating` , the thermal loss is 32% , while the detailed model yield 9%
   this is because the heat loss is not a function of heat load, but only temperature differences and pipe length. the behavior will differ when a district has more diverse building systems. 
2. in `reference-case-cooling`, the temperature difference between the supply temperature and outdoor air is smaller, therefore, yield a better estimation.
3. the pumping losses is <1% for cooling and ~9% for heating
4. the pipe sizes are similar to the detailed model (capital costs will be similar)

overall, i will say the model is good for cooling cases
and the thermal loss will be quite biased for heating cases
but more test cases should be tested to come to a conclusion 
for now, i think we can release it with a note on these assumptions and behaviors

**Comment by shanshanhsieh** [comment]
@JIMENOFONSECA 
the plots are running from the interface, but when i tried to run it from pycharm, this error shows up:
```
    raise MissingInputDataException("Dear developer: Run check_input_files() first, before plotting!")
cea.MissingInputDataException: Dear developer: Run check_input_files() first, before plotting!
```

**Comment by daren-thomas** [comment]
@shanshanhsieh can you please factor this out into a separate script and add a NOTE in the scripts.yml description?

**Comment by daren-thomas** [comment]
@JIMENOFONSECA @shanshan - how to resolve the conflict (supply_systems.xls) - is this version the newest or is master the newest? Does anybody remember?

**Comment by shanshanhsieh** [comment]
@JIMENOFONSECA , i encountered this error while running `cooling-case-workflow`
maybe it is related to some naming changes from your other commits?

```
DISTRICT COOLING OPERATION
Traceback (most recent call last):
  File "C:\Users\Zhongming\Documents\CityEnergyAnalyst\Dependencies\Python\Scripts\cea-script.py", line 11, in <module>
    load_entry_point('cityenergyanalyst', 'console_scripts', 'cea')()
  File "c:\users\zhongming\documents\cityenergyanalyst\cityenergyanalyst\cea\interfaces\cli\cli.py", line 66, in main
    script_module.main(config)
  File "c:\users\zhongming\documents\cityenergyanalyst\cityenergyanalyst\cea\workflows\workflow.py", line 56, in main
    do_script_step(config, step)
  File "c:\users\zhongming\documents\cityenergyanalyst\cityenergyanalyst\cea\workflows\workflow.py", line 138, in do_script_step
    run(config, py_script, **py_parameters)
  File "c:\users\zhongming\documents\cityenergyanalyst\cityenergyanalyst\cea\workflows\workflow.py", line 29, in run
    f(config=config, **kwargs)
  File "c:\users\zhongming\documents\cityenergyanalyst\cityenergyanalyst\cea\api.py", line 52, in __call__
    self._runner.__call__(*args, **kwargs)
  File "c:\users\zhongming\documents\cityenergyanalyst\cityenergyanalyst\cea\api.py", line 32, in script_runner
    script_module.main(config)
  File "c:\users\zhongming\documents\cityenergyanalyst\cityenergyanalyst\cea\optimization\optimization_main.py", line 117, in main
    moo_optimization(locator=locator, weather_file=weather_file, config=config)
  File "c:\users\zhongming\documents\cityenergyanalyst\cityenergyanalyst\cea\optimization\optimization_main.py", line 94, in moo_optimization
    network_features, config, prices, lca)
  File "c:\users\zhongming\documents\cityenergyanalyst\cityenergyanalyst\cea\optimization\master\master_main.py", line 227, in non_dominated_sorting_genetic_algorithm
    repeat(column_names, len(invalid_ind))))
  File "C:\Users\Zhongming\Documents\CityEnergyAnalyst\Dependencies\Python\lib\multiprocessing\pool.py", line 253, in map
    return self.map_async(func, iterable, chunksize).get()
  File "C:\Users\Zhongming\Documents\CityEnergyAnalyst\Dependencies\Python\lib\multiprocessing\pool.py", line 572, in get
    raise self._value
AttributeError: 'SlaveData' object has no attribute 'NG_Trigen_CCGT_size_W'
```

**Comment by daren-thomas** [comment]
I, too, get the `AttributeError: 'SlaveData' object has no attribute 'NG_Trigen_CCGT_size_W'`

**Comment by shanshanhsieh** [comment]
@JIMENOFONSECA 
seems like the columns for invalid individuals are not matching...
```
DISTRICT ELECTRICITY GRID OPERATION
Traceback (most recent call last):
  File "C:\Users\Zhongming\Documents\CityEnergyAnalyst\Dependencies\Python\Scripts\cea-script.py", line 11, in <module>
    load_entry_point('cityenergyanalyst', 'console_scripts', 'cea')()
  File "c:\users\zhongming\documents\cityenergyanalyst\cityenergyanalyst\cea\interfaces\cli\cli.py", line 66, in main
    script_module.main(config)
  File "c:\users\zhongming\documents\cityenergyanalyst\cityenergyanalyst\cea\optimization\optimization_main.py", line 117, in main
    moo_optimization(locator=locator, weather_file=weather_file, config=config)
  File "c:\users\zhongming\documents\cityenergyanalyst\cityenergyanalyst\cea\optimization\optimization_main.py", line 94, in moo_optimization
    network_features, config, prices, lca)
  File "c:\users\zhongming\documents\cityenergyanalyst\cityenergyanalyst\cea\optimization\master\master_main.py", line 277, in non_dominated_sorting_genetic_algorithm
    repeat(column_names, len(invalid_ind))))
  File "C:\Users\Zhongming\Documents\CityEnergyAnalyst\Dependencies\Python\lib\multiprocessing\pool.py", line 253, in map
    return self.map_async(func, iterable, chunksize).get()
  File "C:\Users\Zhongming\Documents\CityEnergyAnalyst\Dependencies\Python\lib\multiprocessing\pool.py", line 572, in get
    raise self._value
pandas.errors.EmptyDataError: No columns to parse from file

```

**Comment by daren-thomas** [comment]
@shanshanhsieh @JIMENOFONSECA is this ready to commit? It runs the district-cooling-system workflow on my machine. I think we're ready.

**Comment by JIMENOFONSECA** [comment]
Thanks for the analysis. So from pycharm you will have to clean up your compiled files from the cea folder. Right click on it and you will see that. This happens when new plots are introduced/changed
On 28 Nov 2019, 11:02 +0800, Shanshan Hsieh <notifications@github.com>, wrote:

@JIMENOFONSECA<https://github.com/JIMENOFONSECA>
the plots are running from the interface, but when i tried to run it from pycharm, this error shows up:

    raise MissingInputDataException("Dear developer: Run check_input_files() first, before plotting!")
cea.MissingInputDataException: Dear developer: Run check_input_files() first, before plotting!

**Pull request merged**
