### PR TITLE
removing repeated STANDARDs in CONSTRUCTION_STANDARD.xlsx (SG)

### PR DESCRIPTION
**Pull request by lguilhermers**
This solves issue #2961.

***
CONSTRUCTION_STANDARDS for Singapore had repeated items (with same paramereters) and unclear definitions.

Changes in CONSTUCTION_STANDARDS.xlsx:

1- Deleted STANDARD4 and STANDARD5 (were the same as STANDARD3)

2 - Changed definitions from existent standards:
•	STANDARD1
FROM: Concrete and Masonry with outdoor corridors
TO: Concrete and Masonry - residential, reduced conditioned areas

•	STANDARD2
FROM: Concrete and Masonry with indoor corridors
TO: Concrete and Masonry - residential, increased conditioned areas

•	STANDARD3
FROM: Concrete, Masonry and Rainscreens
TO: Concrete and Masonry - commercial

The motivation to change the definitions is to make more intuitive for the user to select a suitable standard without much knowledge about them.  "Corridors" and "Rainscreens" weren't very informative, as in reality the standards try to reflect HDBs, condominium and commercial properties.

***
WALLs (ASSEMBLIES - ENVELOPE) for Singapore had an old parameter U_base, which was migrated to floor.

Changes in ENVELOPE.xls:
1- Deleted U_base column in WALL tab.

To test: Open a scenatio with Singapore database and check changes in database editor.

### CODE REVIEW

**Comment by lguilhermers** [comment]
Thanks, @shanshanhsieh! sorry for not checking the workflow, still getting used to the PRs.
I like your suggestions and I think those are good alternatives. We should keep simple the parameters so it is easy to understand what is different by the definition, so I think changing a single parameter (as you proposed) is the way to go.

In standard 5 I would also specify if it is high or low wwr.
Or have a baseline commercial (high wwr) and just have low wwr, and green roof stated, because then is more intuitive the other is different.

**Comment by lguilhermers** [comment]
@shanshanhsieh I have updated with your suggestion, please check now.

PS: In an unrelated issue, I ran both workflows, both running until Workflow step 13: script=network-layout and giving an error that seems unrelated (see below). I find strange to not have the streets file. Any ideas about that?

ERROR: Missing input files:
- C:\CEA\inputs\inputs\inputs\networks\streets.shp
Traceback (most recent call last):
  File "C:\Users\luis.santos\Documents\CityEnergyAnalyst\Dependencies\Python\Scripts\cea-script.py", line 33, in <module>
    sys.exit(load_entry_point('cityenergyanalyst', 'console_scripts', 'cea')())
  File "c:\users\luis.santos\documents\cityenergyanalyst\cityenergyanalyst\cea\interfaces\cli\cli.py", line 72, in main
    script_module.main(config)
  File "c:\users\luis.santos\documents\cityenergyanalyst\cityenergyanalyst\cea\workflows\workflow.py", line 83, in main
    do_script_step(config, i, step, trace_input)
  File "c:\users\luis.santos\documents\cityenergyanalyst\cityenergyanalyst\cea\workflows\workflow.py", line 176, in do_script_step
    run(config, py_script, **py_parameters)
  File "c:\users\luis.santos\documents\cityenergyanalyst\cityenergyanalyst\cea\workflows\workflow.py", line 29, in run
    f(config=config, **kwargs)
  File "c:\users\luis.santos\documents\cityenergyanalyst\cityenergyanalyst\cea\api.py", line 59, in __call__
    self._runner.__call__(*args, **kwargs)
  File "c:\users\luis.santos\documents\cityenergyanalyst\cityenergyanalyst\cea\api.py", line 34, in script_runner
    raise cea.MissingInputDataException()
cea.MissingInputDataException

**Comment by jimenofonseca** [comment]
I trend to feel that the best use pf the standard and other propierties is that they start speaking to Standards (e.g., LEED platinium building, Minergie A, Minergie Eco) etc. this will make it just easier to run simulations for all and multiple scenarios of well defined typical buildings.

I guess in Singapore Green Mark etc.

**Comment by lguilhermers** [comment]
Tested both cooling and heating, both worked (after deleting the config and reference-case-open before running the workflow)

**Comment by lguilhermers** [comment]
> I trend to feel that the best use pf the standard and other propierties is that they start speaking to Standards (e.g., LEED platinium building, Minergie A, Minergie Eco) etc. this will make it just easier to run simulations for all and multiple scenarios of well defined typical buildings.
> 
> I guess in Singapore Green Mark etc.


@jimenofonseca I agree, but I feel the Standards sometimes allow flexibility within the ranges of parameters or work with metrics different from CEA. Nonetheless, we can still make them in a way that is at least closer to those standards than the defaults...
For now the plan was only to fix some issues and make the descriptions more clear. Since I plan to work more on that now (green marks, super low energy and net zero), hopefully I can come with good additions for this database in the future. :)

**Comment by shanshanhsieh** [comment]
@lguilhermers @jimenofonseca thanks for the comments!
@lguilhermers could you please adding an issue about updating SG database with current standards (Green Mart etc...)

**Comment by shanshanhsieh** [comment]
closing this issue now, and keeping the comment regarding standards to be integrated in the SG database in this new issue #2974

**Pull request merged**
