### PR TITLE
LCA database Reference documentation update

### PR DESCRIPTION
**Pull request by ongbolie**
- updated reference for LCA-infrastructure for SG (Resource)
- updated missing reference for LCA-infrastructure for CH (Resource - data for 'Solid Waste' extracted from Kehrichtverbrennung KBOB 2009/1:2016)
- PEN and CO2 are from ecoinvent 3.4 (SG), KBOB (CH)
- costs are  calculated from CEA

This PR fixes Issue #1567.

### CODE REVIEW

**Comment by JIMENOFONSECA** [comment]
@gabriel-happle can you check this patch? thanks!

**Comment by gabriel-happle** [comment]
Thanks @ongbolie 
In `CityEnergyAnalyst/cea/databases/SIN/lifecycle/LCA_infrastructure.xlsx` you can remove the references column in the `Cooling` and  `Electricity` Tab. Because there is no LCA information stored.

**Comment by gabriel-happle** [comment]
@JIMENOFONSECA could you please review the efficiency of row 17 in `cea/databases/CH/lifecycle/LCA_infrastructure.xlsx` in the `DHW` and `Heating` tabs.

Could you add to the documentation what the resources energy content mean? I.e., cost per kWh of Natural Gas? Is it heating value or converted into electricity.
Also, why are the cost for PV so low? Aren't we calculating them inside CEA?

**Comment by ongbolie** [comment]
@gabriel-happle Just deleted the references from `DHW`, `Heating`, `Cooling` and `Electricity` tab from cea/databases/SG/lifecycle/LCA_infrastructure.xlsx

**Comment by JIMENOFONSECA** [comment]
@gabriel-happle @ongbolie done, I fixed the value and added "educated guess" as the reference, which depicts what it is basically for now.

I leave this issue to whoever would like to get more detailed values for the baseline calculation. Maybe the work of https://data.sccer-jasm.ch can help with this. 

The optimization part remains less affected, except on the step of decentralized buildings, @BhargavaKrishnaSreepathi is that correct?

**Comment by BhargavaKrishnaSreepathi** [comment]
optimization (both centralized and decentralized) uses the values corresponding to the Primary Energy, CO2 emissions and costs from the 'Resources' tab in the 'LCA_infrastructure' file. So it is affected by the change of numbers

**Comment by JIMENOFONSECA** [comment]
that is OK. but the efficiency is not right?


On 2 Aug 2018, 3:54 PM +0800, Bhargava Krishna Sreepathi <notifications@github.com>, wrote:

optimization (both centralized and decentralized) uses the values corresponding to the Primary Energy, CO2 emissions and costs from the 'Resources' tab in the 'LCA_infrastructure' file. So it is affected by the change of numbers

**Comment by BhargavaKrishnaSreepathi** [comment]
Nope, other tabs are not being used in optimization. Only the 'Resources' tab is being used in the optimization

**Comment by JIMENOFONSECA** [comment]
@ongbolie actually the PR was not merged, It is not passing the tests. Could you check in your computer what is the problem?

**Comment by ongbolie** [comment]
@JIMENOFONSECA Local test ran successfully on my computer

**Comment by BhargavaKrishnaSreepathi** [comment]
@JIMENOFONSECA @ongbolie : I ran the local tests on my computer for this PR. The tests ran successfully.

**Pull request merged**
