### PR TITLE
Release 2.30

### PR DESCRIPTION
**Pull request by reyery**
This is the result of the M2.30 sprint. We worked mainly on restructuring the databases shipped with CEA and creating the GUI to edit them.

To install it on windows, download and run the attached [Setup_CityEnergyAnalyst_2.30.0.exe](https://github.com/architecture-building-systems/CityEnergyAnalyst/releases/download/v2.30.0/Setup_CityEnergyAnalyst_2.30.0.exe). 
[See the guide for more options.](https://city-energy-analyst.readthedocs.io/en/latest/getting-started.html#install-and-set-up)

From the CHANGELOG:

2020-02-17 - 2.29.0 - #2565 Issue databases
2020-02-17 - 2.29.0 - #2557 I2553 restructure database
2020-02-13 - 2.29.0 - #2562 2551 many files optimization
2020-02-13 - 2.29.0 - #2559 Update how-are-schedules-defined.rst
2020-02-11 - 2.29.0 - #2556 `Annual Cost` and `Annual Emissions` plots x-axis are sorted by cost
2020-02-10 - 2.29.0 - #2554 2536 technology editor
2020-02-10 - 2.29.0 - #2550 I2534 opt technologies, merging but sending a new PR with more tests in case functionality is broken (not likely) according to extensive testing.
2020-02-06 - 2.29.0 - #2546 Glossary.csv - synchronized with newest schemas.yml
2020-02-03 - 2.29.0 - #2544 update schemas.yml file to conform to changes in PR 2532
2020-02-03 - 2.29.0 - #2545 Fixed typo in a variable name @martin-mosteiro good catch
2020-01-23 - 2.29.0 - #2542 Release 2.29

### CODE REVIEW

**Comment by JIMENOFONSECA** [comment]
@reyery while testing #2567 I found that the glossary and the input/schedules interface do not work anymore. mind checking this before releasing?

**Comment by reyery** [comment]
@JIMENOFONSECA have you tested it with the new interface here:
https://github.com/architecture-building-systems/CityEnergyAnalyst-GUI/releases/download/v2.30.0/win-unpacked.7z

**Comment by daren-thomas** [comment]
@JIMENOFONSECA @reyery is this ready to be merged?

**Comment by JIMENOFONSECA** [comment]
No!! It was not ready. Ups. I guess we have to do a new release right away to fix some vugs we found in the interface.
On 19 Feb 2020, 21:31 +0800, Daren Thomas <notifications@github.com>, wrote:

Merged #2568<https://github.com/architecture-building-systems/CityEnergyAnalyst/pull/2568> into master.

**Comment by daren-thomas** [comment]
@JIMENOFONSECA my bad... I mixed up the dates and thought 2.30 was due last week while I was on vacation. I'm sorry. I'll be doing a version 2.30.1 after the SCRUM meeting.

**Pull request merged**
