### PR TITLE
Radiation now account for adjacent buildings

### PR DESCRIPTION
**Pull request by JIMENOFONSECA**
@martin-mosteiro this should fix it #2397

### CODE REVIEW

**Comment by martin-mosteiro** [comment]
@JIMENOFONSECA line 407 in **geometry_generator.py** (`instersection = calculate.point_in_solid(sensor_cord, solid)`) appears to print a message that didn't use to happen as far as I can tell:
```
('State', 1)
```
(prints out once for every `solid` in `building_solid_list`)

Does this happen for you too?

**Comment by martin-mosteiro** [comment]
In addition to the above, the geometry generator doesn't seem to work on my case study anymore. I left it running for ~2 hours and it stayed stuck in the loop that contains the line mentioned above.

This was _not_ the case for the `reference-case-open`. Then again, there's no adjacent buildings in the reference case, so I wonder if that's the difference?

**Comment by JIMENOFONSECA** [comment]
Weird. It should work for any case. Can u try again?. The messagge is normal...use multiprocessing
On 25 Oct 2019, 22:18 +0800, Martín Mosteiro-Romero <notifications@github.com>, wrote:

In addition to the above, the geometry generator doesn't seem to work on my case study anymore. I left it running for ~2 hours and it stayed stuck in the loop that contains the line mentioned above.

This was not the case for the reference-case-open. Then again, there's no adjacent buildings in the reference case, so I wonder if that's the difference?

**Comment by martin-mosteiro** [comment]
@JIMENOFONSECA Unfortunately not. I have now tested on two computers and the `geometry_generator` works on neither, although the master branch works on both. I've been using multiprocessing in all cases.

**Comment by martin-mosteiro** [comment]
@JIMENOFONSECA Indeed, it worked now. The results are still strange, though. While we now have no windows in adjacent walls (good), for a test building 4% of the insolation still occurred on adjacent walls. While 4% is not all that much, is it also not easy to filter the surfaces by insolation, either, as the adjacent walls get a similar insolation per m2 as certain exposed surfaces.

**Comment by JIMENOFONSECA** [comment]
@martin-mosteiro sorry I made a mistake in there. Does this work now? if so, mind creating the test files ? thanks!!

**Comment by JIMENOFONSECA** [comment]
@martin-mosteiro did it work now?

**Comment by martin-mosteiro** [comment]
Successfully tested on two Hochschulquartier scenarios and on the reference-case-open. The tests are not passing because the data in the reference case is outdated (no `intersection` column). After updating this data I would assume it'll work.

**Pull request merged**
