### PR TITLE
Raise an error for false weather files

### PR DESCRIPTION
**Pull request by daren-thomas**
This PR addresses #2333 - basically, if the user manually edited the config file to set the `{weather-helper:weather}` to an invalid value, the CEA was just taking the first valid weather file name from its database and working with that.

The new behavior: Raise an error to make it obvious that the config file has a false value.

### CODE REVIEW

**Comment by daren-thomas** [comment]
@martin-mosteiro assigning to you as you posted the issue.

**Comment by martin-mosteiro** [comment]
Fair enough, I'll take a stab at it.

**Comment by martin-mosteiro** [comment]
Tested by doing the following:
1. Set `config.weather_helper.weather = 'something-stupid'`. Got the following `cea.ConfigError: Invalid weather path: something-stupid`
2. Set `config.weather_helper.weather = `. Got the following `AssertionError: Could not find weather file: Singapore-Changi_1990_2010_TMY`
3. Set `config.weather_helper.weather = Zuerich-SMA_2015`. Got `Set weather for scenario <baseline> to /Users/martinmo/Documents/GitHub/CityEnergyAnalyst/cea/databases/weather/Zuerich-SMA_2015.epw`
4. Set `config.weather_helper.weather = Singapore-Changi_1990_2010_TMY`. Got `Set weather for scenario <baseline> to /Users/martinmo/Documents/GitHub/CityEnergyAnalyst/cea/databases/weather/Singapore-Changi_1990_2010_TMY.epw`

The results from tests 1, 3 and 4 sound right to me. Test 2 is odd, though. @daren-thomas Shouldn't the error message be that it's not getting any weather file at all?

**Comment by daren-thomas** [comment]
@martin-mosteiro: well spotted! also, this is a great example of testing! thank you :) (fixed - care to check again?)

**Comment by martin-mosteiro** [comment]
Perfect! Thanks @daren-thomas

**Pull request merged**
