### PR TITLE
i636 connect solar collector and pvt with new radiation results

### PR DESCRIPTION
**Pull request by shanshanhsieh**
Changes:

- New folder `solar` under the `cea/technologies`
- New `settings.py` files to store solar technology-related inputs
- Refactored `solar_collector.py`
- Refactored `photovoltaic_thermal.py`
- add solar collector specifications to `supply_systems.xls` database
- add `calc_worst_hour` function to determine the worst hour according to the desired hours of solar window on winter solstice.

### CODE REVIEW

**Comment by daren-thomas** [comment]
@shanshanhsieh how to test this?

**Comment by shanshanhsieh** [comment]
@daren-thomas do you mean that we should add a test for the "dodo test"?

**Comment by daren-thomas** [comment]
No, basically, what should I run and how to verify it now works?

**Comment by JIMENOFONSECA** [comment]
@shanshanhsieh would you mind checking for conflicts?

**Comment by shanshanhsieh** [comment]
@JIMENOFONSECA conflicts resolved!
However, all the parameters are migrated to the `settings.py` file now, meaning that the inputs we get from the arcgis interface are no longer arguments in the function `calc_PV`, 'calc_SC`, `calc_PVT`. 
Please first take a look to see if the parameters in the settings file make sense, and then we could change the interface accordingly.

**Comment by JIMENOFONSECA** [comment]
@shanshanhsieh overall the script runs but the results need to be checked. Please consider:

1. There should be a separate tab for PVT and the last should be filled in in databases/systems...
2. The efficiency of the PVT and SC seems to not match the nominal. for PVT, the % of the energy generated in relation to the radiation should be around 70%. but we get at the best around 20%. It would be good checking what is wrong with it.
3. The pumping consumption is rather low. it seems it only consumes 10W or 20W to move water around for a whole installation in an hour. It seems rather unusual. A hint: a Led bulb consumes 3W, a vacum cleaner consumes 1000W.

**Comment by shanshanhsieh** [comment]
Hi @JIMENOFONSECA , thanks for catching this, I will take a look this week.

**Comment by daren-thomas** [comment]
@shanshanhsieh could you please take a look at the interface? I just pushed my stab at it... The other two interfaces could be done in a similar matter.

**Comment by JIMENOFONSECA** [comment]
@shanshanhsieh could you let me know when this is ready to test again?

**Comment by shanshanhsieh** [comment]
@JIMENOFONSECA , i will let you know once the conflicts are resolved!

**Comment by JIMENOFONSECA** [comment]
@shanshanhsieh updates?

**Comment by shanshanhsieh** [comment]
@JIMENOFONSECA there are more conflicts now after merging the refactoring branch. I will go on fixing it now

**Comment by JIMENOFONSECA** [comment]
@shanshanhsieh thnaks!, after that, qouedl you mind @martin-mosteiro to take a look at this PR?

**Pull request merged**
