### PR TITLE
I833 switch databases

### PR DESCRIPTION
**Pull request by JIMENOFONSECA**

### CODE REVIEW

**Comment by JIMENOFONSECA** [comment]
@daren thomas I created the PR for this branch so we can keep it on the pipeline of things to test asap

**Comment by JIMENOFONSECA** [comment]
@daren-thomas the multiprocessing flag does not work and does not affect the demand calculation or any-other calculation. maybe we account for that issue in this branch. let me know how we can hep as this issue is blocking us at the moment

**Comment by daren-thomas** [comment]
@JIMENOFONSECA how are you running the demand calculations? What steps *exactly* are you taking? What are the input values? What did you expect? What did you see as a result instead?

**Comment by JIMENOFONSECA** [comment]
@daren-thomas is your question already addressed in #836 ? or should I elaborate? I see a conflict in this branch I might know how to solve, let me know when

**Comment by daren-thomas** [comment]
@JIMENOFONSECA, yes, my questions are addressed - see the PR #856 for a fix to the issue. This branch is not ready to be merged yet.

**Comment by daren-thomas** [comment]
@JIMENOFONSECA Please DON'T merge this! It doesn't work yet!

**Comment by JIMENOFONSECA** [comment]
@daren-thomas are we ready to merge? let me know how to test it and what is different. thanks

**Comment by daren-thomas** [comment]
Build finished.

**Comment by daren-thomas** [comment]
Build finished.

**Pull request merged**
