### PR TITLE
Add empty property to MultiChoiceParameter

### LINKED ISSUE #2966: Running multiple scenarios consecutively (workflow): restriction of number of buildings simulated
**Describe the bug**
I have workflows (yml-files) which simulate multiple scenarios consecutively. The structure is visible in the following txt-file. 
[YML_rural.txt](https://github.com/architecture-building-systems/CityEnergyAnalyst/files/6417964/YML_rural.txt)
Each scenario covers a different municipality in Switzerland. The problem is that the number of buildings of each scenario is restricted to the number of buildings from the first scenario. This is problematic when running a scenario with less buildings involved first.

**To Reproduce**
1. Create two scenarios with differing sizes (different amount of buildings involved)
2. Create a workflow where both scenarios are run consecutively and where the scenario with less buildings is run first.
3. Notice that the demand, radiation, schedules,.... from the second scenario are limited to the amount of buildings from the first scenario.

**Hardware (please complete the following information):**
 - Windows 10
 - not sure how to check the CEA version yet, downloaded it approx. 2 weeks ago.

### PR DESCRIPTION
**Pull request by reyery**
This PR fixes #2966 by adding the `_.empty` property to `MultiChoiceParameter` which is inherited by `BuildingsParameter`. 
This will not only affect the `building` parameter, but all parameters in the config that uses `MultiChoiceParameter`. 

This solves the issue by keeping a state that indicates that the parameter is an empty value (selecting every value) when the parameter is initialized and reading from config. When getting the value of such parameter, it will just return every value if the empty state is `True`. The empty state will only be `False` when explicitly setting the parameter with a non empty value. 

So `BuildingsParameter` will remember the empty state instead of the buildings of the previous scenario when running workflow unless explicitly changed in later steps.

## Testing
Test workflow with 2 different scenarios with different number of buildings
- Run demand for each, with the scenario with **lesser** buildings before the other
    - the second scenario should still be able to run with all it's buildings
- Set the buildings parameter when running demand and check if as expected

### CODE REVIEW

**Comment by shanshanhsieh** [comment]
hey @reyery ,

thanks for the PR.
it only works if i initiate cea config again before starting the new case study.
is it an expected behavior?

```
- config: default
  "general:project": "C:\\Users\\shsieh\\Documents\\CEA_Porjects\\PR2972"
  "radiation:daysim-bin-directory": "${CEA_radiation_daysim-bin-directory}"
- config: .
  "general:scenario-name": SMALL
- script: data-initializer
  parameters:
    databases-path: CH
    databases: [archetypes, assemblies, components]
- script: archetypes-mapper
  parameters:
    input-databases: [comfort, architecture, air-conditioning, internal-loads, supply, schedules]
- script: radiation
  parameters:
    consider-intersections: false
- script: schedule-maker
- script: demand
- config: default # THIS IS REQUIRED
  "general:project": "C:\\Users\\shsieh\\Documents\\CEA_Porjects\\PR2972"
  "radiation:daysim-bin-directory": "${CEA_radiation_daysim-bin-directory}"
- config: .
  "general:scenario-name": BIG
- script: data-initializer
  parameters:
    databases-path: CH
    databases: [archetypes, assemblies, components]
- script: archetypes-mapper
  parameters:
    input-databases: [comfort, architecture, air-conditioning, internal-loads, supply, schedules]
- script: radiation
  parameters:
    consider-intersections: false
- script: schedule-maker
- script: demand
```

**Comment by shanshanhsieh** [comment]
@reyery , could you please comment on my question? thanks!

**Comment by shanshanhsieh** [comment]
ummmm that's not the case for me though, i tried what you suggested, but the problem is still there...
maybe we could call for some more testings.

Steps to test:
1. Create two scenarios, one with more buildings and one with less buildings
[PR2972.zip](https://github.com/architecture-building-systems/CityEnergyAnalyst/files/6474466/PR2972.zip)
2. try workflow A and B
**workflow A.**
```
# SMALL
- config: default
  "general:project": "C:\\Users\\shsieh\\Documents\\CEA_Porjects\\PR2972"
  "radiation:daysim-bin-directory": "${CEA_radiation_daysim-bin-directory}"
- config: .
  "general:scenario-name": SMALL
- script: data-initializer
  parameters:
    databases-path: CH
    databases: [archetypes, assemblies, components]
- script: archetypes-mapper
  parameters:
    input-databases: [comfort, architecture, air-conditioning, internal-loads, supply, schedules]
- script: radiation
  parameters:
    consider-intersections: false
- script: schedule-maker
- script: demand
# BIG
- config: .
  "general:scenario-name": BIG
- script: data-initializer
  parameters:
    databases-path: CH
    databases: [archetypes, assemblies, components]
- script: archetypes-mapper
  parameters:
    input-databases: [comfort, architecture, air-conditioning, internal-loads, supply, schedules]
- script: radiation
  parameters:
    consider-intersections: false
- script: schedule-maker
- script: demand
```
**workflow B.**
```
# SMALL
- config: default
  "general:project": "C:\\Users\\shsieh\\Documents\\CEA_Porjects\\PR2972"
  "radiation:daysim-bin-directory": "${CEA_radiation_daysim-bin-directory}"
- config: .
  "general:scenario-name": SMALL
- script: data-initializer
  parameters:
    databases-path: CH
    databases: [archetypes, assemblies, components]
- script: archetypes-mapper
  parameters:
    input-databases: [comfort, architecture, air-conditioning, internal-loads, supply, schedules]
- script: radiation
  parameters:
    consider-intersections: false
- script: schedule-maker
- script: demand
# BIG
- config: default # THIS IS REQUIRED
  "general:project": "C:\\Users\\shsieh\\Documents\\CEA_Porjects\\PR2972"
  "radiation:daysim-bin-directory": "${CEA_radiation_daysim-bin-directory}"
- config: .
  "general:scenario-name": BIG
- script: data-initializer
  parameters:
    databases-path: CH
    databases: [archetypes, assemblies, components]
- script: archetypes-mapper
  parameters:
    input-databases: [comfort, architecture, air-conditioning, internal-loads, supply, schedules]
- script: radiation
  parameters:
    consider-intersections: false
- script: schedule-maker
- script: demand
```
3. after each workflow, check the number of buildings simulated in the BIG case

**Comment by reyery** [comment]
Okay I might need to test it on my end again

**Comment by shanshanhsieh** [comment]
thanks, @reyery , **workflow A** is also working now!

**Pull request merged**
