### PR TITLE
1914 radiation daysim windows installer

### LINKED ISSUE #1914: Make sure radiation-daysim works after installing the CEA with the Installer
The installer bundles Daysim binaries. These still need to be tested properly. First field tests (thank you @JIMENOFONSECA) imply it doesn't quite work yet.

### PR DESCRIPTION
**Pull request by daren-thomas**
This PR fixes #1914 - radiation-daysim now works when installed with the installer. A minimal set of Daysim binaries are shipped and the environment is set up.

To test:
- run the installer https://www.dropbox.com/s/rfka3st83ap07be/Setup_CityEnergyAnalyst_2.13.5a1.exe?dl=0
- using the CEA Console shortcut, run `cea radiation-daysim`
- using the CEA Dashboard shortcut, run Tools -> Energy Potentials -> Solar (Radiation Daysim).

The radiation script should run to completion

### CODE REVIEW

**Comment by JIMENOFONSECA** [comment]
@daren-thomas let's maintain the original logo of CEA, the color full one that was in the previous installer. let me know when the new installer is ready.

**Comment by JIMENOFONSECA** [comment]
I did the second step. and it does not work. I am on this branch while testing

image

**Comment by JIMENOFONSECA** [comment]
The CEA dashboard does not run form the shortcut. It just does not open it...

**Comment by JIMENOFONSECA** [comment]
The conclusion from a slack conversation between Daren and me... there is a problem with this installer in the developer's version.

**Comment by JIMENOFONSECA** [comment]
Also. we just tested it in another computer, the NO-developer version. It also does not work..@zhongming would you mind posting the error message?

**Comment by shizhongming** [comment]
Hi @daren-thomas , neat installation...but it seems the cea dashboard is not working. See the error below..

C:\Users\Zhongming\Documents\CityEnergyAnalyst
λ cea dashboard
City Energy Analyst version 2.13.5a1
Running `cea dashboard` with the following parameters:
 * Serving Flask app "cea.interfaces.dashboard.dashboard" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://localhost:5050/ (Press CTRL+C to quit)
127.0.0.1 - - [09/May/2019 15:58:57] "GET / HTTP/1.1" 302 -
load_plot C:\reference-case-open {'category': 'demand', 'plot': 'energy-balance', 'parameters': {'building': 'XYZ', 'scenario-name': 'baseline'}}
[2019-05-09 15:58:57,660] ERROR in app: Exception on /landing/welcome [GET]
Traceback (most recent call last):
  File "C:\Users\Zhongming\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Zhongming\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Zhongming\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Zhongming\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Zhongming\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Zhongming\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\cea\interfaces\dashboard\landing\routes.py", line 23, in index
    return render_template('landing.html')
  File "C:\Users\Zhongming\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\flask\templating.py", line 133, in render_template
    ctx.app.update_template_context(context)
  File "C:\Users\Zhongming\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\flask\app.py", line 792, in update_template_context
    context.update(func())
  File "C:\Users\Zhongming\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\cea\interfaces\dashboard\dashboard.py", line 39, in dashboards_processor
    dashboards = cea.plots.read_dashboards(config, plot_cache)
  File "C:\Users\Zhongming\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\cea\plots\__init__.py", line 47, in read_dashboards
    dashboards = [default_dashboard(config, cache)]
  File "C:\Users\Zhongming\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\cea\plots\__init__.py", line 70, in default_dashboard
    'scenario-name': config.scenario_name}}]}, cache)
  File "C:\Users\Zhongming\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\cea\plots\__init__.py", line 98, in __init__
    self.plots = [load_plot(config.project, plot_dict, cache) for plot_dict in dashboard_dict['plots']]
  File "C:\Users\Zhongming\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\cea\plots\__init__.py", line 126, in load_plot
    return plot_class(project, parameters, cache)
  File "C:\Users\Zhongming\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\cea\plots\demand\energy_balance.py", line 27, in __init__
    super(EnergyBalancePlot, self).__init__(project, parameters, cache)
  File "C:\Users\Zhongming\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\cea\plots\demand\__init__.py", line 153, in __init__
    super(DemandSingleBuildingPlotBase, self).__init__(project, parameters, cache)
  File "C:\Users\Zhongming\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\cea\plots\demand\__init__.py", line 46, in __init__
    zone_building_names = self.locator.get_zone_building_names()
  File "C:\Users\Zhongming\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\cea\inputlocator.py", line 585, in get_zone_building_names
    zone_building_names = sorted(gdf.from_file(self.get_zone_geometry())['Name'].values)
  File "C:\Users\Zhongming\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\geopandas\geodataframe.py", line 455, in __getitem__
    result = super(GeoDataFrame, self).__getitem__(key)
  File "C:\Users\Zhongming\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\pandas\core\frame.py", line 2688, in __getitem__
    return self._getitem_column(key)
  File "C:\Users\Zhongming\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\pandas\core\frame.py", line 2695, in _getitem_column
    return self._get_item_cache(key)
  File "C:\Users\Zhongming\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\pandas\core\generic.py", line 2489, in _get_item_cache
    values = self._data.get(item)
  File "C:\Users\Zhongming\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\pandas\core\internals.py", line 4115, in get
    loc = self.items.get_loc(item)
  File "C:\Users\Zhongming\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\pandas\core\indexes\base.py", line 3080, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 140, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 162, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1492, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1500, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'Name'
127.0.0.1 - - [09/May/2019 15:58:57] "GET /landing/welcome HTTP/1.1" 500 -

**Comment by daren-thomas** [comment]
@shizhongming the error you posted is not related to the installer but to the dashboard / buggy scenario. In fact, it shows clearly how the installer worked. The dashboard is serving requests, it's just that there is an error inside the CEA code.

**Pull request merged**
