### PR TITLE
Change surroundings-helper to use a concave instead of a convex hull

### PR DESCRIPTION
**Pull request by reyery**
This PR solves #2815 by extract more relevant surrounding buildings based on zone buildings.

The current implementation uses a convex hull to determine the boundary of the zone buildings which does not accurately represent or follow closely to the actual boundary of the zone buildings. This leads to spaces where surrounding buildings are not extracted for zone areas of irregular shape e.g. Basel. See picture below. (Red represents zone while orange represents surrounding buildings)

This is actual not ideal for the radiation simulation since that is the main use for the surrounding buildings, for calculating shading due to nearby buildings. Having surrounding buildings that are so far away from the zone buildings does not make sense since it would likely not affect the radiation on zone buildings.

This new implementation would use a concave hull to determine the boundary instead, which follows more closely to the edges of zone buildings near the edges of the site. This results in buildings that are closer to the zone buildings which is more ideal. I found out that the function actually already exists in the code but was not used. I did some minor changes to the code to make use of it and this is what I got. (Purple represents surrounding buildings extracted using the new method.)

However, one caveat is that this does make it run a little slower, e.g. for the city of Zurich, the current took around 130s while this took around 210s.

image

### CODE REVIEW

**Comment by daren-thomas** [comment]
we will merge this after python3 port

**Comment by daren-thomas** [comment]
I'm not sure this is the expected behavior:

image

**Comment by shanshanhsieh** [comment]
@reyery what is the current status?

**Comment by daren-thomas** [comment]
@reyery any progress?

**Comment by reyery** [comment]
@daren-thomas sorry I'm still working on it. Still finding out ways to do it automatically.

**Comment by reyery** [comment]
This should work now. Right now it uses a spatial join instead of an concave shell to filter the zone buildings from the extracted geometries. It is more accurate (for smaller sites with irregular shape like multiple acute angles) but less efficient. 

Zurich example now takes around 500~ seconds which is at least 3 times slower than the previous method (scales exponentially based on the number of total buildings). But at this point it is a trade off that is acceptable.

**Comment by daren-thomas** [comment]
woah! very nice! works as advertised. good job :-) (I also like how it's _way_ less code!)

**Pull request merged**
