### PR TITLE
Optimization tool box for ArcGIS

### PR DESCRIPTION
**Pull request by BhargavaKrishnaSreepathi**
This PR adds optimization tool box to the ArcGIS interface. It will present under `CityEnergyAnalyst-> Supply Systems Optimization -> Multi Objective Optimization`.

The way it is tested is:

1. Update the config file
2. Go to Anaconda prompt and activate CEA
3. Do `cea install-toolbox`

This should create a addon in ArcGIS in the above mentioned location.

Open it and run the optimization, it might take a little while to run, but if there is an error it will immediately pop up.

### CODE REVIEW

**Comment by BhargavaKrishnaSreepathi** [comment]
@JIMENOFONSECA: I think it is ready to be tested

**Comment by daren-thomas** [comment]
@JIMENOFONSECA @BhargavaKrishnaSreepathi

I can't test this PR because of issue #1100 - basically, the reference case has become unusable for certain scripts.

**Comment by daren-thomas** [comment]
How do I run this tool: "Missing sewage potential of the scenario. Consider running sewage heat exchanger script first" - I've never ever heard of the sewage heat exchanger script and I don't know where to find it. `cea sewage-heat-exchanger`???

**Comment by daren-thomas** [comment]
Turns out there is a script `cea\technologies\sewage_heat_exchanger.py` - but that won't run because:

```
C:\Users\darthoma\AppData\Local\conda\conda\envs\cea\python.exe C:/Users/darthoma/Documents/GitHub/CityEnergyAnalyst/cea/technologies/sewage_heat_exchanger.py
Traceback (most recent call last):
  File "C:/Users/darthoma/Documents/GitHub/CityEnergyAnalyst/cea/technologies/sewage_heat_exchanger.py", line 190, in <module>
    main(cea.config.Configuration())
  File "C:/Users/darthoma/Documents/GitHub/CityEnergyAnalyst/cea/technologies/sewage_heat_exchanger.py", line 186, in main
    calc_sewage_heat_exchanger(locator=locator, config=config, gv=gv)
  File "C:/Users/darthoma/Documents/GitHub/CityEnergyAnalyst/cea/technologies/sewage_heat_exchanger.py", line 50, in calc_sewage_heat_exchanger
    building.Twwf_re_C, building.mcptw_kWperC, building.mcpwwf_kWperC, gv.Cpw,
AttributeError: 'GlobalVariables' object has no attribute 'Cpw'
```

The toolbox needs to add this script too! Otherwise the optimization toolbox can never be run...

**Comment by JIMENOFONSECA** [comment]
Yep. A complete list of the scripts and the order in which they need to be run is in:

http://city-energy-analyst.readthedocs.io/en/latest/cea-workflow-guide.html

On 6 Mar 2018, 22:56 +0800, Daren Thomas <notifications@github.com>, wrote:

Turns out there is a script cea\technologies\sewage_heat_exchanger.py - but that won't run because:

C:\Users\darthoma\AppData\Local\conda\conda\envs\cea\python.exe C:/Users/darthoma/Documents/GitHub/CityEnergyAnalyst/cea/technologies/sewage_heat_exchanger.py
Traceback (most recent call last):
  File "C:/Users/darthoma/Documents/GitHub/CityEnergyAnalyst/cea/technologies/sewage_heat_exchanger.py", line 190, in <module>
    main(cea.config.Configuration())
  File "C:/Users/darthoma/Documents/GitHub/CityEnergyAnalyst/cea/technologies/sewage_heat_exchanger.py", line 186, in main
    calc_sewage_heat_exchanger(locator=locator, config=config, gv=gv)
  File "C:/Users/darthoma/Documents/GitHub/CityEnergyAnalyst/cea/technologies/sewage_heat_exchanger.py", line 50, in calc_sewage_heat_exchanger
    building.Twwf_re_C, building.mcptw_kWperC, building.mcpwwf_kWperC, gv.Cpw,
AttributeError: 'GlobalVariables' object has no attribute 'Cpw'


The toolbox needs to add this script too! Otherwise the optimization toolbox can never be run...

**Comment by BhargavaKrishnaSreepathi** [comment]
@daren-thomas @JIMENOFONSECA: Regarding this PR, should I make changes such that the optimization script checks all of these things, or just simply direct the user to the guide on which scripts need to be run?

**Comment by JIMENOFONSECA** [comment]
I think, just changes in the optimisation script.

On 7 Mar 2018, 12:50 PM +0800, Bhargava Krishna Sreepathi <notifications@github.com>, wrote:

@daren-thomas<https://github.com/daren-thomas> @JIMENOFONSECA<https://github.com/jimenofonseca>: Regarding this PR, should I make changes such that the optimization script checks all of these things, or just simply direct the user to the guide on which scripts need to be run?

**Comment by JIMENOFONSECA** [comment]
I meant that it is ok as it is.

**Comment by JIMENOFONSECA** [comment]
@daren-thomas I wonder if this is ready to merge now

**Comment by JIMENOFONSECA** [comment]
@daren-thomas we fixed issue #1100 so I think we can move this forward

**Comment by daren-thomas** [comment]
@JIMENOFONSECA: `ImportError: No module named utm` - not quite ready yet, but fixable... i'm on it!

**Comment by daren-thomas** [comment]
@JIMENOFONSECA well... i still don't think the point of the sewage heat exchange script has been addressed yet.

my point is this: i think it is a _bug_ to add a tool to the cea toolbox that can't be used. it can't be used, because it depends on a tool having been run that can't be run from the toolbox. so. i suggest we add an interface for the sewage heat exchanger too. i'll add this to this branch - i think it's a small thing to do anyways...

**Comment by daren-thomas** [comment]
It seems, this needs to be checked for too: `IOError: File C:\reference-case-open\baseline\outputs\data\optimization\network\layout\DH__AllEdges.csv does not exist` - the thermal network matrix needs to be run. should we wait for lenny's changes? so we can add a tool for that too?

**Comment by JIMENOFONSECA** [comment]
@daren-thomas I think Lenny's changes will come after. So it will be good if we add the next tools straightaway. Could we put also this as the top priority? It should be merged by 30th of March.

- Thermal_network_matrix.py
- Sewage_potential
- optimization.py

**Comment by daren-thomas** [comment]
@JIMENOFONSECA I added a tool for the sewage heat exchanger to this pull request. I am adding the thermal network matrix to the multiprocessing thermal network matrix pull request (#1140) - i think that has come a long way and can probably be merged this week!

What I don't know is this: For each of the three tools I need to know the following information:

- label (as it will show up in ArcGIS interface)
- description (a help line)
- category (the first level in the arcgis interface toolbox hierarchy)

I have made assumptions for this missing information. Please check and adjust accordingly.

**Comment by JIMENOFONSECA** [comment]
@daren-thomas @BhargavaKrishnaSreepathi I am not able to test weather the toolbox works or not in ArcGIS. Everytime I run cea install-toolbox, cea installs the toolbox in V2.7 but not the one of my branch.

I am in the branch optimization-tool-box.

Thing I tried:
- I tried to erase the toolbox from arcgis and do the process again.
- I did in the repository pip install .[dev]
- i tried several times to do cea install-toolbox which runs ok.

**Comment by JIMENOFONSECA** [comment]
@daren-thomas @BhargavaKrishnaSreepathi I fixed the problem with help of Bhargava. I am waiting for the tests to pass and then we can merge. Great work you guys.

**Comment by daren-thomas** [comment]
@JIMENOFONSECA - did you do `activate cea` first? sounds like you installed the cea with pip install (without the `-e .`)

**Pull request merged**
