### PR TITLE
Fixing cea optimization plots

### PR DESCRIPTION
**Pull request by BhargavaKrishnaSreepathi**
This PR modifies the optimization plots to be compatible with the updated optimization results.

This PR solves the issue #1762.

The way to test is generate optimization results and then run the `cea\plots\optimization\main.py`

@daren-thomas: do let me know if it fixes the problem you are already encountering.

This is second PR as part of the CONCEPT project and also continuous efforts on improving CEA

### CODE REVIEW

**Comment by JIMENOFONSECA** [comment]
@daren-thomas i assign this review to you since this is a bottle neck for you

**Comment by daren-thomas** [comment]
@JIMENOFONSECA I'm working on it. it's going to take forever to get a cooling case ready to test, so some patience will be required.

@BhargavaKrishnaSreepathi you could speed that process up by sending me a case study to use.

**Comment by daren-thomas** [comment]
I'm trying to get the input data to test this, but I have the following problems:

- `cea network-layout` fails with the message "networkx.exception.NetworkXError: G is not a connected graph. metric_closure is not defined."

- `cea thermal-network` fails with the message "ImportError: cannot import name FULL_COOLING_SYSTEMS_LIST"

Steps to reproduce:

- extract the bundled reference-case "reference-case-WTP.zip"
- select the scenario "C:\reference-case-WTP\MIX_low_density"
- run data-helper, demand
- run all the scripts in the energy potentials category (solar-collector etc.)
- run `cea network-layout` (see above for error message) - @shanshanhsieh do you have any idea?
- run `cea thermal-network` (see above for error message) - @JIMENOFONSECA I think this is related to your work?

**Comment by JIMENOFONSECA** [comment]
@daren-thomas are you receiving the same problem still?

**Comment by daren-thomas** [comment]
@JIMENOFONSECA no, I'm getting a new error:

```
C:\Users\darthoma\Documents\GitHub\CityEnergyAnalyst (fixing-cea-optimization-plots)
(cea) λ cea plots-optimization --network-type DC
City Energy Analyst version 2.9.2
Running `cea plots-optimization` with the following parameters:
- general:region = SG
  (default: CH)
- general:scenario = c:\reference-case-WTP\WTP_CBD_h
  (default: C:\reference-case-open\baseline)
- plots-optimization:generation = 2
  (default: 3)
- plots-optimization:network-type = DC
  (default: DC)
- plots-optimization:multicriteria = True
  (default: True)
- plots-optimization:categories = ['pareto_curve', 'system_sizes', 'costs_analysis']
  (default: ['pareto_curve', 'system_sizes', 'costs_analysis'])
Running dashboard with scenario = c:\reference-case-WTP\WTP_CBD_h
Running dashboard with the next generation = 2
8
Traceback (most recent call last):
  File "c:\Users\darthoma\Miniconda2\envs\cea\Scripts\cea-script.py", line 11, in <module>
    load_entry_point('cityenergyanalyst', 'console_scripts', 'cea')()
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\interfaces\cli\cli.py", line 65, in main
    script_module.main(config)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\plots\optimization\main.py", line 644, in main
    plots_main(locator, config)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\plots\optimization\main.py", line 54, in plots_main
    data_address = locating_individuals_in_generation_script(generation, locator)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\analysis\multicriteria\optimization_post_processing\locating_individuals_in_generation_script.py", line 60, in locating_individuals_in_generation_script
    data_generation = preprocessing_generations_data(locator, generation)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\analysis\multicriteria\optimization_post_processing\locating_individuals_in_generation_script.py", line 172, in preprocessing_generations_data
    df_network = pd.DataFrame({'Name': individual_names_HOF, "network": dict_network}).set_index("Name")
  File "C:\Users\darthoma\Miniconda2\envs\cea\lib\site-packages\pandas\core\frame.py", line 348, in __init__
    mgr = self._init_dict(data, index, columns, dtype=dtype)
  File "C:\Users\darthoma\Miniconda2\envs\cea\lib\site-packages\pandas\core\frame.py", line 459, in _init_dict
    return _arrays_to_mgr(arrays, data_names, index, columns, dtype=dtype)
  File "C:\Users\darthoma\Miniconda2\envs\cea\lib\site-packages\pandas\core\frame.py", line 7356, in _arrays_to_mgr

    index = extract_index(arrays)
  File "C:\Users\darthoma\Miniconda2\envs\cea\lib\site-packages\pandas\core\frame.py", line 7402, in extract_index
    raise ValueError('arrays must all be same length')
ValueError: arrays must all be same length
```

**Comment by JIMENOFONSECA** [comment]
Mmm. I can try to solve it right away tomorrow morning. Are there any steps i should follow to replicate this?
On 4 Mar 2019, 19:30 +0800, Daren Thomas <notifications@github.com>, wrote:

@JIMENOFONSECA<https://github.com/JIMENOFONSECA> no, I'm getting a new error:

C:\Users\darthoma\Documents\GitHub\CityEnergyAnalyst (fixing-cea-optimization-plots)

(cea) λ cea plots-optimization --network-type DC

City Energy Analyst version 2.9.2

Running `cea plots-optimization` with the following parameters:

- general:region = SG

  (default: CH)

- general:scenario = c:\reference-case-WTP\WTP_CBD_h

  (default: C:\reference-case-open\baseline)

- plots-optimization:generation = 2

  (default: 3)

- plots-optimization:network-type = DC

  (default: DC)

- plots-optimization:multicriteria = True

  (default: True)

- plots-optimization:categories = ['pareto_curve', 'system_sizes', 'costs_analysis']

  (default: ['pareto_curve', 'system_sizes', 'costs_analysis'])

Running dashboard with scenario = c:\reference-case-WTP\WTP_CBD_h

Running dashboard with the next generation = 2

8

Traceback (most recent call last):

  File "c:\Users\darthoma\Miniconda2\envs\cea\Scripts\cea-script.py", line 11, in <module>

    load_entry_point('cityenergyanalyst', 'console_scripts', 'cea')()

  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\interfaces\cli\cli.py", line 65, in main

    script_module.main(config)

  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\plots\optimization\main.py", line 644, in main

    plots_main(locator, config)

  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\plots\optimization\main.py", line 54, in plots_main

    data_address = locating_individuals_in_generation_script(generation, locator)

  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\analysis\multicriteria\optimization_post_processing\locating_individuals_in_generation_script.py", line 60, in locating_individuals_in_generation_script

    data_generation = preprocessing_generations_data(locator, generation)

  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\analysis\multicriteria\optimization_post_processing\locating_individuals_in_generation_script.py", line 172, in preprocessing_generations_data

    df_network = pd.DataFrame({'Name': individual_names_HOF, "network": dict_network}).set_index("Name")

  File "C:\Users\darthoma\Miniconda2\envs\cea\lib\site-packages\pandas\core\frame.py", line 348, in __init__

    mgr = self._init_dict(data, index, columns, dtype=dtype)

  File "C:\Users\darthoma\Miniconda2\envs\cea\lib\site-packages\pandas\core\frame.py", line 459, in _init_dict

    return _arrays_to_mgr(arrays, data_names, index, columns, dtype=dtype)

  File "C:\Users\darthoma\Miniconda2\envs\cea\lib\site-packages\pandas\core\frame.py", line 7356, in _arrays_to_mgr



    index = extract_index(arrays)

  File "C:\Users\darthoma\Miniconda2\envs\cea\lib\site-packages\pandas\core\frame.py", line 7402, in extract_index

    raise ValueError('arrays must all be same length')

ValueError: arrays must all be same length

**Comment by JIMENOFONSECA** [comment]
Btw, could you write a unittest that runs all the plots in the mean time? They just need to run as a first step.

This will help us a lot since there is a big PR bhargava and I will submit soon, which will touch optimization. Since he is leaving soon, we need to give priority to that.
On 4 Mar 2019, 19:30 +0800, Daren Thomas <notifications@github.com>, wrote:

@JIMENOFONSECA<https://github.com/JIMENOFONSECA> no, I'm getting a new error:

C:\Users\darthoma\Documents\GitHub\CityEnergyAnalyst (fixing-cea-optimization-plots)

(cea) λ cea plots-optimization --network-type DC

City Energy Analyst version 2.9.2

Running `cea plots-optimization` with the following parameters:

- general:region = SG

  (default: CH)

- general:scenario = c:\reference-case-WTP\WTP_CBD_h

  (default: C:\reference-case-open\baseline)

- plots-optimization:generation = 2

  (default: 3)

- plots-optimization:network-type = DC

  (default: DC)

- plots-optimization:multicriteria = True

  (default: True)

- plots-optimization:categories = ['pareto_curve', 'system_sizes', 'costs_analysis']

  (default: ['pareto_curve', 'system_sizes', 'costs_analysis'])

Running dashboard with scenario = c:\reference-case-WTP\WTP_CBD_h

Running dashboard with the next generation = 2

8

Traceback (most recent call last):

  File "c:\Users\darthoma\Miniconda2\envs\cea\Scripts\cea-script.py", line 11, in <module>

    load_entry_point('cityenergyanalyst', 'console_scripts', 'cea')()

  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\interfaces\cli\cli.py", line 65, in main

    script_module.main(config)

  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\plots\optimization\main.py", line 644, in main

    plots_main(locator, config)

  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\plots\optimization\main.py", line 54, in plots_main

    data_address = locating_individuals_in_generation_script(generation, locator)

  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\analysis\multicriteria\optimization_post_processing\locating_individuals_in_generation_script.py", line 60, in locating_individuals_in_generation_script

    data_generation = preprocessing_generations_data(locator, generation)

  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\analysis\multicriteria\optimization_post_processing\locating_individuals_in_generation_script.py", line 172, in preprocessing_generations_data

    df_network = pd.DataFrame({'Name': individual_names_HOF, "network": dict_network}).set_index("Name")

  File "C:\Users\darthoma\Miniconda2\envs\cea\lib\site-packages\pandas\core\frame.py", line 348, in __init__

    mgr = self._init_dict(data, index, columns, dtype=dtype)

  File "C:\Users\darthoma\Miniconda2\envs\cea\lib\site-packages\pandas\core\frame.py", line 459, in _init_dict

    return _arrays_to_mgr(arrays, data_names, index, columns, dtype=dtype)

  File "C:\Users\darthoma\Miniconda2\envs\cea\lib\site-packages\pandas\core\frame.py", line 7356, in _arrays_to_mgr



    index = extract_index(arrays)

  File "C:\Users\darthoma\Miniconda2\envs\cea\lib\site-packages\pandas\core\frame.py", line 7402, in extract_index

    raise ValueError('arrays must all be same length')

ValueError: arrays must all be same length

**Comment by daren-thomas** [comment]
@JIMENOFONSECA reproduction steps are easy:

- i unzipped the scenario @BhargavaKrishnaSreepathi gave me (i can paste you the link on slack if you like)
- i used `cea-config demand --scenario c:\reference-case-WTP\WTP_CBD_h` to set the scenario also checked network-type etc.
- i ran `cea optimize`
- then i ran the command quoted above

Regarding the Unittests: Could you create the issue? It's a bit bigger than "just write some unit tests" as we currently don't run all the scripts yet, so the whole optimization stuff won't work etc. So no, I can't quickly implement it. But we can schedule the task for an upcoming sprint.

**Comment by JIMENOFONSECA** [comment]
@daren-thomas regarding your first issue on the network layout and thermal_matrix I just made some commits that should fix this. Please try again

**Comment by JIMENOFONSECA** [comment]
@BhargavaKrishnaSreepathi we are getting this error, https://github.com/architecture-building-systems/CityEnergyAnalyst/pull/1810#issuecomment-469219637

any idea what could this be?

**Comment by BhargavaKrishnaSreepathi** [comment]
I need to run it and see, nothing I can think of from the top of my head. Let me take a look

**Comment by BhargavaKrishnaSreepathi** [comment]
hey @shanshanhsieh, you can use this branch to run the optimization plots. Do remember to rerun optimization to test in this

**Pull request merged**
