### PR TITLE
I1600 electric and thermal network planning

### PR DESCRIPTION
**Pull request by BhargavaKrishnaSreepathi**
This PR, includes the final piece of code developed under the CONCEPT project. This runs the electrical grid optimization, uses it as the input for thermal network calculations and then iterates further to find the best network for a given set of buildings and streets.

The way to test this is to run `cea\optimization\flexibility_model\electrical_and_thermal_grid_planning\electrical_thermal_optimization_main.py`. The outputs will be saved in the `scenario\outputs\electrical_and_thermal_network` folder. 

Do read the `README.MD` before testing the PR.

The computational time might go to about 5-7 hours, depending on the generations and the individuals.

This also creates a config section `electrical-thermal-optimization`, where in the optimization parameters are specified.

### CODE REVIEW

**Comment by daren-thomas** [comment]
@shanshanhsieh @JIMENOFONSECA what is the status here? ready to merge?

**Comment by JIMENOFONSECA** [comment]
@shanshanhsieh I imagine this is ready to merge now right?, would you do the honors please?

**Comment by shanshanhsieh** [comment]
@JIMENOFONSECA the documentation from my part is finished.
but yesterday i tried to run the script in order to see the outputs, and it's not finished yet... how long does it take normally?

**Comment by daren-thomas** [comment]
@shanshanhsieh @JIMENOFONSECA what is the status of this? can we merge this into release 2.12? or wait for 2.13?

**Comment by daren-thomas** [comment]
Comment by @shanshanhsieh: script is not actually running, @BhargavaKrishnaSreepathi is looking into it.

**Pull request merged**
