### PR TITLE
1238 glossary terms and databases

### PR DESCRIPTION
**Pull request by Jack-Hawthorne**
updated the glossary to reflect the latest version

added a preamble to explain the database types and why they exist.

also created a code schedule (code_ref.rst) to define the various system bins (T1...Tn) to avoid confusion.

feedback welcome (might be worth mentioning the default case specific databases as the minimum required)

### CODE REVIEW

**Comment by daren-thomas** [comment]
Can one of the admins verify this patch?

**Comment by JIMENOFONSECA** [comment]
@Jack-Hawthorne please ask @amraladdin personally how databases in CEA are organized. He is doing a lecture about this. So things should be synchronized by the 15th of June (we will start printing the glossary and @amraladdin lecture.  It would be good if you two sit together as soon as possible (I believe Amr will need your help Jack to navigate into how the glossary looks like).

**Comment by daren-thomas** [comment]
@Jack-Hawthorne could you please push your results so far?

**Comment by Jack-Hawthorne** [comment]
@daren-thomas @JIMENOFONSECA @amraladdin 
hey fellas, feel free to check out the latest glossary build.
as always, feedback welcome

**Pull request merged**
