### PR TITLE
967 dashboard plots

### PR DESCRIPTION
**Pull request by daren-thomas**
Implements:
- #1307 (Define landing page for dashboard) in MVP fashion
- #1318 (Add plot title name in dashboard)

Contains:
- updated installation guide

To run:
- install according to installation guide
- run `cea dashboard` from anaconda prompt

### CODE REVIEW

**Comment by JIMENOFONSECA** [comment]
@daren-thomas just assign this PR to me when you consider it ready

**Comment by daren-thomas** [comment]
@JIMENOFONSECA actually, added #1712 - it's all one repository now.

**Comment by JIMENOFONSECA** [comment]
I go the following error. To replicate do:

1. shift to this branch.
2. in anaconda prompt, activate cea.
3. navigate to cityenergyanalyst repository
4. do conda env update.
5. do pip install - e .[dev]



image

**Comment by JIMENOFONSECA** [comment]
@daren-thomas I tried today to run cea dashboard again and get the same error. I did this after reinstalling CEA from this branch.  i tried:

1. conda env update
2. pip install -e .[dev]
3. cea dashboard

image

**Comment by JIMENOFONSECA** [comment]
@daren-thomas I am trying to install form the new environment you provided. It takes 3 hours and it has not even downloaded more than 1 package. Any advise?

image

**Comment by JIMENOFONSECA** [comment]
@daren-thomas I solved this by changing the route to the packages. It seems some servers are quite slow in singapore

**Comment by daren-thomas** [comment]
> @daren-thomas I solved this by changing the route to the packages. It seems some servers are quite slow in singapore

@JIMENOFONSECA what do you mean by "changing the route to the packages"?

**Pull request merged**
