### PR TITLE
Fix various typos

### PR DESCRIPTION
**Pull request by luzpaz**
**Describe the PR**

This PR fixes various typos in the source tree.  
Found via `codespell -q 3 -S ./CHANGELOG.md -L bu,exitt,lod,modul,te,thi,wee`

**To Test**

n/a

**Expected behaviour**

Documentation and code with less typos.

**Extra Data Needed**

n/a

### CODE REVIEW

**Comment by shanshanhsieh** [comment]
Can one of the admins verify this patch?

**Comment by luzpaz** [comment]
Note: there are typos in `notebooks/2637-single-point-of-reference-for-variables.ipynb`. Shall I submit a fix for that in this PR ?

**Review by MatNif — APPROVED** [review]
All instances of the typo-correction are valid.
All of them also occur in either in-line comments, header comments, print statements, error statements or doc-files. Therefore none of the changes will affect the functioning of the code. The changes can be pulled to the main branch imo.

**Review by MatNif — APPROVED** [review]
All changes are valid corrections of typos.
None of them affect the functioning of the code in any way.
I will therefore merge this PR.

**Pull request merged**
