### PR TITLE
I1331 pv panels fail to run

### PR DESCRIPTION
**Pull request by shanshanhsieh**
This PR resolves issue #1329, #1331, #1332 
Changes include: 
1. maximum radiation received on surface setting
2. radiation on surface threshold (from percentage to a fixed number, it was suggested during the test run, part of #1245)

To test:
1. delete `cea.config`
2. change region/weather to SIN/Singapore-2016
3. `install_toolbox`
4. run `photovoltaic.py`, `solar_collectors.py`, `PVT` tools from ArcGIS

### CODE REVIEW

**Comment by shanshanhsieh** [comment]
@JIMENOFONSECA please put this to the first priority to merge, reason is @amraladdin and @ongbolie will need this to proceed with their testings. Thank you!

**Comment by JIMENOFONSECA** [comment]
@ongbolie does this work for you?

**Comment by amraladdin** [comment]
I Checked the PV and PV/T Component, didn't work. I did the exact following steps:
- Synchronized master branch.
- Type cd Documents\Github\CityEnergyAnalyst
- Type activate cea
- Type cea install-toolbox

Then ran Data Helper, Demand forcast (Radiation already run) and then the PV component.

*Unfortunately, it still doesn't work, and I got the following error (PV component)*


Executing: PhotovoltaicPanelsTool C:\reference-case\reference-case-WTP\RES_low_density Singapore-2016 c:\Users\aelesawy\documents\GitHub\cityenergyanalyst\cea\databases\weather\Singapore-2016.epw 01.01.2016 PV1 true true 0.75 4
Start Time: Thu May 17 10:03:56 2018
Running script PhotovoltaicPanelsTool...
Executing: C:\ProgramData\Miniconda2\envs\cea\python.exe -u -m cea.interfaces.cli.cli photovoltaic --panel-on-roof true --scenario C:\reference-case\reference-case-WTP\RES_low_density --type-pvpanel PV1 --solar-window-solstice 4 --weather c:\users\aelesawy\documents\github\cityenergyanalyst\cea\databases\weather\Singapore-2016.epw --panel-on-wall true --date-start 2016-01-01 --min-radiation 0.75
Running photovoltaic with scenario = C:\reference-case\reference-case-WTP\RES_low_density
Running photovoltaic with date-start = 2016-01-01 00:00:00
Running photovoltaic with dpl = 200.0
Running photovoltaic with eff-pumping = 0.6
Running photovoltaic with fcr = 1.3
Running photovoltaic with k-msc-max = 0.217
Running photovoltaic with min-radiation = 0.75
Running photovoltaic with panel-on-roof = True
Running photovoltaic with panel-on-wall = True
Running photovoltaic with ro = 1000.0
Running photovoltaic with solar-window-solstice = 4
Running photovoltaic with t-in-pvt = 35.0
Running photovoltaic with t-in-sc = 75.0
Running photovoltaic with type-pvpanel = PV1
Running photovoltaic with type-scpanel = SC1
reading weather data done
calculating solar properties done
gathering properties of PV panel
filtering low potential sensor points done
calculating optimal tile angle and separation done
generating groups of sensor points done
B001 done - time elapsed: 1.65 seconds
reading weather data done
calculating solar properties done
gathering properties of PV panel
filtering low potential sensor points done
GB not in expected range
GB not in expected range
GB not in expected range
GB not in expected range
GB not in expected range
GB not in expected range
GB not in expected range
GB not in expected range
GB not in expected range
GB not in expected range
GB not in expected range
GB not in expected range
GB not in expected range
GB not in expected range
GB not in expected range
GB not in expected range
GB not in expected range
GB not in expected range
GB not in expected range
GB not in expected range
GB not in expected range
GB not in expected range
GB not in expected range
GB not in expected range
c:\users\aelesawy\documents\github\cityenergyanalyst\cea\utilities\solar_equations.py:229: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  sensors_rad_clean[sensors_rad_clean[:] <= 50] = 0  # eliminate points when hourly production < 50 W/m2
C:\ProgramData\Miniconda2\envs\cea\lib\site-packages\pandas\core\frame.py:2366: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._where(-key, value, inplace=True)
Traceback (most recent call last):
  File "C:\ProgramData\Miniconda2\envs\cea\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\ProgramData\Miniconda2\envs\cea\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "c:\users\aelesawy\documents\github\cityenergyanalyst\cea\interfaces\cli\cli.py", line 79, in <module>
    main(cea.config.Configuration())
  File "c:\users\aelesawy\documents\github\cityenergyanalyst\cea\interfaces\cli\cli.py", line 33, in main
    script_module.main(config)
  File "c:\users\aelesawy\documents\github\cityenergyanalyst\cea\technologies\solar\photovoltaic.py", line 755, in main
    longitude=longitude, weather_path=config.weather, building_name=building, )
  File "c:\users\aelesawy\documents\github\cityenergyanalyst\cea\technologies\solar\photovoltaic.py", line 83, in calc_PV
    max_yearly_radiation, panel_properties_PV)
  File "c:\users\aelesawy\documents\github\cityenergyanalyst\cea\utilities\solar_equations.py", line 306, in optimal_angle_and_tilt
    sensors_metadata_clean.total_rad_Whm2, Max_Isol_Whperm2yr)
  File "C:\ProgramData\Miniconda2\envs\cea\lib\site-packages\numpy\lib\function_base.py", line 2734, in __call__
    return self._vectorize_call(func=func, args=vargs)
  File "C:\ProgramData\Miniconda2\envs\cea\lib\site-packages\numpy\lib\function_base.py", line 2816, in _vectorize_call
    for x, t in zip(outputs, otypes)])
TypeError: long() argument must be a string or a number, not 'NoneType'


Traceback (most recent call last):
  File "C:\Users\aelesawy\AppData\Roaming\ESRI\Desktop10.4\ArcToolbox\My Toolboxes\cea\interfaces\arcgis\arcgishelper.py", line 77, in execute
    run_cli(self.cea_tool, **kwargs)
  File "C:\Users\aelesawy\AppData\Roaming\ESRI\Desktop10.4\ArcToolbox\My Toolboxes\cea\interfaces\arcgis\arcgishelper.py", line 164, in run_cli
    raise Exception('Tool did not run successfully')
Exception: Tool did not run successfully

Failed to execute (PhotovoltaicPanelsTool).
Failed at Thu May 17 10:04:00 2018 (Elapsed Time: 3.64 seconds)

**Comment by amraladdin** [comment]
Should I just try uninstalling miniconda, arcGIS and CEA and reinstall all of them again from the beginning and see if this will work?

**Comment by JIMENOFONSECA** [comment]
Hi Amr,

Just wait for PR #1338 to pass. It will work the problem of PV. It should be done soon.

Jimeno

On 17 May 2018, 4:10 PM +0800, Amr Elesawy <notifications@github.com>, wrote:

Should I just try uninstalling miniconda, arcGIS and CEA and reinstall all of them again from the beginning and see if this will work?

**Comment by amraladdin** [comment]
Perfect!

**Comment by shanshanhsieh** [comment]
@jimeno this branch is ready to be merged

**Pull request merged**
