### PR TITLE
1828 make one for all installer for windows

### PR DESCRIPTION
**Pull request by daren-thomas**
This PR implements an installer for Windows.

Try this: https://www.dropbox.com/s/3l67vmd90f7pn6m/Setup_CityEnergyAnalyst_2.12.0a3.exe?dl=0

I'll add more information on how to create the installer (setup NSIS etc.), what it does exactly and documentation for the website tomorrow. Just a sneak peak for now :)

(check out the start menu when done for the nifty cea shortcuts)

### CODE REVIEW

**Comment by JIMENOFONSECA** [comment]
A couple of comments while testing: 
1. we might want to put the credits in here and the year of the copyright from 2016-2019
image

**Comment by JIMENOFONSECA** [comment]
Another issue is that the icon has a white background. It should be transparent right? Take a look at the corners. thanks!

image

**Comment by JIMENOFONSECA** [comment]
I believe I had implemented the option to open automatically the cea interface. Now when I click CEA dashboard it opens this. 

I believe it should directly open the browser (no the console). We can open the console with other executable as I see, right?

image

**Comment by JIMENOFONSECA** [comment]
4th issue. The last three issues where found while running CEA with development version installed. I also did a separate installation and saved it in the folder CityEnergyAnalyst2.

I run the console and try to run the dashboard. It does not work. 
image


I also tried to run the CEA dashboard directly form the executeble. and it does not work (it opens the console and closes it quickly)

**Comment by JIMENOFONSECA** [comment]
5th Issue: Daysim does not work. I think this has to do with the fact that C:/Daysim/bin (a parameter inside the solar radiation tool. does not exist anymore. I believe CEA should then know that daysim is installed in the cea/dependencies folder?

image

**Comment by daren-thomas** [comment]
@JIMENOFONSECA thank you for the feedback! yep. there are still a couple of issues. btw: the license agreement is taken from the LICENCE file in our root folder. that needs to be updated too! i have created a separate issue for that (#1912). The credits could be shown on a separate page. But I don't think they improve the usability and nobody is going to check the installer to figure out the credits, so i think that's maybe just a vanity project.

I have asked @shizhongming on slack to provide a gradient towards dark - the background really is transparent, but the icons have a gradient towards the background. maybe the gradient is not necessary at all...

regarding 3rd issue: that's actually fixed in this pull request already - but you'd have to use the development version and switch that repo to this branch for the changes to be visible - a bit of a chicken and egg problem that maybe easier to solve with a quick merge and then work out the issues as separate issues incrementally?

regarding 4th issue: i have created an issue for that. (#1913)

regarding 5th issue: yes. i am aware of this. the installer bundles daysim binaries, but i'm not sure if i have everything yet. (#1914)

Since these issues don't really break existing things in the CEA, I propose merging this PR, but not closing the issue, instead, makinging #1828 dependent on these issues being resolved. That way, we can have smaller pull requests, each addressing a specific issue.

**Pull request merged**
