### PR TITLE
I351 calibrator cea

### PR DESCRIPTION
**Pull request by JIMENOFONSECA**

### CODE REVIEW

**Comment by JIMENOFONSECA** [comment]
@daren-thomas would you mind taking a look at this? I add it a readme with instructions. This code will only run in 64 bit. it took me about a week of trial and error fixing Memory Errors in Numpy in the 32 bit version. I just moved to the 64 bit version and all works.

I did:
- Install anaconda 64 bits,
- install environment 64 bits,
- install packages from conda install. The only thing is to be sure that we install PyMC3 3.1

and that's it...should we consider moving to 64 bit? it will solve many problems to come due to memory requests above 2 GB from the emulators and NN. I think @Khayatian agrees on this?

**Comment by Khayatian** [comment]
@JIMENO does this mean that we will also be moving to python 3.5? or is it just moving to a 64 bit architecture? I was wondering whether it will also help with moving from theano to TF.

**Comment by JIMENOFONSECA** [comment]
Daren, could be python 3.5 an option?


On 26 Jul 2017, at 6:01 pm, Fazel Khayatian <notifications@github.com<mailto:notifications@github.com>> wrote:


@jimeno<https://github.com/jimeno> does this mean that we will also be moving to python 3.5? or is it just moving to a 64 bit architecture? I was wondering whether it will also help with moving from theano to TF.

**Comment by daren-thomas** [comment]
I would rather not right now: First move to 64 bit. Porting to 3.5 is a separate effort that might take quite a while and include rewriting some stuff as the language changed quite a bit. I don't know python3 yet so I won't be of much help until I get stuck into it.

**Comment by daren-thomas** [comment]
@JIMENOFONSECA: This calculates different results to the master branch. Any ideas? Which one to use?

(might be a problem of the archetypes not being consistent?)

```
C:\Users\darthoma\Documents\GitHub\CityEnergyAnalyst (i351-calibrator-cea)
λ cea test
failed to import from rc_model_sia_cc.pyd, falling back to pure python functions
failed to import from storagetank_cc.pyd, falling back to pure python functions
.  run_unit_tests
........FF
======================================================================
FAIL: test_mixed_use_archetype_values (test_schedules.TestBuildingPreprocessing)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\tests\test_schedules.py", line 45, in test_mixed_use_archetype_values
    self.assertAlmostEqual(value, calculated_results[column][building], 4)
AssertionError: 198.75 != 208.9473684210526 within 4 places

======================================================================
FAIL: test_mixed_use_schedules (test_schedules.TestScheduleCreation)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\tests\test_schedules.py", line 81, in test_mixed_use_schedules
    reference_results[schedule]))
AssertionError: Schedule 'El' at time 3456, 0.108039 != 0.231863

----------------------------------------------------------------------
Ran 10 tests in 25.654s

FAILED (failures=2)
########################################
TaskFailed - taskid:run_unit_tests
Python Task failed: '<function run_unit_tests at 0x0000000003F8C908>' returned False

read input files
done
failed to import from calc_radiator.pyd, falling back to pure python functions
(6192.0, 3216.0)
```

**Comment by JIMENOFONSECA** [comment]
@daren-thomas im getting this error message, what does tokkenize mean here?

image

**Comment by daren-thomas** [comment]
Are you still getting that error message? it seams the format of the surface properties file is not what the csv parser is expecting.

**Comment by JIMENOFONSECA** [comment]
Yep, still. I do not know, maybe it changed.. let me check if we are using another one or something.

Best, Jimeno

On 20 Sep 2017, at 16:56, Daren Thomas <notifications@github.com<mailto:notifications@github.com>> wrote:


Are you still getting that error message? it seams the format of the surface properties file is not what the csv parser is expecting.

**Comment by JIMENOFONSECA** [comment]
@daren-thomas do you get the same error? is it happenning while running the open or the zug case?

**Comment by daren-thomas** [comment]
yes, i am still getting the same error. it happens in the open case.

**Comment by JIMENOFONSECA** [comment]
@daren-thomas working, could you merge this? btw, when will Jenkins be back? it has been a while without him.

**Comment by daren-thomas** [comment]
For acceptance tests / integration tests of this, see issue #420

**Comment by daren-thomas** [comment]
the files were found! so. main gripe is the warnings. i updated the environment file to include `pymc3`.

**Comment by JIMENOFONSECA** [comment]
@daren-thomas yes, unfortunatelly it would take ages to take out that message. it does not affect functionality, it is just that the PyMC3 guys are warning that it will not work in future versions of pymc3. but if we keep the current version. it will work for sure. I think we go ahead, and solve this problem in due time.

**Comment by daren-thomas** [comment]
this works on my computer!

**Pull request merged**
