### PR TITLE
I1138 plots cea arcgis

### PR DESCRIPTION
**Pull request by JIMENOFONSECA**
this solves #1138 @BhargavaKrishnaSreepathi would you mind checking this? You will need to have run all CEA first.

### CODE REVIEW

**Comment by BhargavaKrishnaSreepathi** [comment]
Hi @JIMENOFONSECA, i got the following error. I ran the potentials, demand followed by optimization scripts.

Executing: Plots C:\reference-case-open\baseline C:/reference-case-open/baseline # solar_potentials;solar_technology_potentials;energy_demand;optimization;life_cycle;scenarios_comparisons;thermal_network 1;2;3 ind1 DH #
Start Time: Thu Mar 29 15:21:27 2018
Running script Plots...
Executing: c:\users\bhargava\anaconda2\envs\cea\python.exe -u -m cea.interfaces.cli.cli plots --buildings  --network-names  --scenario C:\reference-case-open\baseline --network-type DH --scenarios C:/reference-case-open/baseline --individual ind1 --generations 1, 2, 3 --categories solar_potentials, solar_technology_potentials, energy_demand, optimization, life_cycle, scenarios_comparisons, thermal_network
Running plots for the next categories = ['solar_potentials', 'solar_technology_potentials', 'energy_demand', 'optimization', 'life_cycle', 'scenarios_comparisons', 'thermal_network']
solar potential plots successfully saved in plots folder of scenario:  C:\reference-case-open\baseline
technology potential plots successfully saved in plots folder of scenario:  C:\reference-case-open\baseline
done - time elapsed: 12.2f seconds
energy demand plots successfully saved in plots folder of scenario:  C:\reference-case-open\baseline
c:\users\bhargava\anaconda2\envs\cea\lib\site-packages\pandas\core\series.py:1295: RuntimeWarning:

invalid value encountered in rint

Traceback (most recent call last):
  File "c:\users\bhargava\anaconda2\envs\cea\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\users\bhargava\anaconda2\envs\cea\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "c:\users\bhargava\documents\github\ceaforarcgis\cea\interfaces\cli\cli.py", line 79, in <module>
    main(cea.config.Configuration())
  File "c:\users\bhargava\documents\github\ceaforarcgis\cea\interfaces\cli\cli.py", line 33, in main
    script_module.main(config)
  File "c:\users\bhargava\documents\github\ceaforarcgis\cea\plots\plots_main.py", line 76, in main
    plots_main(config)
  File "c:\users\bhargava\documents\github\ceaforarcgis\cea\plots\plots_main.py", line 50, in plots_main
    plots_lca(locator, config)
  File "c:\users\bhargava\documents\github\ceaforarcgis\cea\plots\life_cycle\main.py", line 32, in plots_main
    plots = Plots(locator, buildings)
  File "c:\users\bhargava\documents\github\ceaforarcgis\cea\plots\life_cycle\main.py", line 58, in __init__
    self.data_processed = self.preprocessing_building_costs()
  File "c:\users\bhargava\documents\github\ceaforarcgis\cea\plots\life_cycle\main.py", line 86, in preprocessing_building_costs
    data_raw = pd.read_csv(self.locator.get_costs_operation_file()).set_index('Name')
  File "c:\users\bhargava\anaconda2\envs\cea\lib\site-packages\pandas\io\parsers.py", line 655, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "c:\users\bhargava\anaconda2\envs\cea\lib\site-packages\pandas\io\parsers.py", line 405, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "c:\users\bhargava\anaconda2\envs\cea\lib\site-packages\pandas\io\parsers.py", line 764, in __init__
    self._make_engine(self.engine)
  File "c:\users\bhargava\anaconda2\envs\cea\lib\site-packages\pandas\io\parsers.py", line 985, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "c:\users\bhargava\anaconda2\envs\cea\lib\site-packages\pandas\io\parsers.py", line 1605, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 394, in pandas._libs.parsers.TextReader.__cinit__ (pandas\_libs\parsers.c:4209)
  File "pandas/_libs/parsers.pyx", line 710, in pandas._libs.parsers.TextReader._setup_parser_source (pandas\_libs\parsers.c:8873)
IOError: File C:\reference-case-open\baseline\outputs\data\costs\operation_costs.csv does not exist


Traceback (most recent call last):
  File "C:\Users\Bhargava\AppData\Roaming\ESRI\Desktop10.5\ArcToolbox\My Toolboxes\cea\interfaces\arcgis\arcgishelper.py", line 68, in execute
    run_cli(self.cea_tool, **kwargs)
  File "C:\Users\Bhargava\AppData\Roaming\ESRI\Desktop10.5\ArcToolbox\My Toolboxes\cea\interfaces\arcgis\arcgishelper.py", line 155, in run_cli
    raise Exception('Tool did not run successfully')
Exception: Tool did not run successfully

Failed to execute (Plots).
Failed at Thu Mar 29 15:21:50 2018 (Elapsed Time: 22.82 seconds)

**Comment by daren-thomas** [comment]
```
IOError: File C:\reference-case-open\baseline\outputs\data\potentials\solar\B01_SC_ET.csv does not exist
```
@shanshanhsieh do you know how to produce this file?

**Comment by daren-thomas** [comment]
Currently blocked by #1202

**Comment by shanshanhsieh** [comment]
@daren-thomas , yea, we only figured that it make sense to run both SC_FP and SC_ET should be run for the optimization. However, that was not considered in previous scenarios, this will eventually be the next step after the optimization branch is merged. So ideas are welcome, feel free to make an issue and assign it to me : )

**Comment by daren-thomas** [comment]
Also, I get a `KeyError: "['SC_capacity_W'] not in index"` with this stack trace when running `cea plots`:

```
energy demand plots successfully saved in plots folder of scenario:  C:\reference-case-open\baseline
life cycle plots successfully saved in plots folder of scenario:  C:\reference-case-open\baseline
c:\users\darthoma\documents\github\cityenergyanalyst\cea\plots\optimization\pareto_curve.py:69: RankWarning:

Polyfit may be poorly conditioned

Traceback (most recent call last):
  File "C:\Users\darthoma\AppData\Local\conda\conda\envs\cea\Scripts\cea-script.py", line 11, in <module>
    load_entry_point('cityenergyanalyst', 'console_scripts', 'cea')()
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\interfaces\cli\cli.py", line 33, in main
    script_module.main(config)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\plots\plots_main.py", line 76, in main
    plots_main(config)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\plots\plots_main.py", line 56, in plots_main
    plots_optimization(locator, config)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\plots\optimization\main.py", line 41, in plots_main
    plots.pareto_final_generation_capacity_installed()
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\plots\optimization\main.py", line 278, in pareto_final_generation_capacity_installed
    plot = pareto_capacity_installed(data, self.analysis_fields, self.renewable_sources_fields, title, output_path)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\plots\optimization\pareto_capacity_installed.py", line 15, in pareto_capacity_installed
    traces_graph = calc_graph(analysis_fields, data_frame)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\plots\optimization\pareto_capacity_installed.py", line 55, in calc_graph
    data['total'] = total = data[analysis_fields].sum(axis=1)
  File "C:\Users\darthoma\AppData\Local\conda\conda\envs\cea\lib\site-packages\pandas\core\frame.py", line 1958, in __getitem__
    return self._getitem_array(key)
  File "C:\Users\darthoma\AppData\Local\conda\conda\envs\cea\lib\site-packages\pandas\core\frame.py", line 2002, in _getitem_array
    indexer = self.loc._convert_to_indexer(key, axis=1)
  File "C:\Users\darthoma\AppData\Local\conda\conda\envs\cea\lib\site-packages\pandas\core\indexing.py", line 1231, in _convert_to_indexer
    raise KeyError('%s not in index' % objarr[mask])
KeyError: "['SC_capacity_W'] not in index"
```

**Comment by BhargavaKrishnaSreepathi** [comment]
Also, I get a KeyError: "['SC_capacity_W'] not in index" with this stack trace when running cea plots:

I am responsible for this error, as the new PR changes this to two components. namely SC_ET_capacity_W and SC_FP_capacity_W. i will make changes regarding the same

**Comment by JIMENOFONSECA** [comment]
@daren-thomas this is ready to be tested again

**Comment by daren-thomas** [comment]
@BhargavaKrishnaSreepathi just checked - it's still not working. Did you commit your fix to this branch or somewhere else?

**Comment by BhargavaKrishnaSreepathi** [comment]
@daren: i did not make changes, it was my understanding that Jimeno is now working on this

**Comment by JIMENOFONSECA** [comment]
@daren-thomas this is ready to be tested again. Here Bhargava added some modifications to fix the issue with the solar collector.

**Comment by daren-thomas** [comment]
So... now I get this error with `cea optimization`:
```
Storage Optimization Ready
 Slave Optimization done ( 5.7  seconds used for this task)
Traceback (most recent call last):
  File "C:\Users\darthoma\AppData\Local\conda\conda\envs\cea\Scripts\cea-script.py", line 11, in <module>
    load_entry_point('cityenergyanalyst', 'console_scripts', 'cea')()
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\interfaces\cli\cli.py", line 33, in main
    script_module.main(config)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\optimization\optimization_main.py", line 113, in main
    moo_optimization(locator=locator, weather_file=weather_file, gv=gv, config=config)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\optimization\optimization_main.py", line 65, in moo_optimization
    network_features, gv, config, prices)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\optimization\master\master_main.py", line 187, in evolutionary_algo_main
    a = objective_function(i, ind, genCP)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\optimization\master\master_main.py", line 100, in objective_function
    network_features, gv, config, prices, individual_number, generation)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\optimization\master\evaluation.py", line 122, in evaluation_main
    QUncoveredAnnual, solar_features, network_features, gv, config, prices)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\optimization\master\cost_model.py", line 387, in addCosts
    Capex_a_pump, Opex_fixed_pump = pumps.calc_Ctot_pump(master_to_slave_vars, buildList, locator.get_optimization_network_results_folder(), ntwFeat, gv, locator, prices)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\technologies\pumps.py", line 86, in calc_Ctot_pump
    Capex_a, Opex_fixed = calc_Cinv_pump(deltaPmax, mdotnMax_kgpers, PUMP_ETA, gv, locator)  # investment of Machinery
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\technologies\pumps.py", line 160, in calc_Cinv_pump
    Inv_a = pump_cost_data.iloc[0]['a']
  File "C:\Users\darthoma\AppData\Local\conda\conda\envs\cea\lib\site-packages\pandas\core\indexing.py", line 1328, in __getitem__
    return self._getitem_axis(key, axis=0)
  File "C:\Users\darthoma\AppData\Local\conda\conda\envs\cea\lib\site-packages\pandas\core\indexing.py", line 1749, in _getitem_axis
    self._is_valid_integer(key, axis)
  File "C:\Users\darthoma\AppData\Local\conda\conda\envs\cea\lib\site-packages\pandas\core\indexing.py", line 1638, in _is_valid_integer
    raise IndexError("single positional indexer is out-of-bounds")
IndexError: single positional indexer is out-of-bounds
```

I'm working on the standard reference case, basically following this workflow:

- `cea extract-reference-case`
- `cea data-helper`
- `cea demand`
- `cea operation-costs`
- `cea mobility`
- `cea emissions`
- `cea embodied-energy`
- `cea photovoltaic`
- `cea solar-collector --type-scpanel SC1`
- `cea solar-collector --type-scpanel SC2`
- `cea photovoltaic-thermal`
- `cea thermal-network-matrix`
- `cea optimization`

this is where i'd like to do `cea plots` and merge, but... the error above...

**Comment by JIMENOFONSECA** [comment]
@BhargavaKrishnaSreepathi Could you check what is wrong with the optimization?

**Comment by JIMENOFONSECA** [comment]
@BhargavaKrishnaSreepathi @roglen I think the last PR of thermal network created a bu gin optimization. could you guys have an exchange on this?

To replicate this error I run the thermal network (now in master) and then try to run optimization for the reference case.

image

**Comment by roglen** [comment]
@JIMENOFONSECA @BhargavaKrishnaSreepathi I think the source is not from the last pull request since this error originates from `cea/technologies/substation.py`, the only files edited by the last PR were `cea/technologies/substation_matrix.py` and `cea/therchnologies/thermal_network/thermal_network_matrix.py`
Outputs of the files have remained the same.

**Comment by BhargavaKrishnaSreepathi** [comment]
@daren-thomas: i fixed it, and followed every step you mentioned in the comment in the anaconda prompt and it runs smoothly. The error which lead to this was, I changed the supply_systems.xls file for the SIN scenario (added a sheet), which I did not do for the CH scenario (should have done, my bad). But now it is fixed. Just an additional layer for testing in future, that we test the `reference-case-open` for both `CH` and `SIN` scenarios (if this thing is not already being done)

**Comment by JIMENOFONSECA** [comment]
So i just pushed some changes related to dependencies.
please do
- conda env update.
- pip install -e .[dev]
- cea install-toolbox

**Pull request merged**
