### PR TITLE
I 1255 refactoring solar plots

### PR DESCRIPTION
**Pull request by JIMENOFONSECA**
@daren-thomas as requested.

### CODE REVIEW

**Comment by JIMENOFONSECA** [comment]
@daren-thomas fixed!, please check again.

**Comment by daren-thomas** [comment]
@JIMENOFONSECA it still does not run through...

```
technology potential plots successfully saved in plots folder of scenario:  C:\reference-case-open\baseline
done - time elapsed: 11.2f seconds
energy demand plots successfully saved in plots folder of scenario:  C:\reference-case-open\baseline
life cycle plots successfully saved in plots folder of scenario:  C:\reference-case-open\baseline
Traceback (most recent call last):
  File "C:\Users\darthoma\AppData\Local\conda\conda\envs\cea\Scripts\cea-script.py", line 11, in <module>
    load_entry_point('cityenergyanalyst', 'console_scripts', 'cea')()
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\interfaces\cli\cli.py", line 33, in main
    script_module.main(config)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\plots\plots_main.py", line 76, in main
    plots_main(config)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\plots\plots_main.py", line 56, in plots_main
    plots_optimization(locator, config)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\plots\optimization\main.py", line 36, in plots_main
    plots = Plots(locator, individual, generations, config)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\plots\optimization\main.py", line 164, in __init__
    self.individual, self.config)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\plots\optimization\main.py", line 275, in preprocessing_individual_data
    df_current_individual[ind] = individual_barcode_list[i]
IndexError: list index out of range
```

Maybe my optimization results are not good? I tried to run the optimization script, but got this:

```
λ cea optimization
Traceback (most recent call last):
  File "C:\Users\darthoma\AppData\Local\conda\conda\envs\cea\Scripts\cea-script.py", line 11, in <module>
    load_entry_point('cityenergyanalyst', 'console_scripts', 'cea')()
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\interfaces\cli\cli.py", line 32, in main
    script_module = importlib.import_module(module_path)
  File "C:\Users\darthoma\AppData\Local\conda\conda\envs\cea\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\optimization\optimization_main.py", line 13, in <module>
    import cea.optimization.master.master_main as master
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\optimization\master\master_main.py", line 12, in <module>
    import cea.optimization.master.evaluation as evaluation
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\optimization\master\evaluation.py", line 12, in <module>
    import cea.optimization.master.summarize_network as nM
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\optimization\master\summarize_network.py", line 14, in <module>
    from cea.optimization.constants import K_DH, T_GROUND, ZERO_DEGREES_CELSIUS_IN_KELVIN
ImportError: cannot import name T_GROUND
```

I checked master and got the same error message. So... It seems master is now broken?

**Comment by JIMENOFONSECA** [comment]
@BhargavaKrishnaSreepathi Hi bhargava would you mind checking this? I think I might have slipped some parts when I added the Ground temperature calculation. my bad..

**Comment by BhargavaKrishnaSreepathi** [comment]
@JIMENOFONSECA : made commits to fix the errors raising from the T_ground, and the plots run except for 'thermal_networks\network_plot.py', which I am not quite sure. 

Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm 2017.3.3\helpers\pydev\pydevd.py", line 1668, in <module>
    main()
  File "C:\Program Files\JetBrains\PyCharm 2017.3.3\helpers\pydev\pydevd.py", line 1662, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Program Files\JetBrains\PyCharm 2017.3.3\helpers\pydev\pydevd.py", line 1072, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:/Users/Bhargava/Documents/GitHub/CEAforArcGIS/cea/plots/plots_main.py", line 80, in <module>
    main(cea.config.Configuration())
  File "C:/Users/Bhargava/Documents/GitHub/CEAforArcGIS/cea/plots/plots_main.py", line 76, in main
    plots_main(config)
  File "C:/Users/Bhargava/Documents/GitHub/CEAforArcGIS/cea/plots/plots_main.py", line 66, in plots_main
    plots_thermal_network(locator, config)
  File "C:\Users\Bhargava\Documents\GitHub\CEAforArcGIS\cea\plots\thermal_networks\main.py", line 55, in plots_main
    plots.heat_network_plot()
  File "C:\Users\Bhargava\Documents\GitHub\CEAforArcGIS\cea\plots\thermal_networks\main.py", line 393, in heat_network_plot
    plot = network_plot(data, title, output_path, analysis_fields, building_demand_data, all_nodes)
  File "C:\Users\Bhargava\Documents\GitHub\CEAforArcGIS\cea\plots\thermal_networks\network_plot.py", line 144, in network_plot
    nx.set_node_attributes(graph, 'node_colors', node_colors)
  File "C:\Users\Bhargava\Anaconda2\envs\cea\lib\site-packages\networkx\classes\function.py", line 654, in set_node_attributes
    G.nodes[n][name] = values
TypeError: unhashable type: 'dict'

**Pull request merged**
