### PR TITLE
Thermal network simulation config file

### PR DESCRIPTION
**Pull request by martin-mosteiro**
This PR changes a few lines in `thermal_network.py` so that whether the representative week per month method is defined by the `thermal_network` section of the config file, not `thermal_network_optimization`. 

Up until now the variable was called as `config.thermal_network_optimization.use_representative_week_per_month`, so whether the representative week method is used or not was defined not by the thermal-network section of the config file, but by the thermal-network-optimization section (i.e., when running thermal network simulation the optimization configuration overrides the simulation configuration).

### CODE REVIEW

**Comment by martin-mosteiro** [comment]
@shanshanhsieh your latest commit does not pass the tests - but I believe Jenkins wasn't working anyway?
Did it pass the tests locally on your computer?

**Comment by shanshanhsieh** [comment]
yep, cea test ran through on my laptop

**Comment by martin-mosteiro** [comment]
Thanks @shanshanhsieh for the fix in the optimization script. The tests pass locally on my computer. As described in #2034 Jenkins was having some problems so it's being restarted, so I think this PR should be passed pending Jenkins approval.

**Comment by martin-mosteiro** [comment]
Issue #2064 will also be solved by this PR

**Pull request merged**
