### PR TITLE
I1078 thermal network plots

### PR DESCRIPTION
**Pull request by roglen**
Includes first network plots

To test:
- [x] run thermal_network_matrix.py
- [x] enter "thermal_network" under dashboard-categories in the cea.config file
- [x] run cea/plots/plots_main.py
- [x] verify that 4 .html and 2 .png plots are created

### CODE REVIEW

**Comment by shanshanhsieh** [comment]
@roglen , the code runs well!

Here are some suggestions to the graph to make it easier to understand:

*Loss Duration Curve*
- In the table, change the column names to *Peak [kW]* and *Yearly [MWh]*, also, change *Network heat* to *Thermal loss*? 
- In the graph, change y-axis to *Thermal losses/Pumping energy*

*Supply/Return T*
- Please change Tsupply,return to deg C

*Relative Heat and Pressure Losses*
- Change name or add more description on what it is, e.g. Annual Losses/Annual cooling demand 
- The output is a bit weird
image

*Heat and Pressure Losses*
- The output is a bit weird
image

*the two .png figures*
- change file name, these are not curves.
- include legend (if possible) 
- are the losses average? 
- label the plants
- don't know if it's easy, but maybe we can show the peak demand of each customer by the size of the dot?

**Comment by roglen** [comment]
Made requested changes. 
Interactive network plot will be in a separate pull request.

@shanshanhsieh can you check again please?

**Comment by JIMENOFONSECA** [comment]
@shanshanhsieh let me know when you review it so we can merge. please do approve the changes requested

**Comment by roglen** [comment]
I am moving this into a new pull request since there are a lot of files shown as changed which shouldn't be there.

**Pull request closed without merging**
