### PR TITLE
Optimization cooling

### PR DESCRIPTION
**Pull request by JIMENOFONSECA**
Alright, I believe we can start to test this exhaustively.
Since lots of changes were created,

Kindly help me to have 10 eyes to make sure that this time we get this right. Kindly test it separately:

@daren-thomas @martin-mosteiro  take the heating case, please (case study in here:https://we.tl/t-yk3plUj3wq)

[general]
project = E:\CASE-EXECUTIVE-COURSE
scenario-name = baseline
scenario = {general:project}/{general:scenario-name}
multiprocessing = true
number-of-cpus-to-keep-free = 0
debug = false

[decentralized]
detailed-electricity-pricing = false

[optimization]
district-heating-network = true
district-cooling-network = false
detailed-electricity-pricing = false
population-size =
number-of-generations = 5
random-seed = 100

@shanshanhsieh, @gabriel-happle  take the cooling case, please (case study in here:https://we.tl/t-yk3plUj3wq)

[general]
project = E:\CASE-EXECUTIVE-COURSE
scenario-name = baseline
scenario = {general:project}/{general:scenario-name}
multiprocessing = true
number-of-cpus-to-keep-free = 0
debug = false

[decentralized]
detailed-electricity-pricing = false

[optimization]
district-heating-network = true
district-cooling-network = false
detailed-electricity-pricing = false
population-size =
number-of-generations = 5
random-seed = 100

HOW TO:
1. run decentralized optimization (the rest is inside the case study already)
2. run centralized optimization.
3. If completed, please check the plots of supply_systems and optimization_overview and report back.

Main changes:
0. Created a new case study to test CEA.
download it  from here: https://we.tl/t-yk3plUj3wq

---Existing one is not realistic enough in terms of geometry and location. It makes difficult to have a feeling of what is a 'good value' of the optimization.
---The case study is based in Switzerland, yet it has cooling and heating seasons. It should be possible to use it for testing both heating and cooling networks/systems.

1. remade the whole optimization code from scratch for cooling
---Found issues regarding technology models. Solved together with Shanshan Hsieh.
-----Absorption chillers' database had some errors. 
-----Daily storage unit had some errors in the model.
---Found issues regarding miscalculations of costs, emissions and pen. Solved
-----Fuels were not correctly calculated
-----electricity costs were sometimes calculated twice.
-----Lack of transparency in some numbers (hard-core numbers seemed to help the algorithm to converge without explanation.

2. remade the whole optimization code for heating.
---Found issues regarding miscalculations of costs, emissions and pen. Solved
-----Fuels were not correctly calculated
-----electricity costs were sometimes calculated twice.
-----Lack of transparency in some numbers (hard-core numbers seemed to help the algorithm to converge without explanation.

3. remade the genetic algorithm 
----found issues regarding crossover and mutations of continues and discrete variables. Solved.
-------continuous and discrete variables require different crossover and mutations, otherwise, the learning process of the algorithm is affected.
-------the algorithm was not converging and will not after 100 generations and 92 individuals minimum.

4. remade the optimization and supply system graphs.
----found issues regarding to how variables were named and called. It was virtually impossible to use the previous ones due to the miscalculations found in 2 and 3.

Thank you!

### CODE REVIEW

**Comment by shanshanhsieh** [comment]
@JIMENOFONSECA 
while running optimization_main, this is missing...
image

**Comment by JIMENOFONSECA** [comment]
@shanshanhsieh fixed.

**Comment by martin-mosteiro** [comment]
So how exactly should we test this? Change the config file as you specified and run `optimization_main`?

I got the following:
```
﻿SUPPLY SYSTEMS OPTIMIZATION
    runfile('C:/Users/Assistenz/Documents/GitHub/CityEnergyAnalyst/cea/optimization/optimization_main.py', wdir='C:/Users/Assistenz/Documents/GitHub/CityEnergyAnalyst/cea/optimization')
  File "C:\Program Files\JetBrains\PyCharm 2018.3.3\helpers\pydev\_pydev_bundle\pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "C:/Users/Assistenz/Documents/GitHub/CityEnergyAnalyst/cea/optimization/optimization_main.py", line 166, in <module>
    main(cea.config.Configuration())
  File "C:/Users/Assistenz/Documents/GitHub/CityEnergyAnalyst/cea/optimization/optimization_main.py", line 117, in main
    moo_optimization(locator=locator, weather_file=weather_file, config=config)
  File "C:/Users/Assistenz/Documents/GitHub/CityEnergyAnalyst/cea/optimization/optimization_main.py", line 94, in moo_optimization
    network_features, config, prices, lca)
  File "C:\Users\Assistenz\Documents\GitHub\CityEnergyAnalyst\cea\optimization\master\master_main.py", line 122, in non_dominated_sorting_genetic_algorithm
    ref_points = tools.uniform_reference_points(NOBJ, P)
AttributeError: 'module' object has no attribute 'uniform_reference_points'
```

**Comment by JIMENOFONSECA** [comment]
Old version of deap library? Maybe you could update the libraries of cea from the console doing pip install .[dev]?
On 24 Sep 2019, 18:49 +0800, Martín Mosteiro-Romero <notifications@github.com>, wrote:

So how exactly should we test this? Change the config file as you specified and run optimization_main?

I got the following:

﻿SUPPLY SYSTEMS OPTIMIZATION

    runfile('C:/Users/Assistenz/Documents/GitHub/CityEnergyAnalyst/cea/optimization/optimization_main.py', wdir='C:/Users/Assistenz/Documents/GitHub/CityEnergyAnalyst/cea/optimization')

  File "C:\Program Files\JetBrains\PyCharm 2018.3.3\helpers\pydev\_pydev_bundle\pydev_umd.py", line 197, in runfile

    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script

  File "C:/Users/Assistenz/Documents/GitHub/CityEnergyAnalyst/cea/optimization/optimization_main.py", line 166, in <module>

    main(cea.config.Configuration())

  File "C:/Users/Assistenz/Documents/GitHub/CityEnergyAnalyst/cea/optimization/optimization_main.py", line 117, in main

    moo_optimization(locator=locator, weather_file=weather_file, config=config)

  File "C:/Users/Assistenz/Documents/GitHub/CityEnergyAnalyst/cea/optimization/optimization_main.py", line 94, in moo_optimization

    network_features, config, prices, lca)

  File "C:\Users\Assistenz\Documents\GitHub\CityEnergyAnalyst\cea\optimization\master\master_main.py", line 122, in non_dominated_sorting_genetic_algorithm

    ref_points = tools.uniform_reference_points(NOBJ, P)

AttributeError: 'module' object has no attribute 'uniform_reference_points'

**Comment by shanshanhsieh** [comment]
@JIMENOFONSECA , the supply system optimization for cooling was completed.

image

- All plots in `optimization overview` are working
- Two plots in the `supply system` are not running
1. Requirement curves electricity, `KeyError: 'E_hs_ww_req_W'`
2. Dispatch curve heating plant (there should be one for cooling plants?)


here are the parameters:
```
[optimization]
district-heating-network = false
district-cooling-network = true
detailed-electricity-pricing = false
population-size = 20
number-of-generations = 5
random-seed = 100
crossover-prob = 0.9
mutation-prob = 0.1
```

**Comment by JIMENOFONSECA** [comment]
@shanshanhsieh would you mind trying again with the plots?
I created one for District cooling Plant and fixed the one of electricity requirements

**Comment by daren-thomas** [comment]
I'm getting the following error when running the district-heating-systems workflow:

```
C:\Users\darthoma\Documents\GitHub\CityEnergyAnalyst (optimization-cooling -> origin)
λ cea optimization
City Energy Analyst version 2.22
Running `cea optimization` with the following parameters:
- general:scenario = C:\Users\darthoma\Documents\CityEnergyAnalyst\projects\reference-case-open\baseline
  (default: {general:project}\{general:scenario-name})
- general:multiprocessing = True
  (default: True)
- optimization:district-heating-network = True
  (default: True)
- optimization:district-cooling-network = False
  (default: False)
- optimization:detailed-electricity-pricing = False
  (default: False)
- optimization:population-size = 5
  (default: None)
- optimization:number-of-generations = 2
  (default: 100)
- optimization:random-seed = 100
  (default: 100)
- optimization:crossover-prob = 0.9
  (default: 0.9)
- optimization:mutation-prob = 0.1
  (default: 0.1)

---------------------------
ERROR: Missing input files:
Traceback (most recent call last):
  File "C:\Users\darthoma\Documents\CityEnergyAnalyst\Dependencies\Python\Scripts\cea-script.py", line 11, in <module>
    load_entry_point('cityenergyanalyst', 'console_scripts', 'cea')()
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\interfaces\cli\cli.py", line 59, in main
    cea_script.print_missing_input_files(config)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\scripts.py", line 48, in print_missing_input_files
    if 'created_by' in schema_data[method_name]
KeyError: 'get_geothermal_potential'
```

**Comment by daren-thomas** [comment]
@JIMENOFONSECA fixed the above error (`KeyError: 'get_geothermal_potential'`) and am now stuck here:

```
λ cea optimization
City Energy Analyst version 2.22
Running `cea optimization` with the following parameters:
- general:scenario = C:\Users\darthoma\Documents\CityEnergyAnalyst\projects\reference-case-open\baseline
  (default: {general:project}\{general:scenario-name})
- general:multiprocessing = True
  (default: True)
- optimization:district-heating-network = True
  (default: True)
- optimization:district-cooling-network = False
  (default: False)
- optimization:detailed-electricity-pricing = False
  (default: False)
- optimization:population-size = 5
  (default: None)
- optimization:number-of-generations = 2
  (default: 100)
- optimization:random-seed = 100
  (default: 100)
- optimization:crossover-prob = 0.9
  (default: 0.9)
- optimization:mutation-prob = 0.1
  (default: 0.1)
PRE-PROCESSING
PRE-PROCESSING 1/2: weather properties
PRE-PROCESSING 2/2: thermal networks
2.87251074691 seconds process time for Network summary for configuration 111111111
SUPPLY SYSTEMS OPTIMIZATION
Traceback (most recent call last):
  File "C:\Users\darthoma\Documents\CityEnergyAnalyst\Dependencies\Python\Scripts\cea-script.py", line 11, in <module>
    load_entry_point('cityenergyanalyst', 'console_scripts', 'cea')()
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\interfaces\cli\cli.py", line 64, in main
    script_module.main(config)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\optimization\optimization_main.py", line 117, in main
    moo_optimization(locator=locator, weather_file=weather_file, config=config)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\optimization\optimization_main.py", line 94, in moo_optimization
    network_features, config, prices, lca)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\optimization\master\master_main.py", line 122, in non_dominated_sorting_genetic_algorithm
    ref_points = tools.uniform_reference_points(NOBJ, P)
AttributeError: 'module' object has no attribute 'uniform_reference_points'
```

**Comment by shanshanhsieh** [comment]
@JIMENOFONSECA 
the two plots are still not working for me
1. Requirement curves electricity, KeyError: 'E_hs_ww_req_W'
```
  File "c:\users\shanshan\documents\cityenergyanalyst\cityenergyanalyst\cea\plots\base.py", line 163, in _plot_div_producer
    fig = plotly.graph_objs.Figure(data=self.calc_graph(), layout=self.layout)
  File "c:\users\shanshan\documents\cityenergyanalyst\cityenergyanalyst\cea\plots\supply_system\requirements_curve_electricity.py", line 100, in calc_graph
    trace = go.Bar(x=data.index, y=y, name=NAMING[field],
KeyError: 'E_PeakVCC_AS_req_W'
```
2. Dispatch curve cooling plant? (cant see this option in the dropdown)

**Comment by JIMENOFONSECA** [comment]
Did you updated the branch to the latest commit?




On 3 Oct 2019, 2:56 PM +0800, Shanshan Hsieh <notifications@github.com>, wrote:

@JIMENOFONSECA<https://github.com/JIMENOFONSECA>
the two plots are still not working for me

  1.  Requirement curves electricity, KeyError: 'E_hs_ww_req_W'

  File "c:\users\shanshan\documents\cityenergyanalyst\cityenergyanalyst\cea\plots\base.py", line 163, in _plot_div_producer
    fig = plotly.graph_objs.Figure(data=self.calc_graph(), layout=self.layout)
  File "c:\users\shanshan\documents\cityenergyanalyst\cityenergyanalyst\cea\plots\supply_system\requirements_curve_electricity.py", line 100, in calc_graph
    trace = go.Bar(x=data.index, y=y, name=NAMING[field],
KeyError: 'E_PeakVCC_AS_req_W'


  1.  Dispatch curve cooling plant? (cant see this option in the dropdown)

**Comment by shanshanhsieh** [comment]
@JIMENOFONSECA , i can plot the Dispatch curve cooling plant now.
but still getting the same error for *Requirement curves electricity,*
`
  File "c:\users\shanshan\documents\cityenergyanalyst\cityenergyanalyst\cea\plots\base.py", line 163, in _plot_div_producer
    fig = plotly.graph_objs.Figure(data=self.calc_graph(), layout=self.layout)
  File "c:\users\shanshan\documents\cityenergyanalyst\cityenergyanalyst\cea\plots\supply_system\requirements_curve_electricity.py", line 100, in calc_graph
    trace = go.Bar(x=data.index, y=y, name=NAMING[field],
KeyError: 'E_PeakVCC_AS_req_W'

`

**Comment by JIMENOFONSECA** [comment]
@JIMENOFONSECA kindly update and try again, thanks! Help me also out, to see if the results make sense please. It is hard to see it and I might be missing stuff.

**Comment by daren-thomas** [comment]
I can run the `cea workflow --workflow district-heating-system` all the way through it seems (running it again just to be sure, will know more tomorrow morning)

I have errors with the following plots:

- Scenario comparisons
  - Comparison Annual Costs
- Supply System
  - Dispatch curve for cooling plant in system #1
    - (`KeyError: 'Q_DailyStorage_gen_directload_W'`)
  - Supply system map for system #1 of gen2 - baseline
    - (`TypeError: string indices must be integers, not str`)

I committed a jupyter notebook to the `notebooks` folder in the repository that adds one dashboard per plot category, containing all the plots. This can help testing the plots.

**Comment by martin-mosteiro** [comment]
Based on @daren-thomas's feedback today during the meeting, I am now testing from the CEA console instead of the dashboard. I get the following:
```
C:\Users\Assistenz\Documents\GitHub\CityEnergyAnalyst (optimization-cooling -> origin)
λ cea optimization
City Energy Analyst version 2.22
Running `cea optimization` with the following parameters:
- general:scenario = C:\CASE-EXECUTIVE-COURSE\baseline
  (default: {general:project}\{general:scenario-name})
- general:multiprocessing = False
  (default: True)
- optimization:district-heating-network = True
  (default: True)
- optimization:district-cooling-network = False
  (default: False)
- optimization:detailed-electricity-pricing = False
  (default: False)
- optimization:population-size = None
  (default: None)
- optimization:number-of-generations = 100
  (default: 100)
- optimization:random-seed = 100
  (default: 100)
- optimization:crossover-prob = 0.9
  (default: 0.9)
- optimization:mutation-prob = 0.1
  (default: 0.1)
PRE-PROCESSING
PRE-PROCESSING 1/2: weather properties
PRE-PROCESSING 2/2: thermal networks
4.89399816368 seconds process time for Network summary for configuration 11111111111111111
SUPPLY SYSTEMS OPTIMIZATION
Traceback (most recent call last):
  File "C:\Users\Assistenz\Documents\CityEnergyAnalyst\Dependencies\Python\Scripts\cea-script.py", line 11, in <module>
    load_entry_point('cityenergyanalyst', 'console_scripts', 'cea')()
  File "c:\users\assistenz\documents\github\cityenergyanalyst\cea\interfaces\cli\cli.py", line 64, in main
    script_module.main(config)
  File "c:\users\assistenz\documents\github\cityenergyanalyst\cea\optimization\optimization_main.py", line 117, in main
    moo_optimization(locator=locator, weather_file=weather_file, config=config)
  File "c:\users\assistenz\documents\github\cityenergyanalyst\cea\optimization\optimization_main.py", line 94, in moo_optimization
    network_features, config, prices, lca)
  File "c:\users\assistenz\documents\github\cityenergyanalyst\cea\optimization\master\master_main.py", line 122, in non_dominated_sorting_genetic_algorithm
    ref_points = tools.uniform_reference_points(NOBJ, P)
AttributeError: 'module' object has no attribute 'uniform_reference_points'
```
@JIMENOFONSECA any ideas?

**Comment by JIMENOFONSECA** [comment]
@martin-mosteiro I believe you have an old version of DEAP installed can you check? Maybe a reinstall of the setup of CEA can help? I made a comment about this above.

**Comment by martin-mosteiro** [comment]
@JIMENOFONSECA Yeah, sorry about that, you're right: didn't notice it was the same issue.

Reinstalling worked (and that's how I was testing on pycharm) but yesterday @daren-thomas  noticed there were two different installations on the computer I was testing on. I guess the console is using the wrong CEA installation, hence why the error happened again.

**Comment by JIMENOFONSECA** [comment]
@daren-thomas I made some changes. would you mind trying again? you need to run the optimization again, thanks!

**Comment by gabriel-happle** [comment]
@JIMENOFONSECA sorry, I didn't get the chance to test this yet. Do you mind uploading the case study again? The link is not valid anymore.

**Comment by shanshanhsieh** [comment]
@JIMENOFONSECA , testing is completed on my side.
i can run through optimization with district cooling = true, and access all the optimization-related plots.
shall i send you the results?

**Comment by JIMENOFONSECA** [comment]
@shanshanhsieh nop, all good, but if you find inconsistencies in the plots kindly create an issue, thanks!!

**Comment by daren-thomas** [comment]
@JIMENOFONSECA supply system plots on newest version of this branch (ran workflow last night for DH, re-ran `optimization` and `multi-criteria-analysis` this morning with fresh pulls. Status: All work except for "Dispatch curve for cooling plant in system #1 (monthly) - baseline":

```
Traceback (most recent call last):
  File "C:\Users\darthoma\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\darthoma\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\darthoma\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\flask_restplus\api.py", line 584, in error_router
    return original_handler(e)
  File "C:\Users\darthoma\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\flask_restplus\api.py", line 584, in error_router
    return original_handler(e)
  File "C:\Users\darthoma\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\darthoma\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\darthoma\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\interfaces\dashboard\plots\routes.py", line 255, in route_div
    plot_div = plot.plot_div()
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\plots\base.py", line 160, in plot_div
    return self.cache.lookup_plot_div(self, self._plot_div_producer)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\plots\cache.py", line 50, in lookup_plot_div
    plot_div = producer()
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\plots\base.py", line 163, in _plot_div_producer
    fig = plotly.graph_objs.Figure(data=self.calc_graph(), layout=self.layout)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\plots\supply_system\dispatch_curve_cooling_plant.py", line 68, in calc_graph
    analysis_fields = self.remove_unused_fields(data, self.analysis_fields)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\plots\base.py", line 130, in remove_unused_fields
    return [field for field in fields if np.isclose(data[field].sum(), 1e-8)==False]
  File "C:\Users\darthoma\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\pandas\core\frame.py", line 2688, in __getitem__
    return self._getitem_column(key)
  File "C:\Users\darthoma\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\pandas\core\frame.py", line 2695, in _getitem_column
    return self._get_item_cache(key)
  File "C:\Users\darthoma\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\pandas\core\generic.py", line 2489, in _get_item_cache
    values = self._data.get(item)
  File "C:\Users\darthoma\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\pandas\core\internals.py", line 4115, in get
    loc = self.items.get_loc(item)
  File "C:\Users\darthoma\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\pandas\core\indexes\base.py", line 3080, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 140, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 162, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1492, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1500, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'Q_DailyStorage_gen_directload_W'
```

Configuration: 
```
- category: supply-system
    parameters: {generation: 2, individual: 1, scenario-name: baseline, timeframe: monthly}
    plot: dispatch_curve_cooling_plant
```

**Comment by JIMENOFONSECA** [comment]
@daren-thomas, so in essence that plot cannot run without optimizing for district cooling. How would you like to handle that error? in the front or the back-end. if so how?

**Pull request merged**
