### PR TITLE
remove faulty input requests

### PR DESCRIPTION
**Pull request by shanshanhsieh**
the PR resolves issue #2144
to test in Dashboard:
1. run create new project (zone, district, terrain, streets)
2. run data helper
the script should run through, and a `technology` folder should be created inside the `inputs` folder

### CODE REVIEW

**Comment by daren-thomas** [comment]
Oh dear, I get the following error:

```
City Energy Analyst version 2.17.1
Running `cea data-helper` with the following parameters:
- general:scenario = c:\temp\2145-shanshan-saves-the-day\baseline
  (default: C:\reference-case-open\baseline)
- data-helper:region = CH
  (default: CH)
- data-helper:databases = ['comfort', 'architecture', 'HVAC', 'internal-loads', 'supply', 'restrictions', 'technology']
  (default: ['comfort', 'architecture', 'HVAC', 'internal-loads', 'supply', 'restrictions', 'technology'])
Running data-helper with scenario = c:\temp\2145-shanshan-saves-the-day\baseline
Running data-helper with archetypes = ['comfort', 'architecture', 'HVAC', 'internal-loads', 'supply', 'restrictions', 'technology']
Process Process-1:
Traceback (most recent call last):
  File "C:\Users\darthoma\Documents\CityEnergyAnalyst\Dependencies\Python\lib\multiprocessing\process.py", line 267, in _bootstrap
    self.run()
  File "C:\Users\darthoma\Documents\CityEnergyAnalyst\Dependencies\Python\lib\multiprocessing\process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\interfaces\dashboard\tools\worker.py", line 19, in run_script
    script(**kwargs)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\api.py", line 32, in script_runner
    script_module.main(config)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\datamanagement\data_helper.py", line 421, in main
    technology_flag=technology_flag)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\datamanagement\data_helper.py", line 92, in data_helper
    archetypes_schedules = pd.read_excel(locator.get_archetypes_schedules(), use, index_col=0).T
  File "C:\Users\darthoma\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\pandas\util\_decorators.py", line 178, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\darthoma\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\pandas\util\_decorators.py", line 178, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\darthoma\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\pandas\io\excel.py", line 329, in read_excel
    **kwds)
  File "C:\Users\darthoma\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\pandas\io\excel.py", line 456, in parse
    **kwds)
  File "C:\Users\darthoma\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\pandas\io\excel.py", line 607, in _parse_excel
    sheet = self.book.sheet_by_name(asheetname)
  File "C:\Users\darthoma\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\xlrd\book.py", line 476, in sheet_by_name
    raise XLRDError('No sheet named <%r>' % sheet_name)
XLRDError: No sheet named 
```

Also, that looks to me as if `get_archetypes_schedules` is being used as an _input_ right? (see  line 92, in data_helper):  `archetypes_schedules = pd.read_excel(locator.get_archetypes_schedules(), use, index_col=0).T`

**Comment by daren-thomas** [comment]
Ran the tool from the command line and got this: `xlrd.biffh.XLRDError: No sheet named <u'UNIVERSITY'>`

**Comment by reyery** [comment]
> 
> 
> Ran the tool from the command line and got this: `xlrd.biffh.XLRDError: No sheet named <u'UNIVERSITY'>`

This error is the same as the one in #2123

**Comment by martin-mosteiro** [comment]
I've now added a UNIVERSITY archetype to the CH database, which didn't exist so far. Here's the assumptions for future references:
- CONSTRUCTION, SUPPLY, HVAC: all copied from SCHOOL archetype
- INDOOR COMFORT, INTERNAL LOADS: taken from SIA 2024 (2006) for room type Hörsaal
- schedules: taken from SIA 2024 (2006) for room type Hörsaal
- occupant density: kept occupant density from SCHOOL archetype (*not* 2024) due to the issue described in #2051 
Indoor comfort, internal loads and occupant schedules should eventually be updated to SIA 2024 (2015) (again, see #2051) but that is not part of this PR.

**Comment by daren-thomas** [comment]
image

CELEBRATION TIME COME ON!

**Comment by martin-mosteiro** [comment]
thanks @daren-thomas for finding the typo in the construction properties file.
murging now.
@daren-thomas can you find the typo in this comment?

**Pull request merged**
