### PR TITLE
Clean geometries from OpenStreetMap in zone-helper

### LINKED ISSUE #2764: zone_helper: Record's geometry type does not match collection schema's geometry type
**Describe the bug**
While creating a new case study on the CEA dashboard, I got a `ValueError: Record's geometry type does not match collection schema's geometry type: 'MultiPolygon' != 'on'`. Not sure how to debug this. This happened while running an older version of the dashboard, but I don't think this would be related to that.

**To Reproduce**
1. Go to CEA Dashboard, create a new project, create a new scenario
2. Select an area in the map for the zone file (in my case, the entire city of Zurich). Whether you select Sourroundings/Streets/Terrain/Weather or not shouldn't matter – I got the same error in both cases.
3. Hit Create

**Expected behaviour**
A scenario with all the buildings in Zurich should have been created.

**Screenshots**
Screen Shot 2020-06-08 at 14 20 05

**Hardware (please complete the following information):**
 - OS and version: Windows 10
 - City Energy Analyst v2.9.2

### PR DESCRIPTION
**Pull request by reyery**
This PR fixes #2764 by adding a new function to clean geometries from **OpenStreetMap** before processing it.

The issue is mainly caused by `geopandas` not able to export a GeoPandas DataFrame to a shapefile if any of its geometries are of type **`MultiPolygon`**. It solves it by trying to flatten any **`MultiPolygon`** into a single **`Polygon`**.

### CODE REVIEW

**Comment by martin-mosteiro** [comment]
Tested it on my computer and the shapefiles were created successfully. Thanks @reyery!

**Comment by martin-mosteiro** [comment]
Nope, not quite ready yet @reyery 
The zone_helper works, but `MultiPolygon` geometries still cause trouble for the solar radiation tool:
```
Traceback (most recent call last):
  File "c:\users\assistenz\documents\cityenergyanalyst\cityenergyanalyst\cea\worker.py", line 146, in worker
    run_job(config, job, server)
  File "c:\users\assistenz\documents\cityenergyanalyst\cityenergyanalyst\cea\worker.py", line 108, in run_job
    script(config=config, **parameters)
  File "c:\users\assistenz\documents\cityenergyanalyst\cityenergyanalyst\cea\api.py", line 58, in __call__
    self._runner.__call__(*args, **kwargs)
  File "c:\users\assistenz\documents\cityenergyanalyst\cityenergyanalyst\cea\api.py", line 38, in script_runner
    script_module.main(config)
  File "c:\users\assistenz\documents\cityenergyanalyst\cityenergyanalyst\cea\resources\radiation_daysim\radiation_main.py", line 485, in main
    config)
  File "c:\users\assistenz\documents\cityenergyanalyst\cityenergyanalyst\cea\resources\radiation_daysim\geometry_generator.py", line 533, in geometry_main
    height_col='height_ag', nfloor_col="floors_ag")
  File "c:\users\assistenz\documents\cityenergyanalyst\cityenergyanalyst\cea\resources\radiation_daysim\geometry_generator.py", line 235, in building_2d_to_3d
    data_preprocessed = BuildingData(locator, settings, geometry_terrain, height_col, nfloor_col)
  File "c:\users\assistenz\documents\cityenergyanalyst\cityenergyanalyst\cea\resources\radiation_daysim\geometry_generator.py", line 142, in __init__
    self.zone_building_solid_list = np.vectorize(self.calc_zone_building_solids)(self.zone_building_names)
  File "C:\Users\Assistenz\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\numpy\lib\function_base.py", line 1972, in __call__
    return self._vectorize_call(func=func, args=vargs)
  File "C:\Users\Assistenz\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\numpy\lib\function_base.py", line 2048, in _vectorize_call
    outputs = ufunc(*inputs)
  File "c:\users\assistenz\documents\cityenergyanalyst\cityenergyanalyst\cea\resources\radiation_daysim\geometry_generator.py", line 178, in calc_zone_building_solids
    face_footprint = burn_buildings(geometry, self.terrain_intersection_curves)
  File "c:\users\assistenz\documents\cityenergyanalyst\cityenergyanalyst\cea\resources\radiation_daysim\geometry_generator.py", line 379, in burn_buildings
    point_list_2D = geometry.exterior.coords
AttributeError: 'MultiPolygon' object has no attribute 'exterior'
```

**Comment by reyery** [comment]
It seems that some **`MultiPolygon`** were not able to be combined, (maybe they do not intersect at all, such as below) so they remained as **`MultiPolygon`**. In this case, when cleaning the geometries, it should just take the first geometry and discard the other. Or maybe separate them and duplicate their info.

image

**Comment by daren-thomas** [comment]
@martin-mosteiro @reyery what is the status of this PR?

**Comment by martin-mosteiro** [comment]
@reyery I tested the radiation script again as  discussed last week and got the same `AttributeError`:
Screen Shot 2020-06-19 at 10 25 44

Steps I followed:
1-Created a new case study of Zurich to make sure the shapefiles were created according to the latest commit.
2-Ran the various database mappers
3-Ran the radiation tool

**Comment by reyery** [comment]
@martin-mosteiro could you send me the building geometries again? weird. It seems to be working on my side when extracting the buildings for zurich using zone-helper then running radiation.

I think I will add a validation step at the beginning of the radiation script to check the zone shapefiles for Multipolygons first before running the actual simulation.

**Comment by daren-thomas** [comment]
@reyery can you please send me the files in question? I'll try and merge this today.

**Comment by reyery** [comment]
@daren-thomas you could use this file [site.zip](https://github.com/architecture-building-systems/CityEnergyAnalyst/files/4957617/site.zip) to test with the zone-helper. This site file only contains the `MultiPolygon` buildings above that were mainly causing the problem. 

OSM would return 2 sets of `MultiPolygon` each containing 2 `Polygon` (so a total of 4 footprints) within the site file but zone-helper will try to combine them and only take the first `Polygon` of the `MultiPolygon`.

So in the end there should only be 2 `Polygon` footprints as below

image

You should also be able to run radiation script with the output zone file.

**Comment by martin-mosteiro** [comment]
I have tested by doing the following:
1-Used the CEA GUI to generate a shapefile of the city center of Zurich (which contained problematic MultiPolygon buildings)
This worked well, as was already the case a month ago
2-Ran all the data helpers to complete the case study
3-Ran the solar radiation tool
This is still running, but has as of yet not crashed as it used to. So the PR looks good so far!

**Pull request merged**
