### PR TITLE
fixes #353

### LINKED ISSUE #353: Update installation guide for new radiation script

### PR DESCRIPTION
**Pull request by daren-thomas**

### CODE REVIEW

**Comment by JIMENOFONSECA** [comment]
@daren-thomas so it means that we do not need anymore the LFS?

**Comment by daren-thomas** [comment]
i think so... @JIMENOFONSECA i'm not sure. how would we test this? i'll check - in a separate issue.

**Comment by JIMENOFONSECA** [comment]
@daren-thomas I am confused, why does this PR then erases the line in the documentation that states that LFS is needed

**Comment by daren-thomas** [comment]
@JIMENOFONSECA I just checked: we don't need git lfs anymore. We used to have radiation data > 100MB stored in the repo, but we no longer do that. LFS is not needed to clone the repository and it is not needed to run the CEA (as tested yesterday with the ubuntu branch)

**Pull request merged**
